### ISSUE TITLE
File picker attachment loader should handle more cases

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1016]
copy similar code from here: https://github.com/miguelpruivo/flutter_file_picker/blob/9f0a811028a0944e9e23dad6002108a7ff17a6ec/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java#L89

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#requests`.

**Comment by zlshames** [comment]
Actually, after looking at their code, it's very similar to what I already implemented. Just compare again and make sure we aren't missing any cases. 

I don't think we need to handle any "dir" cases

**Comment by tneotia** [comment]
we switched to using file_picker itself
