### ISSUE TITLE
Replicate file picker intent

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1017]
https://github.com/miguelpruivo/flutter_file_picker/blob/9f0a811028a0944e9e23dad6002108a7ff17a6ec/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java#L189

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#requests`.

**Comment by tneotia** [comment]
We switched to using file_picker itself
