### ISSUE TITLE
Select multiple messages/attachments to be able to forward together all at once

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1018]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Blank` in `#requests`.

**Comment by zlshames** [comment]
Backlogged because we have a ton of other issues we need to get done

**Comment by CSab6482** [comment]
This might be related to issue #542

**Comment by tneotia** [comment]
done
