### ISSUE TITLE
Conversation list scrolls to the top when the app re-enters focus

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1026]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#feedback`.

**Comment by zlshames** [comment]
I’m not sure this is possible. My guess is this happens because we "paginate" the chat list. So when you leave and re-enter the app, the chat list re-loads/re-populates (i think) and it's causing the scroll up because only 10 are loaded at a time. I could be wrong, but this is my first assumption

**Comment by tneotia** [comment]
We could potentially update the chat list only when all the chats are loaded if we already have existing chat data. Don't know if that's a great idea though.

**Comment by zlshames** [comment]
That may be what we already do (re: `updateChatPosition()`) calls in the `ChatBloc()`. I just need to verify. Definitely going to need to diagnose the actual issue a bit more

**Comment by tneotia** [comment]
I tested it yesterday and the length of the chat list changes inside the stream builder when the app is put back in the foreground indicating that it's probably chunked but I could be wrong.

**Comment by zlshames** [comment]
> I tested it yesterday and the length of the chat list changes inside the stream builder when the app is put back in the foreground indicating that it's probably chunked but I could be wrong.

Nah, you're probably correct. In that case, maybe we do a more controlled processing for resuming the app. Like fetch the chats, but then compare the indexes of the new list and the previous list. If indexes are different, call `updateChatPosition()` for each of the out-of-place chats.

**Comment by tneotia** [comment]
fixed with zachs conditional chat list update
