### ISSUE TITLE
Images sent with empty text receive double timestamps (one for the image and one for the message)

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1027]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#feedback`.

**Comment by tneotia** [comment]
Tried to investigate this yesterday but couldn't figure out why. There doesn't seem to be any empty message that the timestamp is attached to which is weird.

**Comment by tneotia** [comment]
![image](https://user-images.githubusercontent.com/50850142/133479288-da90516c-32f5-4aaf-a4df-7c80f6caea47.png)
