### ISSUE TITLE
When attempting to share an image from Google Messages, the app crashes

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1040]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by CSab6482** [comment]
https://user-images.githubusercontent.com/53708281/124993937-0f434780-e013-11eb-869d-e0f24d9cc5c9.mp4

**Comment by CSab6482** [comment]
From @tneotia https://github.com/KasemJaffer/receive_sharing_intent/issues/173

**Comment by zlshames** [comment]
Marking this as hard because it technically just requires the lib (receive share intent) to be updated

**Comment by tneotia** [comment]
This no longer happens, I assume something is updated on the google messages end

**Comment by CSab6482** [comment]
I'm facing this same issue again on BB v1.11.4 and the 20230118 release of Google Messages

**Comment by tneotia** [comment]
fixed for good
