### ISSUE TITLE
Sometimes, messages/notifications don't go through

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1054]
This can range from no notifications coming in, to only some notifications coming in, and then requiring an exit/re-enter to the chat to load all messages.

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by CSab6482** [comment]
Here are some screenshots from my description and Zach's response on Discord
![image](https://user-images.githubusercontent.com/53708281/125212261-1b7d0e00-e27a-11eb-8aba-43ddea20598c.png)
![image](https://user-images.githubusercontent.com/53708281/125212269-2e8fde00-e27a-11eb-8269-fe08ed4a50e0.png)
and then the original screenshots
![Screenshot 1](https://cdn.discordapp.com/attachments/746560644995612752/863500953159860254/20210710_152244.jpg)
![Screenshot 2](https://cdn.discordapp.com/attachments/746560644995612752/863501098219601940/20210710_152314.jpg)

**Comment by zlshames** [comment]
Yep, definitely take a look at the `handleNewMessage` function in messages_view.dart

**Comment by tneotia** [comment]
@CSab6482 still reproducible on latest?

**Comment by CSab6482** [comment]
I think it's safe to close for now as I haven't experienced the bug in a while. This might have been fixed with the revamped notifications 👍
