### ISSUE TITLE
Show graphical feedback for when a tapback fails to deliver

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1081]
It would also be nice if tapping the not delivered graphic would prompt to restart iMessage or something

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#baffoonery`.

**Comment by CSab6482** [comment]
![Image](https://media.discordapp.net/attachments/768689186801975296/865052468680589312/image.png)

**Comment by zlshames** [comment]
Marking as medium just cuz I think the UI will be a little annoying to do. And getting the error feedback too

**Comment by tneotia** [comment]
done
