### ISSUE TITLE
quick react menu that is triggered by left to right swipe over message

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1096]
the menu would ideally extent from the touch point, and would react with the icon the touch point is over when released, so you can react in one gesture. radial, vertical or horizontal would all work. Visual feedback of which would be selected if you let go would be a good idea, along with a section you can let go in to trigger nothing?

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@isaac` in `#feedback`.

**Comment by jjoelj** [comment]
![SmartSelect_20210719-202950_Discord.jpg](https://user-images.githubusercontent.com/35714943/126257598-b03a0b73-7775-489e-a75c-9c82a745dfd3.jpg)

**Comment by tneotia** [comment]
I'm gonna close this one - at this point in time we have *way* too many potential gestures for message bubbles, and long press / slide is already taken
