### ISSUE TITLE
reactions to interactive messages are not aligned correctly

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1097]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

**Comment by CSab6482** [comment]
![Image](https://media.discordapp.net/attachments/746560644995612752/865827771544764476/SmartSelect_20210716-223011.jpg)

**Comment by zlshames** [comment]
Marking this as medium because this needs to be done correctly as to not mess up reactions on other message types. 

However, I think the fix is as easy as adding margin/padding to the top of the interactive message widget, so the Stack gets built correctly
