### ISSUE TITLE
Make progress indicators match the iOS theme, conditionally

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1101]
right now, all the progress indicators on images and what not are material theme. We should switch it to iOS for the iOS theme

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by zlshames** [comment]
@tneotia this can be closed, right?

**Comment by tneotia** [comment]
No this is the second half I was talking ab earlier in android dev

**Comment by tneotia** [comment]
Completed in full rewrite
