### ISSUE TITLE
Look into trimming memory to stay alive longer

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#1136]
Read this, it's an interesting read and probably something we should look into: https://developer.android.com/reference/android/content/ComponentCallbacks2

**Comment by CSab6482** [comment]
Could the next update add an option to download more RAM to our phones?

**Comment by zlshames** [comment]
> Could the next update add an option to download more RAM to our phones?

banned

**Comment by zlshames** [comment]
We should actually make a Dart function to handle trimming memory. For instance, in the CurrentChat context, we store image data in there. Let's trim that (remove image cache) from the CurrentChat to reduce the memory footprint to stay alive longer. I don't think it should be too hard. Just a matter of overriding the trim method in the Java, and have it call Dart to clear the Current Chat.

Hopefully that is possible... Idk if spinning up a Dart VM to trim memory is any more memory-efficient than not trimming it and not spinning up the VM

**Comment by zlshames** [comment]
Marking this as 1.4.0 because it would help keep it in memory and keep receiving notifications

**Comment by tneotia** [comment]
> For instance, in the CurrentChat context, we store image data in there. Let's trim that (remove image cache) from the CurrentChat to reduce the memory footprint to stay alive longer

How does storing images in the cache folder affect our RAM usage?

**Comment by zach-threatq** [comment]
> > For instance, in the CurrentChat context, we store image data in there. Let's trim that (remove image cache) from the CurrentChat to reduce the memory footprint to stay alive longer
> 
> How does storing images in the cache folder affect our RAM usage?

When I say cache here, I don't mean the files in the filesystem. What I'm talking about is how we cache the images in memory, in CurrentChat. We store the actual bytes in memory afaik. Check the ImageWidget file

**Comment by zlshames** [comment]
> > For instance, in the CurrentChat context, we store image data in there. Let's trim that (remove image cache) from the CurrentChat to reduce the memory footprint to stay alive longer
> 
> How does storing images in the cache folder affect our RAM usage?

When I say cache here, I don't mean the files in the filesystem. What I'm talking about is how we cache the images in memory, in CurrentChat. We store the actual bytes in memory afaik. Check the ImageWidget file

**Comment by tneotia** [comment]
Hmm I remember now.... Is there any real benefit to caching the bytes in memory? It can't be that much slower to just load it from the filesystem right?

**Comment by zlshames** [comment]
> Hmm I remember now.... Is there any real benefit to caching the bytes in memory? It can't be that much slower to just load it from the filesystem right?

We'd probably want/need to do some performance testing for that. See if it's worth caching or not. I say that if it's > 100ms difference, we keep using it.

**Comment by tneotia** [comment]
Here are my results:

I/flutter ( 3582): Attachment loaded cached in 0 ms
I/flutter ( 3582): Attachment loaded cached in 0 ms
I/flutter ( 3582): Attachment loaded cached in 0 ms
I/flutter ( 3582): Attachment loaded filesystem in 37 ms
I/flutter ( 3582): Attachment loaded filesystem in 22 ms
I/flutter ( 3582): Attachment loaded filesystem in 48 ms

3mb image, 1.5mb image, and 185kb image. What do you think @zlshames ?

**Comment by zlshames** [comment]
> Here are my results:
> 
> I/flutter ( 3582): Attachment loaded cached in 0 ms
> I/flutter ( 3582): Attachment loaded cached in 0 ms
> I/flutter ( 3582): Attachment loaded cached in 0 ms
> I/flutter ( 3582): Attachment loaded filesystem in 37 ms
> I/flutter ( 3582): Attachment loaded filesystem in 22 ms
> I/flutter ( 3582): Attachment loaded filesystem in 48 ms
> 
> 3mb image, 1.5mb image, and 185kb image. What do you think @zlshames ?

ehhhh, i would probably leave the caching tbh

**Comment by tneotia** [comment]
Is this complete or do we need to trim other stuff?

**Comment by zlshames** [comment]
tbh I think we still need to keep it open. I still think it's a valid way to reduce the footprint of the app, while also following Android's memory standards

**Comment by tneotia** [comment]
Completed in full rewrite
