### ISSUE TITLE
Send hand-drawn images

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1213]
See https://pub.dev/packages/sketcher?

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@monicow` in `#requests`.

**Comment by zlshames** [comment]
We don’t have to use Apple's native system. Maybe just turn a drawing into a GIF or even just a PNG would be cool

**Comment by zlshames** [comment]
Idk if we can do this, but what we can do is use a "signature pad" to create an image that we can send. 

I looked at some packages and found this one to be the best and most "elegant":

https://pub.dev/packages/hand_signature

The other ones don't have as many drawing options

**Comment by tneotia** [comment]
done
