### ISSUE TITLE
look into disabling FCM option and make always open socket connection

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1230]
for Huawei devices

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#android-bugs`.

**Comment by CSab6482** [comment]
This could also be beneficial for GrapheneOS users or other users that have removed Google services from their phones. Issue #893 may be related.

**Comment by CSab6482** [comment]
https://supabase.io/

**Comment by tneotia** [comment]
This has been added. Unfortunately you cannot swipe away the app, but whenever its in the background, it works
