### ISSUE TITLE
Messages are reversed in date order

### ISSUE THREAD

**Issue by tneotia** [BlueBubblesApp/bluebubbles-app#1244]
Found by @chrundl in discord (alpha builds)

**Comment by zlshames** [comment]
Here are some sample message dates from @Chrundl

```
649449342470999936
649449314921067776
649449305825000064
649449279288297856
649449126551000064
649449115938000000
649449097989558912
649448072496000000
649448059447810688
649448048757461248
649447969193999744
```

**Comment by zlshames** [comment]
Marking this to be done for v1.3.0, however, we will. need to work with Chrundl to get the required logs to debug the actual issue. May take longer than the release date

**Comment by zlshames** [comment]
I believe this was due to High Sierra issues. Closing
