### ISSUE TITLE
make notification sound selection a dropdown

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1473]
So this doesn't happen

![image](https://media.discordapp.net/attachments/704168196802084984/883398010585899078/SmartSelect_20210903-120804.jpg)

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@jojejo` in `#android-development`.

**Comment by zlshames** [comment]
This has been removed. Closing
