### ISSUE TITLE
Look into fixing Java crash errors

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1485]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-development`.

**Comment by zlshames** [comment]
So what was the verdict here? @tneotia

**Comment by tneotia** [comment]
Hopefully fixed with my changes but I don't know for sure

**Comment by tneotia** [comment]
@zlshames 1.5.0 has been out for a bit, are we still getting crashes?

**Comment by zlshames** [comment]
i think we're good
