### ISSUE TITLE
[Feature Request] Automatically copy the server address when tapping it

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1498]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-requests`.

**Comment by CSab6482** [comment]
https://user-images.githubusercontent.com/53708281/132580821-f8cfbdaa-c9ec-4a6a-80e1-d91e04a10320.mp4

**Comment by tneotia** [comment]
How would we handle this bc tapping updates the values?

**Comment by CSab6482** [comment]
Could refresh be changed to a swipe like it is in the photo selector? Or maybe a long press for copy?

**Comment by tneotia** [comment]
Long press would start the text selection so that won't work, and swipe refresh doesn't seem too intuitive
