### ISSUE TITLE
{Request} option to extract QR code from screenshot during setup (like desktop)

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1510]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@monicow` in `#baffoonery`.

**Comment by tneotia** [comment]
Sorta kinda accomplished - you can now go in settings and generate a QR code which you can proceed to screenshot. I think that should satisfy the requirements here.

**Comment by romhacks** [comment]
I think the idea here is to have an option during the initial app setup to import a screenshot and scan it for the server QR - was that accomplished in the PR?

**Comment by tneotia** [comment]
> I think the idea here is to have an option during the initial app setup to import a screenshot and scan it for the server QR - was that accomplished in the PR?

Oh I misunderstood then... well regardless its a dupe of #1548
