### ISSUE TITLE
make favicon for bb web

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1515]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#community-contributions`.

**Comment by CSab6482** [comment]
I know you guys obviously have access to all of these, but I extracted these icons from the desktop app using [Resource Hacker](http://angusj.com/resourcehacker/).
![IconGroup103-1](https://user-images.githubusercontent.com/53708281/132689333-c3ae722c-12d0-48d0-a051-a340abe3f49e.png)
![IconGroup103-2](https://user-images.githubusercontent.com/53708281/132689338-8cf91837-6a80-4d19-b508-11c93e5e1e54.png)
![IconGroup103-3](https://user-images.githubusercontent.com/53708281/132689340-fd413a71-26fa-4cf7-ad36-60621c95045e.png)
![IconGroup103-4](https://user-images.githubusercontent.com/53708281/132689342-b63352d2-e386-46b0-a0b4-e1de9f83a526.png)
![IconGroup103-5](https://user-images.githubusercontent.com/53708281/132689343-2d8f67f9-9428-4868-a9df-363a79e932cf.png)
![IconGroup103-6](https://user-images.githubusercontent.com/53708281/132689344-3c04d5b5-71b7-4b9e-8204-8d61cb582b4f.png)
![IconGroup103-7](https://user-images.githubusercontent.com/53708281/132689345-aabddb71-1841-4d07-86a5-bb194f6a61d1.png)
![IconGroup103-8](https://user-images.githubusercontent.com/53708281/132689347-62cf0ac1-b869-42fd-8ffd-5cd31125c48c.png)
