### ISSUE TITLE
Add `You:` text to last message preview if isFromMe (toggle; default: off)

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1519]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#feedback`.

**Comment by zlshames** [comment]
Apple does not do this in their iMessage apps, so I’m saying this should be a toggle

**Comment by tneotia** [comment]
done for material mode
