### ISSUE TITLE
v1.5 - if you type some text in a message and then attach a gif from Gboard (maybe other kbs also?) the text and gif automatically send.  BB should wait for you to press send.

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1524]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#feedback`.

**Comment by zlshames** [comment]
Closed by https://github.com/BlueBubblesApp/bluebubbles-app/issues/1577
