### ISSUE TITLE
Add note to pre-sync screen telling the user to set message count to 1 if they are having sync issues

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1526]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-support`.

**Comment by CSab6482** [comment]
Not entirely related but #1508

**Comment by zlshames** [comment]
I don’t think we should set it to 1 by default. However, I do think we should add a note about sync issues, and setting it to 1 if you have those issues. Renaming the ticket
