### ISSUE TITLE
[Flutter Desktop] Remove unneeded settings entries

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1529]
The following entries don't apply to PC and can be removed:
-Auto Open Keyboard
-Swipe Message Box to Close Keyboard
-Swipe Message Box to Open Keyboard
-Hide Keyboard when Scrolling
-Open Keyboard after tapping Scroll to Bottom

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@scarlett` in `#desktop-requests`.

**Comment by tneotia** [comment]
Done
