### ISSUE TITLE
[Desktop / Web] restart required to see tapbacks

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1530]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#desktop-support`.

**Comment by tneotia** [comment]
Done for Web

**Comment by zlshames** [comment]
Is this also done for Desktop?

**Comment by tneotia** [comment]
Yep just tested and it works, I dont think this was an issue on desktop in the first place but idk

**Comment by jjoelj** [comment]
> Yep just tested and it works, I dont think this was an issue on desktop in the first place but idk

Yeah I was never able to reproduce on desktop
