### ISSUE TITLE
[Feature Request] Better spacing and ordering of reactions

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1535]
Potentially related to #753 and [this desktop ticket](https://github.com/BlueBubblesApp/BlueBubbles-Desktop-App/issues/208). Below are some photos from Isaac. 
![Image](https://cdn.discordapp.com/attachments/746560677333827584/886461596908552222/SmartSelect_20210911-210132.jpg) ![Image](https://cdn.discordapp.com/attachments/746560677333827584/886461278632157214/SmartSelect_20210911-210014.jpg)

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-requests`.

**Comment by tneotia** [comment]
Completed in full rewrite
