### ISSUE TITLE
Sometimes I get stuck in a mode where I cannot use backspace and all of my letters are in all caps

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1536]
I honestly think this is a Flutter bug and not a BB bug, but I know it isn't my keyboard or shift key being faulty, because I can alt+Tab to other apps where the typing works fine, but it is still broken in BB. I will turn on logging next time it happens and upload that here

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#webapp-support`.

**Comment by zlshames** [comment]
I think this is fixed. If not from a flutter update, from the rewrite and fixing of isolate processing
