### ISSUE TITLE
after switching iOS/material modes, the settings page background has swapped colours until it is closed and reopened

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1538]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@scarlett` in `#android-requests`.

**Comment by zlshames** [comment]
Not sure if this is android-specific or cross-platform specific. Need more info

**Comment by tneotia** [comment]
Fixed
