### ISSUE TITLE
[Desktop] Ctrl + Backspace Creates Null Character

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1544]
Correct functionality: When the Ctrl + Backspace is pressed the previous word is deleted - 
Actual functionality: When the combo is pressed, a null character is printed to the message box and if another key is pressed that renders a new character, the message box correctly updates and the word is deleted. If any other action is taken after pressing Ctrl + Backspace, the null character remains and acts like a normal character.

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Randymations` in `#desktop-support`.

**Comment by zlshames** [comment]
If this is too hard to do, we can move this to 1.7.0

**Comment by jjoelj** [comment]
done
