### ISSUE TITLE
[Desktop] Add QR code clipboard and file options on the initial setup screen

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1548]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Randymations` in `#desktop-support`.

**Comment by SoPat712** [comment]
what does this mean?

**Comment by SoPat712** [comment]
oh

**Comment by tneotia** [comment]
People should be able to "scan" QR code from clipboard or file. This is why I was looking for a new package cuz the current one doesn't support.

**Comment by tneotia** [comment]
gonna say this is no longer really needed once google sign in makes its way to desktop
