### ISSUE TITLE
Desktop Release Tickets

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1560]
- [x] opening image fullscreen viewer throws null exception (check discord for logs)
- [x] images don't download correctly because of null exception (check discord for logs)
- [x] can't make a custom theme and switch to it, it just wont switch in the dropdown for some reason... no logs for this
- [x] Cropping a custom avatar bugs the image, if we can't crop then just directly save the image on desktop
- [x] Set a custom color for avatar, go into settings menu to reset it, and hit reset - the dialog doesn't pop, rather the underlying page does, try `Get.back()` or `CustomNavigator.of(context).backSettingsCloseOverlays()` to fix the issue at line 176 of contact_avatar_widget.dart
- [x] Cancel button for the same dialog doesn't work
- [x] Notifications don't work until you turn on notify on chat list - make this default and remove the option
- [x] See if there's a way to improve slider responsiveness, it feels very laggy
- [x] ~~Allow the scroll speed multiplier to increase past 1 on desktop, set the default super high to improve scroll speeds~~ Not doing
- [x] Fetch and share server logs should actually save to device and not try to share directly
- [x] Send location doesn't work, make the share sheet button directly open files
- [x] Fix weirdness with long mimeType on regular file opener and attachment sender widget
![image](https://cdn.discordapp.com/attachments/725057294626455582/888974891842428938/unknown.png)
![image](https://cdn.discordapp.com/attachments/725057294626455582/888974954362707978/unknown.png)
- [x] Download files from regular file opener rather than saying unsupported handler, maybe show an open button on the right side of the toast if possible
- [x] Hide share button for attachments both in fullscreen viewer (image and video) & details popup (may need to do it on web)
- [x] ~~Reaction details card doesn't animate itself in popup (could be a Flutter bug)~~ Not doing
- [x] ~~Ignore settings parameters that don't apply to web or desktop when restoring settings~~ 
- [x] Notification for group chats shows `<group chat name>: contactName`
- [x] Lag when receiving a new message while the chat is open
- [x] Delete button doesn't work for custom theme
- [x] Theme menu doesn't open again after creating a custom theme
- [x] App is still recognized by `A New Flutter Project.` in certain windows dialogs, e.g. when the app isn't responding
- [x] Setup screen says "before using the Android app" - change to web and desktop conditionally
- [x] Clicking the number of unread messages to exit the message view does not remove highlight from the chat list tile (same bug for material mode but even clicking the arrow itself does not remove the highlight)
- [x] Make the fullscreen file viewer transition between stuff on left and right arrow key
- [x] Clicking about to see the dialog in settings doesn't work and shows white screen
- [x] Add currently selected item highlight to settings page
- [x] Remove the swipe action setting for the chat list on desktop / web
- [x] Change swipe direction setting in media settings to arrow key setting (once left / right arrow key to transition between fullscreen media is added)
- [x] Contacts sync is broken if using Mac contacts
- [x] File drop zone stays blue if file is dragged in but not dropped
- [x] Remove limit on Private API when server is running Big Sur

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#desktop-development`.

**Comment by zlshames** [comment]
@jjoelj so how many of these do you want to get done for the 1.6 release? All of them? Just trying to see what's left that you want to get done for it. Up to you.
