### ISSUE TITLE
System Tray notification icon

### ISSUE THREAD

**Issue by Johayan** [BlueBubblesApp/bluebubbles-app#1600]
I would like a system tray notifier for the Linux version of the desktop app. There is a (mostly) universal library (system notification indicator) that that could be use to create a system tray icon across the major Linux desktop environments.

Also, please link the bluebubbles icon in your bundle to that it can be linked into shortcuts/application links in menus, docks, task bars, etc.

Thank you!

**Comment by Johayan** [comment]
Whooops!  Wrong repo. Close me.

**Comment by Johayan** [comment]
Created in wrong repo.

**Comment by Johayan** [comment]
Oh for the...closed the wrong request.

**Comment by lijy91** [comment]
I think you can use [`tray_manager`](https://github.com/leanflutter/tray_manager) to add a system tray for BlueBubblesApp. 

Example:
```dart
import 'package:tray_manager/tray_manager.dart';

await TrayManager.instance.setIcon(
  Platform.isWindows
    ? 'images/tray_icon.ico'
    : 'images/tray_icon.png',
);
List<MenuItem> menuItems = [
  MenuItem(title: 'Show Window'),
  MenuItem.separator,
  MenuItem(title: 'Exit App'),
];
await TrayManager.instance.setContextMenu(menuItems);
```

**Comment by jjoelj** [comment]
done
