### ISSUE TITLE
Lag fixes for 1.7.0

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1605]
- [x] Right after initial app load and scrolling in the chat list (not incremental sync, actually the app is not even connected to the server) 
- [x] When opening a chatview
- [x] When closing a chatview
- [ ] When the keyboard in the chat view animates open and closed - still happens :((
- [ ] When scrolling in the chatview - sorta kinda fixed
- [x] Right after new messages in the chat view are loaded (actually only rarely nvm) 
- [x] New chat creator (holy shit this takes like 250 ms)
- [x] Inconsistently when opening chat details panel delay/lag
- [x] Opening and then closing then reopening chats repeatedly very visibly makes them take longer to load (I assume objectbox fixed this but just confirm and stress test)
- [x] Scrolling in the attachment view in the text box (I'll take blame for this one, I would recommend a rewrite because this was an issue since the beginning, I'm not sure what the correct way to show this kind of a view is, balancing memory usage/cpu time with compressing the images/disk load times. Perhaps use a background thread to do all this just so the main render thread isn't work to hard?)
From brick

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#android-requests`.

**Comment by zlshames** [comment]
I will split the last 2 into their own tickets

**Comment by zlshames** [comment]
#1667

**Comment by zlshames** [comment]
#1668
