### ISSUE TITLE
Some contacts not syncing to linux build 1.0.0.7 (alpha)

### ISSUE THREAD

**Issue by Johayan** [BlueBubblesApp/bluebubbles-app#1621]
Contact syncing is hit or miss with some contacts syncing and others not.

It is a mix of SMS contacts and iMessage contacts.

And examples are as follows:

SMS Contact: 
{"phoneNumbers":[{"isPrimary":true,"address":"+1337xxxxxxx","areaCode":null,"lastFourDigits":"1514","countryCode":null,"label":"","extension":null}],"emails":[{"isPrimary":true,"address":"gmailuser@gmail.com","label":""}],"firstName":"First","lastName":"Last"}

iMessage Contact:
"phoneNumbers":[{"isPrimary":true,"address":"(612) xxx-xxxx","areaCode":null,"lastFourDigits":"xxxx","countryCode":null,"label":"_$!<Home>!$_","extension":null}],"emails":[],"firstName":"xxxx","lastName":"xxxx"}

**Comment by zlshames** [comment]
Can confirm, some of my contacts were not transfered over... or maybe they just werent matched correctly

**Comment by Johayan** [comment]
Updating contacts in iCloud to have a +1xxx format causes the contact to sync.

**Comment by jjoelj** [comment]
fixed in 1.0.0.8
