### ISSUE TITLE
Sent / delivered / read indicator on chat list does not update correctly

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1627]
we may need to make the var in the message an Rx or observe the changes somehow to make sure we update the chat tile

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#android-support`.

**Comment by zlshames** [comment]
@tneotia did you fix this?

**Comment by tneotia** [comment]
Not yet

**Comment by zlshames** [comment]
So you fixed this now?

**Comment by tneotia** [comment]
yeah it should be good now, sent -> delivered is working fine for me. Bit hard to test read status tho
