### ISSUE TITLE
[Feature Request] Add BlueBubbles to Linux app stores

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/bluebubbles-app#1630]
Part of why I chose to use Pop!_OS as my distro is because of the Pop!_Shop, an easy to use app store that has just about everything I need.
![Screenshot from 2021-10-19 17-18-06](https://user-images.githubusercontent.com/53708281/137992011-e056a1b8-abed-416a-8c31-fd2b3f5bd3dd.png)
![Screenshot from 2021-10-19 17-13-08](https://user-images.githubusercontent.com/53708281/137992017-6bb8df7c-dd1d-4ae6-b607-eb9f1b315479.png)
I'm not too sure of the technical details on what kinds of packages it uses and all, but I do know that the Pop!_Shop does source from [Flathub](https://flathub.org/home). Below is the link for the app submission process to Flathub.
https://github.com/flathub/flathub/wiki/App-Submission
Below is a screenshot example of installing Discord through the Pop!_Shop.
![Screenshot from Screencast from 10-19-2021 05:14:37 PM webm](https://user-images.githubusercontent.com/53708281/137992227-a2308760-02fe-4b26-b681-40ec067b1b16.png)
One valid complaint I saw about making BlueBubbles available on Linux app stores is that there are just too many app stores. For example, Canonical has their own called [Snapcraft](https://snapcraft.io/). I'm not sure which shops are the best or the most universal or any of that, but I do know the Pop!_Shop has the ability to add other sources, and I assume most other Linux app stores would offer that too. Let me know what you think.

**Comment by timsayshey** [comment]
This would be amazing to have. Right now I'm launching from the `bluebubbles_app` file, I haven't figured out how to add it to my application launcher or pin it to my dock. 
![image](https://user-images.githubusercontent.com/1148940/160908759-391df419-26ea-4cfe-ba6e-8cd7edf31b1e.png)

**Comment by dtantono** [comment]
wish to get this app on Snap/Flatpak/Appimage/.deb version

**Comment by Ginjutsu** [comment]
Seconded. Having a simple way to install BB on my Steam Deck would be super sweet.

**Comment by tneotia** [comment]
Steam deck user 👀👀

We're really targeting all frontiers... It even starts up on the 3DS lol

**Comment by MTPeyton** [comment]
Just talked with @jjoelj on Discord. Sounds like they got the app running as a Flatpak, and will update this issue once it's pushed to Flathub. Their WIP is at https://github.com/BlueBubblesApp/bluebubbles-app/tree/joel/bordeaux/desktop/flatpak-support

**Comment by jjoelj** [comment]
Submitted to flathub here: https://github.com/flathub/flathub/pull/3283

**Comment by jjoelj** [comment]
https://flathub.org/apps/details/app.bluebubbles.BlueBubbles

**Comment by CSab6482** [comment]
[We won](https://everythingmarvel.net/wp-content/uploads/2020/05/we-won-mr-stark.jpg)
