### ISSUE TITLE
Make press and hold do the quick react if you have double tap for details active

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1632]
press

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#feedback`.

**Comment by CSab6482** [comment]
Wait but what was this

**Comment by CSab6482** [comment]
Make press and hold do the quick react if you have double tap for details active

**Comment by CSab6482** [comment]
If someone wants to have both press and hold and double tap to show details, would that still be possible?
