### ISSUE TITLE
Reactions from me parsed incorrectly sometimes 1.7.0 alpha

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1638]
from shadow07, on big sur, shows the wrong display name in the reaction details menu popup

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#feedback`.

**Comment by zlshames** [comment]
Confirming you fixed this @tneotia

**Comment by tneotia** [comment]
Yes it is done
