### ISSUE TITLE
[Feature Request] Fix URL Previews on Big Sur

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1645]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-requests`.

**Comment by zlshames** [comment]
@CSab6482 what about them is broken? Need some details. Are all previews broken?

**Comment by CSab6482** [comment]
> @CSab6482 what about them is broken? Need some details. Are all previews broken?

It's the same behavior as https://github.com/open-imcore/imcore.react/issues/25#issue-856484440

**Comment by tneotia** [comment]
We can't fix this Android side, this is a server ticket.
