### ISSUE TITLE
Cannot view images in chats past the most recent 25

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1650]
When clicking to open fullscreen, it jumps to the very first image and when swiping back it hard-stops at the 25th one

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#general`.

**Comment by CSab6482** [comment]
#783

**Comment by tneotia** [comment]
I think this is more severe because it happens even if there aren't a bunch of messages sent in quick succession

**Comment by CSab6482** [comment]
Yes, my bad. I meant https://github.com/BlueBubblesApp/bluebubbles-app/issues/783#issuecomment-786145990
