### ISSUE TITLE
Sending a photo causes all messages in macOS monterey to get stuck

### ISSUE THREAD

**Issue by duckyy1992** [BlueBubblesApp/bluebubbles-app#1653]
message flow will be working fine until a photo is sent

this photo will have a blue sending progress line in MacOS Monterey which never finishes sending.

no other messages will send until MacOS is restarted

**Comment by tneotia** [comment]
Yes this is a known issue (and currently unsolvable) with macOS Monterey. If possible please downgrade back to big sur or wait for a fix through the private API bundle (when we can figure out how to send attachments).

**Comment by duckyy1992** [comment]
amazingly quick response! thanks for the info

**Comment by tneotia** [comment]
Haha yeah, we have a bot in our discord server to let us know of new activity in the GitHub. Makes it easy to keep track of!
