### ISSUE TITLE
Every sent message gets error 1001 before sending correctly

### ISSUE THREAD

**Issue by rschoen** [BlueBubblesApp/bluebubbles-app#1654]
I can currently repro this 100% of the time. Steps:

1. Send any message from Android app
2. Message appears with a red exclamation point
3. Perhaps ~1 second later, the message duplicates itself without the red exclamation point (sent successfully)

Clicking on the message reveals "Message failed to send. Error (1001): Message is already queued to be sent!"

Configuration:

Client: Pixel 6 Pro running Android 12, app version 1.7.0
Server: 12-inch MacBook Air (early 2015), Big Sur 11.1

Attaching screenshots of the issue, and what I think is the relevant part of main.log.
[main.log](https://github.com/BlueBubblesApp/bluebubbles-app/files/7450927/main.log)
![Screenshot_20211031-222227_2](https://user-images.githubusercontent.com/3644011/139626513-e2fa4251-de1d-4274-a415-d0474635fa39.png)
![Screenshot_20211031-222246_2](https://user-images.githubusercontent.com/3644011/139626514-d23a42e5-6f47-4c5c-9601-571c67d61d39.png)

**Comment by jjoelj** [comment]
Hey, this is a known issue that we don't 100% know the cause of yet. The current fix is to restart the server on the Mac, and restart the Mac if the first step doesn't work. Also, make sure you have configured an ngrok Auth Token in server settings.

**Comment by rschoen** [comment]
Thanks for the fast reply! I just restarted the Mac and also tried switching to ngrok with auth token (was using dynamic DNS) and still have the same issue. Interestingly for the first few messages after reboot it was fine, before going back to the unwanted behavior.

Happy to help debug on my end if there's anything I can do, just let me know.

**Comment by jjoelj** [comment]
Would you be able to join our discord server so we can help you out a bit better (and work with you for logs)?

**Comment by tneotia** [comment]
(alpha server fixed this)
