### ISSUE TITLE
Replies are broked if you reply to your own message that is far up in the thread

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1658]
Replying to other people's old messages seems to work okay, but replying to your own old message creates some kind of void reply chain

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-support`.

**Comment by tneotia** [comment]
This is more appropriate to be a helper issue rather than a client issue
