### ISSUE TITLE
[Bug] Grouped notifications sometimes open a chat when tapped instead of simply opening the app

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1662]
It could either be that the chat at the top of the list is opened, or the name of the chat that is tapped on

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-requests`.

**Comment by CSab6482** [comment]
![image](https://user-images.githubusercontent.com/53708281/140130980-128db508-f402-41e4-949c-1766dcb36574.png)
