### ISSUE TITLE
Improve message detection for messages sent from other devices

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1670]
When I send a message from my iPhone or iPad, I often have to quit and re-enter BlueBubbles for it to show up there. Here are some related tickets. https://github.com/iandwelker/smserver/issues/76 https://github.com/sgtaziz/WebMessage/issues/42 https://github.com/sgtaziz/WebMessage/issues/92

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-requests`.

**Comment by tneotia** [comment]
@csab6482 is this still an issue with stable server and android?

**Comment by CSab6482** [comment]
https://user-images.githubusercontent.com/53708281/141695001-10f4920b-0bc0-4515-8888-957e4e59444e.mp4

Yes

**Comment by tneotia** [comment]
Fixed with 0.4.0 supposedly
