### ISSUE TITLE
[Object Box] Sent Messages that are not delivered disappear from the chat after leaving and re-entering

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1718]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by zlshames** [comment]
This is fixed by removing the send queue. Or... Modifying it so that the messages are added to the DB, then queued up. So that it goes into the DB immediately
