### ISSUE TITLE
Make reaction menu 2x3 on narrow screens

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1724]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@jojejo` in `#android-requests`.

**Comment by zlshames** [comment]
@tneotia is this something you changed yet?

**Comment by tneotia** [comment]
not yet, I think @jjoelj wanted to do this but I can look at it as well
