### ISSUE TITLE
after manual reset, the message sync config step is skipped and breaks the final sync step

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1731]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by zlshames** [comment]
This is possibly due to `goToNextPage` being called twice. Once when the socket connects, and once within the QR Code scanner. However, the issue happens upon manual entry as well
