### ISSUE TITLE
[Web] Left chat preview page only shows previews for sent texts, not received

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1733]
Below is an example ![Example](https://cdn.discordapp.com/attachments/885719150666874920/911347508343607436/Example.png)

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#webapp-support`.

**Comment by tneotia** [comment]
fairly certain these are fixed now
