### ISSUE TITLE
[1.8.0] create one time notice popup, alerting users that they need to upgrade their server by January 1st or risk losing functionality

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1734]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#general`.

**Comment by zlshames** [comment]
This date is negotiable. Just an example. We want to give ample time. But also, we want to migrate to the rest API so we can support certain features and better stability
