### ISSUE TITLE
opening an image displays the wrong image

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1738]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by CSab6482** [comment]
https://github.com/BlueBubblesApp/bluebubbles-app/issues/783#issuecomment-786145990

**Comment by tneotia** [comment]
closing for now. should be fixed
