### ISSUE TITLE
group chats occasionally duplicate

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1740]
group chats occasionally show 2 different chats in the conversation list, with new notifications only going to one of the conversations, and the other one receiving new messages only after an incremental sync

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@icanflyit` in `#support`.

**Comment by tneotia** [comment]
cant reproduce this anymore, so we are calling this fixed
