### ISSUE TITLE
[Object Box] homescreen shortcuts don't show contact pictures

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1747]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@icanflyit` in `#support`.

**Comment by elliotnash** [comment]
![Screenshot_20211122-164413](https://user-images.githubusercontent.com/53949099/142955958-b27fb406-c714-4a7d-9a31-92cb56389551.jpg)
