### ISSUE TITLE
[ObjectBox] sent messages sometimes appear in wrong order

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1748]
sometime when sending a message, the message will appear above the recent messages sent from the recipient, so the outgoing messages are in order relative to each other, but the entire group is above the group of recent messages from the recipient)

When backing out and reopening the chat, everything fixes itself so it seems to store in the database correctly

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@icanflyit` in `#support`.

**Comment by CSab6482** [comment]
Could #635 be related?

**Comment by tneotia** [comment]
cannot reproduce this, considering this fixed
