### ISSUE TITLE
[Object Box] Image loading issues (see image)

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#1755]

**Comment by zlshames** [comment]
![Screenshot_20211125-123356](https://user-images.githubusercontent.com/18445938/143485213-d1f5601c-5c73-4581-b5e7-5b4b50c6d8cd.png)

**Comment by zlshames** [comment]
@tneotia did you do anything to mitigate this?

**Comment by tneotia** [comment]
I didn't target this specifically, but to be honest there's been loads of changes since then that might have affected it. Especially if those images are heic.

**Comment by tneotia** [comment]
Gonna call this fixed for now I guess, haven't had any reports from anybody on internal alphas
