### ISSUE TITLE
When getting download from REST API, make sure response is actually 200 before saving, otherwise throw error

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1762]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#feedback`.

**Comment by Rihcus** [comment]
![image](https://user-images.githubusercontent.com/30292597/144268148-00684121-9b0f-4db7-b636-ae6819b4564b.png)

![image](https://user-images.githubusercontent.com/30292597/144268246-34bbe56e-fc8e-43cf-a0a6-db10d46ae6a1.png)


Example of large pdf file 93 mb via the web app. Renaming the corrupt 133 byte pdf to txt shows error in second image.

Android app indefinitly loads until remoted into mac and attachment is manually downloaded
![image](https://user-images.githubusercontent.com/30292597/144268497-b4563a47-efbe-4306-969e-26d5c5557286.png)
