### ISSUE TITLE
Fix issue where message view won't update for new messages (still receive notifications for the chat)

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#1767]
It's clearly an issue with the app having the wrong current chat value set. It may also be interfering with the bubbles code or the "timer" you have for the recent intent guid or whatever. 

Might be something I have to look at in terms of overall app flow

**Comment by tneotia** [comment]
Gonna call this fixed for now I guess, haven't had any reports from anybody on internal alphas. Likely fixed by removing bubbles support

**Comment by curiouscrusher** [comment]
This has been happening to me all week after I removed my server connection and re-added it. If I can help troubleshoot in any way please let me know.

**Comment by zlshames** [comment]
> This has been happening to me all week after I removed my server connection and re-added it. If I can help troubleshoot in any way please let me know.

What do you mean removed your server connection? Are you on an alpha build or stable?

**Comment by tneotia** [comment]
@curiouscrusher if you are on the stable 1.7.1 build, this should not be happening at all. If you are on 1.8.0 alpha (from GitHub or Discord), this is a known issue and we are working on resolving it.
