### ISSUE TITLE
Fix issue where image disappears after sending. Comes back after leave and re enter

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#1768]
Not sure if this will work for you, but here is what I did:

1. Send an image with text
2. Before the image fully sends, leave the app
3. Wait a sec
4. Re enter the app
5. Image seems to disappear or flicker
6. Send a message and it comes back

**Comment by tneotia** [comment]
Gonna call this fixed for now I guess, haven't had any reports from anybody on internal alphas
