### ISSUE TITLE
[Android] Some videos don't play/load infinitely

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/bluebubbles-app#1777]
Below is an example. This video will not play on Android, but it does play on web

https://user-images.githubusercontent.com/53708281/145632861-c4a4aafb-0a22-408e-991e-ed927a17c61f.mp4

**Comment by tneotia** [comment]
Flutter issue because the video name has a `#` inside it. Videos with `?` will also not play.

**Comment by zlshames** [comment]
Closing this.
