### ISSUE TITLE
hide compose floating action button when a message is being swiped on

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1807]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-support`.

**Comment by tneotia** [comment]
This is gonna be super tricky because the library we use for the sliding actions doesn't support any sort of listeners for the slide status.

**Comment by zlshames** [comment]
Swipe has been removed in rewrite. Closing
