### ISSUE TITLE
Add Basic Auth capabilities

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#1808]
- Make the toggle for basic auth show on the setup screen & add required user/pass text fields
- Add the toggle for basic auth to the server settings, along with required user/pass text fields (when enabled)
- API detection to "figure out" if basic auth is enabled, but not enabled on the client side. Show an error or warning if that's the case.

This is tied to this issue: https://github.com/BlueBubblesApp/bluebubbles-server/pull/279

**Comment by tneotia** [comment]
This is now technically possible in a more global manner with the addition of custom headers

Users set
key: `authorization`
value: `Basic $username:$password`
