### ISSUE TITLE
[1.8.0] queuing multiple attachments only shows currently uploading attachment

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1811]
When sending multiple attachments in separate messages quickly after each other, only the first queuing message is shown untill it finishes uploading, and then it shows the next image uploading

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@icanflyit` in `#android-support`.

**Comment by tneotia** [comment]
Fixed
