### ISSUE TITLE
Fix URL Previews for Twitter

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1820]
Broken link: https://twitter.com/ryanshawtech/status/1474213262442958852?s=10, make the preview image take precedence over Apple thumbnail

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#android-support`.

**Comment by tneotia** [comment]
No longer applicable, twitter no longer supplies an image in metadata
