### ISSUE TITLE
notification when message fails to send

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1831]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#android-requests`.

**Comment by zlshames** [comment]
Should be pretty easy. Only show the notification is the app is active and the currently active chat is not the one that had the send failure

**Comment by tneotia** [comment]
We have this in place already, it was just broken on Android 12
