### ISSUE TITLE
[Samsung Phones] Tapping contact in chat details does not open the contact card

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1844]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#server-support`.

**Comment by arooni** [comment]
I'm just a little unclear on whether I need to add the contact FIRST from android or via a Mac to iCloud?  

Is sync one way or two?  

Do I have to create duplicate contacts on each cloud provider or just one and it'll propagate?  

Thanks!
