### ISSUE TITLE
When sending attachments, sometimes it doesn't send and the attachment preview pane will expand/de-expand a few times

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#1846]
This is a bug that we've been getting on the Samsung s22+. 

1. Attach multiple photos to a message (happens more often when sending more than one)
2. Click send
3. Sometimes the photos won't send, but the attachment preview widget will expand up and down, a few times. 

I have no idea what would cause this

**Comment by tneotia** [comment]
gonna say this wont happen anymore
