### ISSUE TITLE
Change how we handle bulk sync notifications vs. real-time notifications

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1848]
An example would be waking PC up from sleep and receiving a TON of notifications. We should make it so if the bulk update finds > x new messages, we just dispatch a single notification for it (and we update the chat list once). Rather than sending x new message notifications and updating the chat x times, which is expensive and can cause lag

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#feedback`.

**Comment by tneotia** [comment]
Fixed
