### ISSUE TITLE
[Desktop] Make app use system titlebar on linux and add option to switch to custom

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1856]
might be good for windows too

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@jojejo` in `#desktop-support`.

**Comment by jjoelj** [comment]
Linux uses system titlebar by default now as of [a0bbf4b](https://github.com/BlueBubblesApp/bluebubbles-app/commit/a0bbf4b4e0640f7c73b415c09af98c589457f896) Keeping this open so we add a toggle in the future

**Comment by tneotia** [comment]
I think we did this, no?

**Comment by idoodler** [comment]
![image](https://user-images.githubusercontent.com/6825153/209851928-a0cf157d-ab3a-4453-b2d5-5d74ea4c2f5e.png)

Apparently this is still an issue

**Comment by jjoelj** [comment]
> ![image](https://user-images.githubusercontent.com/6825153/209851928-a0cf157d-ab3a-4453-b2d5-5d74ea4c2f5e.png)
> 
> Apparently this is still an issue

Yes. For now if you don't want both, the only option is to hide the custom titlebar in desktop settings

**Comment by tneotia** [comment]
done
