### ISSUE TITLE
App keeps crashing after sync.

### ISSUE THREAD

**Issue by woolmonkey** [BlueBubblesApp/bluebubbles-app#1858]
I have the latest android 12 version and blue bubbles keeps crashing after the inital sync with the server.

**Comment by tneotia** [comment]
Can you send us a screen recording of the issue? If it contains personal info, we suggest joining the discord (https://discord.gg/5YmE8HP8) and DMing either me (@Tanay) or Zach (@Zach the Dev).

**Comment by zlshames** [comment]
This is related to #1925
