### ISSUE TITLE
Custom avatars and colors get reset.

### ISSUE THREAD

**Issue by aliquis0001** [BlueBubblesApp/bluebubbles-app#1859]
On Android app version 1.8.0, with colorful avatars and bubbles turned on, I am able to change the colors for contacts, but eventually (typically after a few sent messages), the colors get reset back to the defaults. This also applies to custom avatars I set for group chats. The only ones that seem to stick are the colors for people that I rarely contact. This is an annoying issue because I like to differentiate my friends by color, and in a groupchat of 6 other people, there's only three default colors that get used.

**Comment by tneotia** [comment]
Should be fixed by https://github.com/BlueBubblesApp/bluebubbles-app/commit/7e6489d3126732b588d605847137aea0f3950693
