### ISSUE TITLE
Contact photos are zoomed in on notifications and Android share sheet

### ISSUE THREAD

**Issue by Zyonse** [BlueBubblesApp/bluebubbles-app#1865]
This is happening with all my chats, the issue is present on both 1.7.1 and 1.8.0

**Comment by zlshames** [comment]
We need to prioritize the HiRes avatar when updating the share target

**Comment by zlshames** [comment]
Fixed in branch `zach/amsterdam/1865/hires-share-target` and will be in 1.9.0

**Comment by Zyonse** [comment]
I'm on the 1.9.0 beta and the issue is still present

**Comment by zlshames** [comment]
> I'm on the 1.9.0 beta and the issue is still present

And I assume you've received new messages in those chats that have "zoomed in" avatars, right? Just wondering as im having a hard time replicating the zoomed images

**Comment by tneotia** [comment]
This may be a Samsung specific issue

**Comment by Zyonse** [comment]
> > I'm on the 1.9.0 beta and the issue is still present
> 
> And I assume you've received new messages in those chats that have "zoomed in" avatars, right? Just wondering as im having a hard time replicating the zoomed images

Yeah it's happening with new notifications. That was after a reinstall too.


> This may be a Samsung specific issue

I'm on a Pixel 6, Android 12.1

**Comment by Zyonse** [comment]
Can this issue be marked as open again? Also do you need me to provide logs or anything else?

**Comment by Zyonse** [comment]
I was able to replicate this issue on a Pixel 3a running LineageOS 19 (Android 12).

**Comment by zlshames** [comment]
I'm bumping this to the next release as I'm not totally sure how to solve this at this point, and 1.9.0 needs to go out whenever the server is ready.

**Comment by tneotia** [comment]
https://developer.android.com/training/sharing/receive#providing-shortcut-imagery

**Comment by tneotia** [comment]
Fixed, dev branch
