### ISSUE TITLE
Make background isolate more efficient at processing notifications

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1886]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@jojejo` in `#general`.

**Comment by mrsylerpowers** [comment]
With 1.8.0 candidate it takes a total of 8s to process and display notifications from an app that is completely closed on some clients. This is because of `await ContactManager().matchHandles();` and `getChatBatches` which can take a significant amount of time depending on how many contacts and chats a user has.

**Comment by zlshames** [comment]
@mrsylerpowers does this happen for each notification. Or only the first time the isolate spins up?

**Comment by mrsylerpowers** [comment]
Only for the first notification the isolate turns out. If the isolate is killed again by doze or anything then has to startup again @zlshames

**Comment by zlshames** [comment]
> Only for the first notification the isolate turns out. If the isolate is killed again by doze or anything then has to startup again @zlshames

Ok, I think what we can do is create a function to load the contacts for ONLY the participants of the chat. Then, load the rest of the contacts in the background afterwards

**Comment by mrsylerpowers** [comment]
Getting up to 24 seconds

**Comment by zlshames** [comment]
I've created this ticket to optimize/address this: https://github.com/BlueBubblesApp/bluebubbles-app/issues/1889

**Comment by tneotia** [comment]
Completed in full rewrite
