### ISSUE TITLE
Only load a chat notification's participants into the ContactManager upon a notification

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#1889]
Currently, our contact manager seems to fetch contacts seemingly a lot. We need to limit how often we call it, as well as adding functionality to it to more granularly fetch specific contacts. Use-cases:

* When opening the app from a fresh start, load all contacts associated with chats
* When opening the app from the background, do not refresh the contacts
    - Since we had already loaded them in on the fresh start, there is no reason to reload them
    - If a user creates a contact after the app has loaded contacts, we don't really need to handle that because there is no "event" we can handle as far as I'm aware, telling us a new contact was added, and to refresh the contacts.
    - The user will need to close and reopen the app to reload contacts. This should be fine, contacts are not added/updated that often
* When receiving a notification, _only_ load the contacts _required_ for the chat
    - This will speed up how fast notifications arrive, as well as reduce CPU usage
    - If this happens in the isolate, we aren't opening the app anyways, so loading all contacts won't matter
    - If this happens while the app is opened, the contacts should already be loaded in
* When opening a bubble-chat, only load the contacts for that chat. We can load the rest of the contacts in when the app is actually started

^ These should be the only times we are calling the contact manager, and it should only be called when required.

Currently, we call it in the following places:

* chat_bloc.dart: In order to get the contacts before fetching the chats
    - We could probably make the chat_bloc fetch the contacts with the chats, as needed, instead of waiting for all contacts to load in first
* setup_bloc.dart: In order to fetch contacts before performing the initial sync
    - We also fetch it when setup is finished (which we should remove because we just fetched them earlier)
    - We also fetch it when in a web environment after loading the chats. We need to skip over at least one of those fetches.
 * background_isolate.dart: In order to fetch contacts when the isolate starts up
     - I think this can straight up be removed. I removed it and the app/notifications seemed to work fine. However, I didn't test it too in-depth. This just needs to be removed in favor of fetching only the contacts for the given chat we are loading.
 * method_channel_interface.dart: To fetch all contacts when a chat is open. 
     - Once again, we need to limit fetching only the contacts for the specific chat. 
     - We can load the full list as the chat bloc loads in. But we should wait for the specific chat contact fetch to finish first

**Comment by zlshames** [comment]
This is partially fixed by the changes I made in v1.8.0. This can be further fixed by continuing the work i started on `zach/contact-optimizations`. Keeping this open until it's complete

**Comment by zlshames** [comment]
I think we've pretty much solved the contacts issue for the most part. The _only_ thing we haven't done yet is make it so only the participants of a notification's chat are loaded, when a notification comes in. I believe that when certain Samsung devices (and probably others) have Battery Optimization turned on, it kills background app usage every 10 seconds. On some older Samsung devices (S9/10), loading contacts can take fairly longer than on newer devices. On those devices, it has the potential to hit that 10 second limit and get killed. Thus, the notification doesn't get delivered.

By loading only the notification's chat participants contact info, we are able to hopefully speed up the fetch/cache time and not hit that 10 second threshold. That said, I think most of the "load time" comes from the `buildCache` function that caches the address to Contact object key/value pairs. Since we load multiple variations of the address into the cache to make finding by key more reliable. We should add a flag or just toggle an existing flag to only build the cache for a specific chat.

I am changing this ticket's title to reflect that

**Comment by zlshames** [comment]
Bumping to 1.10 as this isn't high priority for 1.9.0

**Comment by tneotia** [comment]
Completed in full rewrite
