### ISSUE TITLE
When trying to tap to edit message in text field, text cursor is replaced by highlighting animation

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1892]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Blank` in `#feedback`.

**Comment by b1ankusername** [comment]
Affected devices: Galaxy Note 20 Ultra 5G, Galaxy Tab S7+

**Comment by b1ankusername** [comment]
Doesn't affect actual functionality of editing message, just the animation.  Typing even when it appears that all text is highlighted doesn't replace "highlighted" text with new text, it inserts text as normal.  But even actually intentionally highlighting and trying to replace a chunk of text doesnt work so it might be usual behavior in that aspect.

**Comment by b1ankusername** [comment]
https://user-images.githubusercontent.com/100311639/155388287-ca36c1f2-3929-4a72-be47-5f83c35c9289.mp4

**Comment by b1ankusername** [comment]
on Galaxy Tab S7+ with keyboard case, issue isn't present, tapping will move cursor indicatior as normal.  Removing keyboard case and when on screen keyboard appears, issue comes back.

**Comment by zlshames** [comment]
I have a feeling this is Flutter issue. Maybe having to do with the keyboard compatibility. You're using Samsung keyboard, right? @b1ankusername

**Comment by b1ankusername** [comment]
yep samsung keyboard

**Comment by zlshames** [comment]
> yep samsung keyboard

Do you still have this issue in the latest release?

**Comment by zlshames** [comment]
Flutter 3.7 just came out. I'm wondering if this issue is still present. Either way, removing this ticket from the 1.11.0 milestone

**Comment by tneotia** [comment]
This was confirmed as fixed by @b1ankusername
