### ISSUE TITLE
Cannot view heic images in windows desktop app

### ISSUE THREAD

**Issue by jonyTF** [BlueBubblesApp/bluebubbles-app#1900]
When I receive an heic image, the image loads indefinitely and when I click on it, it says "failed to load image". It is only when I download the image and open it externally that I am finally able to view it.

Possibly related to something being wrong with the heic -> jpg conversion??

I'm using BlueBubbles version 1.7.1.6

**Comment by zlshames** [comment]
> When I receive an heic image, the image loads indefinitely and when I click on it, it says "failed to load image". It is only when I download the image and open it externally that I am finally able to view it.
> 
> Possibly related to something being wrong with the heic -> jpg conversion??
> 
> I'm using BlueBubbles version 1.7.1.6

Hi Jony, I believe that we fixed this partially in the latest server update that is unreleased as of right now. We basically auto convert HEIC images to JPEGs

**Comment by jonyTF** [comment]
Oh perfect, looking forward to the next server release!
