### ISSUE TITLE
Some mp4s do not download correctly

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1937]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by zlshames** [comment]
Not sure what the rhyme or reason is for this. Didn't happen on my OnePlus, but does happen on another user's OnePlus. It does happen on my Pixel, but doesn't happen on Joel's or Tanay's Samsung phones. Super confused. Not sure if this is a server bug or a client bug having to do with the conversion stuff.

**Comment by zlshames** [comment]
Fixed by server change
