### ISSUE TITLE
Entering in through a notification sometimes doesn't bring you to the correct chat

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#1944]
I had an instance where it would keep opening to the same chat, despite me clicking different notifications at 2 different times. It seemed "stuck" somehow. I think it happens more when opening from fully closed. Like the app is closed -> I get a notification on my lock screen -> I enter through my lockscreen -> boom, wrong chat.

**Comment by zlshames** [comment]
This still occurs. Sometimes it takes you to the wrong chat, sometimes the right one. Bumping this to 1.10 because we need to investigate this further and more in depth

**Comment by tneotia** [comment]
should be fixed with the rewrite
