### ISSUE TITLE
The founder's nitpicks

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1947]
Alright optimization is still my top nitpick: it's passable as in the stutters are no longer insane, but they're still there
Like scrolling through the chat list, there are still microstutters where it dips below 60
Opening the convo view, there are still micro stutters
Scrolling through messages, there are micro stutters
My recommended fix for that would be to rewrite the widgets, I took a look at the code and it's still a lot of the stuff I wrote a while ago, but I'm sure there is a far better way to design it (I do not like the way I wrote it)
Also, all of the visual indicators for clicking on things are essentially gone now, and it makes the app feel much less responsive
Also very low priority, take a look at the hold to pop-up message it looks misaligned

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#support`.

**Comment by tneotia** [comment]
taken care of
