### ISSUE TITLE
[Test to Confirm] Replying via a notification doesn't work

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1949]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-support`.

**Comment by zlshames** [comment]
I was able to reproduce this when not using private api sending, and replying from a notification on my lockscreen

**Comment by chuccck** [comment]
This happens to me 100% of the time I reply inside the notification

**Comment by NTGDeveloper** [comment]
+1 happens to me constantly, destroying my workflow

**Comment by CSab6482** [comment]
I can also confirm that I've had this happen many times. Ever since I got issue #683, I haven't really used this feature.
