### ISSUE TITLE
Name in text field does not match the active chat

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1950]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#desktop-requests`.

**Comment by zlshames** [comment]
Doesn’t happen everytime. Might happen when you're in a chat, and receive a notification from another chat. Might more have to do with tapping to go into the other chat, not sure.

**Comment by tneotia** [comment]
Completed in full rewrite
