### ISSUE TITLE
[Desktop] Settings menu gets grayed out midway down

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/bluebubbles-app#1969]
https://user-images.githubusercontent.com/53708281/162069941-cd110984-452b-4c5b-8cdd-b18c0ff99109.mp4

This can be fixed by just clicking the menu on the left once more. Joel guessed that it may be an obx problem.

**Comment by zlshames** [comment]
@jjoelj did you fix this by any chance?
