### ISSUE TITLE
[Desktop] Feature request for contact photos in notifications

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/bluebubbles-app#1970]
I'm just going to link to similar feature requests I've made
https://github.com/BlueBubblesApp/BlueBubbles-Desktop-App/issues/188
https://github.com/iandwelker/smserver/issues/119
https://github.com/sgtaziz/WebMessage/issues/110

**Comment by jjoelj** [comment]
![image](https://user-images.githubusercontent.com/35714943/162598002-7f4823ef-a2f9-45b7-ab7f-a5b429a04900.png)

Will be in next desktop release :)
