### ISSUE TITLE
[Desktop] Add spell check to windows client.

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1994]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#desktop-requests`.

**Comment by jawilson** [comment]
@tneotia what fixed this?

**Comment by jjoelj** [comment]
It's been added for the latest Desktop beta release. We can keep it open until there is a stable build.

**Comment by mkitchingh** [comment]
This is awesome. Can You confirm what beta version? I downloaded 1.13 beta the other day, and it says it's 1.12.100 in the about for the app on my desktop.

**Comment by jjoelj** [comment]
That's the right version. Desktop Beta version numbers work a little differently to make sure that updates work. In general, a version ending in .1XX is a Beta release.

You should see colored highlighting on misspelled words along with grammar, capitalization, and other issues. You can highlight a word and right click to view possible fixes. This is a preliminary implementation and the UX will likely be improved in future builds.

**Comment by mkitchingh** [comment]
I thought beta numbering worked something like that. I'll test it out when I get home.
