### ISSUE TITLE
Make sure we arent using CurrentChat when sending reactions

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1997]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-support`.

**Comment by zlshames** [comment]
We should pass the Chat itself to the send function. If we use the current chat, and the chat is changed quickly after sending a tapback, it can cause the tapback to be sent to the wrong chat
