### ISSUE TITLE
[1.9.0 Beta] Still receiving notifications for open chat

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2026]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#feedback`.

**Comment by zlshames** [comment]
Im not sure if this has happened to me. Moving to 1.9.0 to test briefly to see if it's easily reproducible

**Comment by zlshames** [comment]
Moving to v1.10.0

**Comment by tneotia** [comment]
Considering nobody has reported this in a while I'm gonna assume its fixed
