### ISSUE TITLE
Group icon change events shows as a group leaving event

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2029]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#feedback`.

**Comment by zlshames** [comment]
This _might_ be a server issue. Need to investigate more. Bumping to 1.10.0

**Comment by tneotia** [comment]
Fairly certain this is fixed now
