### ISSUE TITLE
Win 11 Client Installs But Won't Open

### ISSUE THREAD

**Issue by toastytortilla** [BlueBubblesApp/bluebubbles-app#2034]
Hey all,

First of all, I love the app and the service it provides. You all do stellar work. I'm having an issue where I can't get the desktop client to open on Windows 11 (build 22610.1). 

Backstory: Last year I was using BB and it was great. I was running it on an old MBP (Catalina, ty dosdude), BB 1.0.4 on Windows 10, and the Android app on my Galaxy S10e. I ended up switching to iPhone, but I still have my Windows machine as my primary PC. I let the app fall by the wayside as I was using iMessage on iPhone, but I want to get it running again on my desktop environment.

I uninstalled BB 1.0.4 and installed the newest stable build (1.8.0) from the .exe file on Github. It installed fine, then when I opened BB, nothing. Weird. So, I followed your instructions to install from the MS Store. Installed fine, then same issue... Here's the most recent crash log I could find:

> Version=1
> EventType=APPCRASH
> EventTime=132958564473555481
> ReportType=2
> Consent=1
> UploadTime=132958564480881915
> ReportStatus=268435456
> ReportIdentifier=1ba3d373-1da7-4548-a2c5-fd9a7be74e50
> IntegratorReportIdentifier=97e4f7b0-eec5-452b-9c00-596478c728b5
> Wow64Host=34404
> NsAppName=bluebubbles_app.exe
> OriginalFilename=bluebubbles_app.exe
> AppSessionGuid=00006cbc-0001-000c-30a5-0a251c5dd801
> TargetAppId=W:0006e5472477dca2c6990c7ec03340cc238900000904!0000565d575796b87847fe9566fc27b245bace28216a!bluebubbles_app.exe
> TargetAppVer=2022//04//02:03:13:09!0!bluebubbles_app.exe
> BootId=4294967295
> TargetAsId=12735
> IsFatal=1
> Response.BucketId=c7210b88f9f7c6db46676b509a038e11
> Response.BucketTable=4
> Response.LegacyBucketId=1614376985361092113
> Response.type=4
> Sig[0].Name=Application Name
> Sig[0].Value=bluebubbles_app.exe
> Sig[1].Name=Application Version
> Sig[1].Value=1.8.0.0
> Sig[2].Name=Application Timestamp
> Sig[2].Value=6247bf45
> Sig[3].Name=Fault Module Name
> Sig[3].Value=bluebubbles_app.exe
> Sig[4].Name=Fault Module Version
> Sig[4].Value=1.8.0.0
> Sig[5].Name=Fault Module Timestamp
> Sig[5].Value=6247bf45
> Sig[6].Name=Exception Code
> Sig[6].Value=c0000005
> Sig[7].Name=Exception Offset
> Sig[7].Value=0000000000005cf0
> DynamicSig[1].Name=OS Version
> DynamicSig[1].Value=10.0.22598.2.0.0.768.101
> DynamicSig[2].Name=Locale ID
> DynamicSig[2].Value=1033
> DynamicSig[22].Name=Additional Information 1
> DynamicSig[22].Value=5d58
> DynamicSig[23].Name=Additional Information 2
> DynamicSig[23].Value=5d585860aae572adb05e6a94a635bd22
> DynamicSig[24].Name=Additional Information 3
> DynamicSig[24].Value=8f40
> DynamicSig[25].Name=Additional Information 4
> DynamicSig[25].Value=8f408f4281334c701464577f7924a292
> UI[2]=C:\Program Files (x86)\BlueBubbles\bluebubbles_app.exe
> LoadedModule[0]=C:\Program Files (x86)\BlueBubbles\bluebubbles_app.exe
> LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
> LoadedModule[2]=C:\WINDOWS\System32\KERNEL32.DLL
> LoadedModule[3]=C:\WINDOWS\System32\KERNELBASE.dll
> LoadedModule[4]=C:\WINDOWS\System32\USER32.dll
> LoadedModule[5]=C:\WINDOWS\System32\win32u.dll
> LoadedModule[6]=C:\WINDOWS\System32\GDI32.dll
> LoadedModule[7]=C:\WINDOWS\System32\gdi32full.dll
> LoadedModule[8]=C:\Program Files (x86)\BlueBubbles\connectivity_plus_windows_plugin.dll
> LoadedModule[9]=C:\Program Files (x86)\BlueBubbles\desktop_drop_plugin.dll
> LoadedModule[10]=C:\Program Files (x86)\BlueBubbles\maps_launcher_plugin.dll
> LoadedModule[11]=C:\WINDOWS\System32\msvcp_win.dll
> LoadedModule[12]=C:\WINDOWS\System32\ucrtbase.dll
> LoadedModule[13]=C:\WINDOWS\System32\SHELL32.dll
> LoadedModule[14]=C:\WINDOWS\System32\ole32.dll
> LoadedModule[15]=C:\WINDOWS\System32\combase.dll
> LoadedModule[16]=C:\WINDOWS\System32\RPCRT4.dll
> LoadedModule[17]=C:\Program Files (x86)\BlueBubbles\objectbox_flutter_libs_plugin.dll
> LoadedModule[18]=C:\Program Files (x86)\BlueBubbles\printing_plugin.dll
> LoadedModule[19]=C:\Program Files (x86)\BlueBubbles\quick_notify_plugin.dll
> LoadedModule[20]=C:\WINDOWS\System32\COMDLG32.dll
> LoadedModule[21]=C:\WINDOWS\System32\OLEAUT32.dll
> LoadedModule[22]=C:\WINDOWS\System32\shcore.dll
> LoadedModule[23]=C:\Program Files (x86)\BlueBubbles\secure_application_plugin.dll
> LoadedModule[24]=C:\WINDOWS\System32\SHLWAPI.dll
> LoadedModule[25]=C:\WINDOWS\System32\msvcrt.dll
> LoadedModule[26]=C:\Program Files (x86)\BlueBubbles\system_tray_plugin.dll
> LoadedModule[27]=C:\Program Files (x86)\BlueBubbles\url_launcher_windows_plugin.dll
> LoadedModule[28]=C:\Program Files (x86)\BlueBubbles\window_manager_plugin.dll
> LoadedModule[29]=C:\WINDOWS\System32\ADVAPI32.dll
> LoadedModule[30]=C:\WINDOWS\System32\sechost.dll
> LoadedModule[31]=C:\Program Files (x86)\BlueBubbles\flutter_windows.dll
> LoadedModule[32]=C:\WINDOWS\SYSTEM32\dwmapi.dll
> LoadedModule[33]=C:\WINDOWS\System32\PSAPI.DLL
> LoadedModule[34]=C:\WINDOWS\System32\WS2_32.dll
> LoadedModule[35]=C:\WINDOWS\System32\IMM32.dll
> LoadedModule[36]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22598.1_none_266eafbb6bbb2fe0\COMCTL32.dll
> LoadedModule[37]=C:\WINDOWS\System32\CRYPT32.dll
> LoadedModule[38]=C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
> LoadedModule[39]=C:\WINDOWS\SYSTEM32\MSVCP140.dll
> LoadedModule[40]=C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll
> LoadedModule[41]=C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
> LoadedModule[42]=C:\Program Files (x86)\BlueBubbles\pdfium.dll
> LoadedModule[43]=C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
> LoadedModule[44]=C:\WINDOWS\SYSTEM32\OPENGL32.dll
> LoadedModule[45]=C:\WINDOWS\SYSTEM32\bcrypt.dll
> LoadedModule[46]=C:\WINDOWS\SYSTEM32\OLEACC.dll
> LoadedModule[47]=C:\WINDOWS\SYSTEM32\UIAutomationCore.DLL
> LoadedModule[48]=C:\WINDOWS\SYSTEM32\dxgi.dll
> LoadedModule[49]=C:\WINDOWS\SYSTEM32\d3d9.dll
> LoadedModule[50]=C:\WINDOWS\SYSTEM32\GLU32.dll
> LoadedModule[51]=C:\WINDOWS\SYSTEM32\dxcore.dll
> LoadedModule[52]=C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
> LoadedModule[53]=C:\WINDOWS\SYSTEM32\kernel.appcore.dll
> LoadedModule[54]=C:\WINDOWS\System32\bcryptPrimitives.dll
> LoadedModule[55]=C:\WINDOWS\system32\uxtheme.dll
> LoadedModule[56]=C:\WINDOWS\System32\MSCTF.dll
> State[0].Key=Transport.DoneStage1
> State[0].Value=1
> OsInfo[0].Key=vermaj
> OsInfo[0].Value=10
> OsInfo[1].Key=vermin
> OsInfo[1].Value=0
> OsInfo[2].Key=verbld
> OsInfo[2].Value=22598
> OsInfo[3].Key=ubr
> OsInfo[3].Value=200
> OsInfo[4].Key=versp
> OsInfo[4].Value=0
> OsInfo[5].Key=arch
> OsInfo[5].Value=9
> OsInfo[6].Key=lcid
> OsInfo[6].Value=1033
> OsInfo[7].Key=geoid
> OsInfo[7].Value=244
> OsInfo[8].Key=sku
> OsInfo[8].Value=101
> OsInfo[9].Key=domain
> OsInfo[9].Value=0
> OsInfo[10].Key=prodsuite
> OsInfo[10].Value=768
> OsInfo[11].Key=ntprodtype
> OsInfo[11].Value=1
> OsInfo[12].Key=platid
> OsInfo[12].Value=10
> OsInfo[13].Key=sr
> OsInfo[13].Value=0
> OsInfo[14].Key=tmsi
> OsInfo[14].Value=221594856
> OsInfo[15].Key=osinsty
> OsInfo[15].Value=1
> OsInfo[16].Key=iever
> OsInfo[16].Value=11.1.22598.0-11.0.1000
> OsInfo[17].Key=portos
> OsInfo[17].Value=0
> OsInfo[18].Key=ram
> OsInfo[18].Value=7983
> OsInfo[19].Key=svolsz
> OsInfo[19].Value=237
> OsInfo[20].Key=wimbt
> OsInfo[20].Value=0
> OsInfo[21].Key=blddt
> OsInfo[21].Value=220408
> OsInfo[22].Key=bldtm
> OsInfo[22].Value=1503
> OsInfo[23].Key=bldbrch
> OsInfo[23].Value=ni_release
> OsInfo[24].Key=bldchk
> OsInfo[24].Value=0
> OsInfo[25].Key=wpvermaj
> OsInfo[25].Value=0
> OsInfo[26].Key=wpvermin
> OsInfo[26].Value=0
> OsInfo[27].Key=wpbuildmaj
> OsInfo[27].Value=0
> OsInfo[28].Key=wpbuildmin
> OsInfo[28].Value=0
> OsInfo[29].Key=osver
> OsInfo[29].Value=10.0.22598.200.amd64fre.ni_release.220408-1503
> OsInfo[30].Key=buildflightid
> OsInfo[30].Value=B42A0393-CE53-4FD2-A8AD-56700E91E6A8.1
> OsInfo[31].Key=edition
> OsInfo[31].Value=Core
> OsInfo[32].Key=ring
> OsInfo[32].Value=External
> OsInfo[33].Key=expid
> OsInfo[33].Value=NG:16B13C,DR:A1B99,DR:A5A1C,DR:AA4AD,DR:ACBD4,DR:ACBD5,DR:ADDA6,DR:AED92,DR:B281A,DR:B66C5,DR:BB5C7,FX:114145DF,FX:11DE1DCB,FX:124117A5,FX:1257104F,FX:2554F26
> OsInfo[34].Key=fconid
> OsInfo[34].Value=21031911,0,2,1;25704915,1,2,1;35681102,0,1,0;36738728,0,1,0;38634282,0,1,0
> OsInfo[35].Key=containerid
> OsInfo[36].Key=containertype
> OsInfo[37].Key=edu
> OsInfo[37].Value=0
> OsInfo[38].Key=servicinginprogress
> OsInfo[38].Value=0
> OsInfo[39].Key=featureupdatependingreboot
> OsInfo[39].Value=0
> FriendlyEventName=Stopped working
> ConsentKey=APPCRASH
> AppName=BlueBubbles
> AppPath=C:\Program Files (x86)\BlueBubbles\bluebubbles_app.exe
> NsPartner=windows
> NsGroup=windows8
> ApplicationIdentity=F3A757484D576258B3CCD31F7678423D
> MetadataHash=-1195804827

I got the webapp working fine to confirm that the connection to the server worked, but still can't get the desktop client to boot up. If this is a redundant post please let me know and I'll delete it. If it's not, I wonder what could be the cause?

Thanks for your time.

**Comment by toastytortilla** [comment]
Attaching crash log as a .txt file if anyone prefers that format
[toastytortilla_BB_crashlog.txt](https://github.com/BlueBubblesApp/bluebubbles-app/files/8599228/toastytortilla_BB_crashlog.txt)
.

**Comment by jjoelj** [comment]
Hey, I believe we've fixed this issue in the latest Microsoft store beta build, which should make it onto the store sometime this week. You can receive beta builds by filling out [this form](https://forms.gle/EK3WYfG715k73j3a6). Alternatively, you can join our [Discord server](https://discord.gg/yC4wr38) and I can dm you the exe version of the build if you'd like.

**Comment by toastytortilla** [comment]
Ah I see, thanks for the clarification. Is your username the same on the Discord server? I'd like to join and possibly get involved!

**Comment by jjoelj** [comment]
> Ah I see, thanks for the clarification. Is your username the same on the Discord server? I'd like to join and possibly get involved!

My username on discord is `@jojejo#3063`
