### ISSUE TITLE
Unable to paste image from clipboard on Win11.

### ISSUE THREAD

**Issue by paulkite** [BlueBubblesApp/bluebubbles-app#2035]
When capturing a screenshot using the Win11 Snipping Tool, the contents get stored in your clipboard once captured. In the web client you're able to paste the captured results into the client whereas with the desktop client nothing happens.

**Comment by tneotia** [comment]
We have added support for image paste in the latest windows beta. Should hopefully roll out to stable in the next few weeks :)
