### ISSUE TITLE
when removed and re-added to a chat, texts don't send

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2038]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-support`.

**Comment by tneotia** [comment]
not sure if this is still an issue - last week we spam removed and readded csab, he was able to text fine. probs would be a server issue anyways since chat GUID and whatnot is all the same
