### ISSUE TITLE
[Desktop] Make sure contact photos refresh in chat list after sync

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2044]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@jojejo` in `#feedback`.

**Comment by zlshames** [comment]
@jjoelj Did you complete this?

**Comment by tneotia** [comment]
This does not appear to be fixed on the latest ms store beta

**Comment by jjoelj** [comment]
Done in 1.9.5
