### ISSUE TITLE
Fix concurrency issue with Chat Heads/Bubbles

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2047]
If the main app is open in the background, and you open a chat head/bubble. Technically there are 2 instances of the app open, and only one of them will receive certain updates/notifications. It's kinda a toss-up/race-case for who actually receives it first. We need to find a way for _both_ instances to receive the event

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#android-development`.

**Comment by zlshames** [comment]
Should we send messages via the SendPort to any other active instances so they can receive it and handle it in the same way? Would that possibly solve this?

Second question, should we pull bubble-support for 1.9.0 if it means this is the caveat?

**Comment by tneotia** [comment]
Should be fixed
