### ISSUE TITLE
delivery time text under messages cut off when DPI of OS changes

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2123]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@samir.a.ali` in `#android-support`.

**Comment by samir-a-ali** [comment]
![Screenshot_20220610-205359_BlueBubbles](https://user-images.githubusercontent.com/107290291/173170139-c87e197a-4211-4ad0-812e-df92c7d3dd96.png)
![Screenshot_20220610-205444_BlueBubbles](https://user-images.githubusercontent.com/107290291/173170140-23a061f1-36de-4993-8452-444219a57f14.png)

**Comment by tneotia** [comment]
Completed in full rewrite
