### ISSUE TITLE
spacing between words too large in material 3 theme

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2124]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@samir.a.ali` in `#android-support`.

**Comment by samir-a-ali** [comment]
![Screenshot_20220610-205359_BlueBubbles](https://user-images.githubusercontent.com/107290291/173170151-7270d37b-41dd-4c5c-9d2a-3bc08df70b34.png)

**Comment by tneotia** [comment]
Addressed in UI rewrite
