### ISSUE TITLE
when avatar is scaled up inside conversation, bubbles are offset to the right

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2125]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@samir.a.ali` in `#android-support`.

**Comment by samir-a-ali** [comment]
![Screenshot_20220610-205444_BlueBubbles](https://user-images.githubusercontent.com/107290291/173170179-2f7f2bf0-9181-4895-921e-a60d12340e12.png)

**Comment by tneotia** [comment]
Resolved in rewrite
