### ISSUE TITLE
sent videos appear as audio in chat but successfully appear as videos to recipients

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2126]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@samir.a.ali` in `#android-support`.

**Comment by samir-a-ali** [comment]
https://drive.google.com/file/d/1D44S-AESdg3ISRYVQtMh3l7lIsQYSBrs/view?usp=drivesdk

Sample video

**Comment by tneotia** [comment]
@samir-a-ali do you still have this video? would like to test and see if fixed

**Comment by tneotia** [comment]
this is properly fixed now
