### ISSUE TITLE
Some settings don't save properly

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2130]
I download/installed the newest 1.9 version and seems like some of the settings don't stick if you close and reopen the app. For example, I turned on the switch for chat list message indicators but of you close and reopen the app the switch turns off.

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-support`.

**Comment by tneotia** [comment]
I think this is a non-issue now
