### ISSUE TITLE
Fix off-center reaction heart, thumbs up, & thumbs down

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#2131]
![Screenshot_20220611-104838](https://user-images.githubusercontent.com/18445938/173192756-95dbf380-afed-4e14-b508-f38e6d63043f.png)

Should be moved down a few pixels

**Comment by zlshames** [comment]
Seems like the thumbs up and down reactions are a bit "high" too

**Comment by tneotia** [comment]
emphasize was the worst one, others seem fine
