### ISSUE TITLE
[Desktop] Only Access Location Services When Necessary.

### ISSUE THREAD

**Issue by SmirkVG** [BlueBubblesApp/bluebubbles-app#2135]
Not sure if the behavior is the same on Android, but on the Windows 11 app, I notice that the BlueBubbles seems to be "using" my location uninterrupted (based on the icon appearing and staying in the taskbar). I understand this is because of the added "Send location" feature.

For the sake of privacy & peace of mind, it would be better if the app fetched the user's location from the system only when requested.

**Comment by tneotia** [comment]
We dont actually fetch the location constantly, this is a weird bug and we dont know what causes it. I think @jjoelj plans to remove the permission entirely, iirc

**Comment by tneotia** [comment]
This is a desktop only issue
