### ISSUE TITLE
[Desktop] Multiple Contacts with the same Contact Photo

### ISSUE THREAD

**Issue by SmirkVG** [BlueBubblesApp/bluebubbles-app#2136]
My contacts are sourced from iCloud (great update!).

Contacts with the same last name all have the same contact photo. On my Apple devices, (iPhone, Mac, etc.) they have unique photos that I've set. For example, the photo BlueBubbles picked for all contacts with my last name (my family members) is my father's. 
After some investigation, I think I've discovered why the issue is happening. Our household still has a landline phone, and I have that number under all of my family members. Of course, they each have their own mobile phone numbers.
Looks to me like the algorithm saw a matching phone number (the home phone) for all of them and THEN chose my dad's photo for everyone since his name would come last alphabetically.

**Comment by jjoelj** [comment]
This is a pretty old ticket. Could you confirm whether this issue is still present on 1.10.1?

**Comment by SmirkVG** [comment]
For a while I had no contact photos, then the most recent update brought them back and it looks like this issue was fixed. Though, occasionally I’ve seen certain contacts in group chats get assigned a completely different contact photo with no discernible pattern to it. That’s a different issue though, will open next time I come across it.
