### ISSUE TITLE
sent pictures missing from chat

### ISSUE THREAD

**Issue by dacmcbibs** [BlueBubblesApp/bluebubbles-app#2141]
Issue: picture missing from chat after sending.

Steps to reproduce - On my phone if I close the chat before the picture fully sends and loads when I come back into the chat the image is not there.

The image sends correctly, and if manually synch messages from the server the missing image re-appears

**Comment by zlshames** [comment]
By any chance, is this an HEIC image?

**Comment by tneotia** [comment]
tentatively marking this as fixed since all backend was rewritten
