### ISSUE TITLE
[Desktop] [Feature Request] Ask where to save logs before saving

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2162]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#desktop-support`.

**Comment by jjoelj** [comment]
The log system on desktop has improved (logs can be opened/deleted from within the app), so will not be doing this.

**Comment by jjoelj** [comment]
The log system on desktop has improved (logs can be opened/deleted from within the app), so will not be doing this.
