### ISSUE TITLE
[Desktop] Would like tab to bring us from the recipient entry box to the message entry box

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2185]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Nolan` in `#desktop-requests`.

**Comment by supercsc** [comment]
This will allow for a keyboard only flow for messaging:
 from create new message (ctrl+n), to typing the recipient, to going to the message body (tab), to typing the message, to sending the message (enter).

**Comment by tneotia** [comment]
done
