### ISSUE TITLE
[Desktop] Samsung UI Snap Scroll resistance

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2190]
When scrolling with the scroll wheel, the window appears to 'fight' the scroll as it attempts to snap to the nearest point which is in the opposite direction the user is attempting to scroll. Instead, only when using the scroll wheel, the window should automatically snap to the next position in the direction the user is scrolling.

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Randymations` in `#desktop-support`.

**Comment by Randymations** [comment]
![BlueBubbles Scroll Bug](https://user-images.githubusercontent.com/69389619/179068519-1f27c27d-b553-4b5f-aa3a-ccc919cc0cd4.gif)

**Comment by tneotia** [comment]
The snapping has been removed entirely since there isn't a clean way to know which way the window is scrolled to snap properly
