### ISSUE TITLE
[Desktop] Add UI transparency

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2191]
Add transparency in the locations shown below

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Randymations` in `#desktop-support`.

**Comment by Randymations** [comment]
![image](https://user-images.githubusercontent.com/69389619/179068821-dae62a70-2388-45e6-a621-79ba07536484.png)
![image](https://user-images.githubusercontent.com/69389619/179068852-dabaec3a-19d1-48a6-bbc9-82295bb3a61b.png)

**Comment by Randymations** [comment]
![image](https://user-images.githubusercontent.com/69389619/179069208-e8050918-11ae-4062-94e5-8faed6355e03.png)

**Comment by Randymations** [comment]
Additional transparency in these sections, but less than others
![image](https://user-images.githubusercontent.com/69389619/179380188-38c5432b-3b07-4d85-a512-72f521968f04.png)
![image](https://user-images.githubusercontent.com/69389619/179380193-f8dddf3d-a4ed-409b-b649-f31660f19302.png)
![image](https://user-images.githubusercontent.com/69389619/179380217-8f81fbe1-cea9-4c9f-bb90-773d690bc983.png)
![image](https://user-images.githubusercontent.com/69389619/179380224-e5b29184-8d4f-4d50-8779-592a2f12f4ae.png)
