### ISSUE TITLE
server shut down re sync

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2198]
my server shuts down due to power loss because poopy power, it would be better imo if when Android client reconnects it auto syncs with the last messages you missed. Happens a bit to me and more of an ease of use thing rather than a needed feature because I did find manual resync

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@collincreed64` in `#server-support`.

**Comment by tneotia** [comment]
It should do this automatically when you open the app up
