### ISSUE TITLE
Unable to remove participants from groups

### ISSUE THREAD

**Issue by SprintKeyz** [BlueBubblesApp/bluebubbles-app#2200]
Removing participants from groups gives the error "Failed to remove participant: Address field must not be blank!". 

I did some digging in the code, and it seems like on line 271 of the file "/lib/layouts/conversation_details/contact_tile.dart" (android app), `handle.address` in `api.chatParticipant("remove", chat.guid, handle.address)` is probably always null (maybe?). I have experience with Java, but none with dart, and although the code looked somewhat similar in ways it wasn't enough for me to really debug it.

**Comment by tneotia** [comment]
server bug
