### ISSUE TITLE
Scan for server on localhost

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#2216]
See comments here: https://github.com/BlueBubblesApp/bluebubbles-server/issues/390

**Comment by tneotia** [comment]
dupe ticket

**Comment by zlshames** [comment]
Not dupe. This would need to be done on the client-side

**Comment by zlshames** [comment]
Basically, scan private IP space on local network, looking for open port on 1234 (or whatever the BB port is)

**Comment by tneotia** [comment]
it is dupe #1810

**Comment by zlshames** [comment]
ope... let's use this ticket tbh it has more info

**Comment by tneotia** [comment]
done
