### ISSUE TITLE
[Web]  text input box has wrong font color

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2226]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#webapp-development`.

**Comment by kfatehi** [comment]
![image](https://user-images.githubusercontent.com/175305/185780495-3e5d0a6d-08c3-45bd-b95a-9aae1026d93f.png)

this is only an issue on web, not desktop

also heres a link to where the discussion happened https://discord.com/channels/640229510662455326/885718963131154452/1010682873159893023

**Comment by tneotia** [comment]
Fixed
