### ISSUE TITLE
[Web] CORS error when trying to connect using web client

### ISSUE THREAD

**Issue by czcollier** [BlueBubblesApp/bluebubbles-app#2228]
Trying to connect to my bluebubbles app on the web client with Chrome yields a "connecting..." dialog that quickly disappears and the screen stays on the "3 of 4" set up screen.

Looking at the Chrome developer console, I see the following CORS error:

Access to XMLHttpRequest at 'https://<my server>/api/v1/fcm/client?guid=<GUID>' from origin 'https://bluebubbles.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by nmcarp99** [comment]
As of today, I am using ngrok and still am encountering this error. Possibly ngrok needs configuration to add the header in addition to the server responding with it? I have tried disabling CORS on my browser, which does allow me to connect. After attempting to sync messages, the app gives me the following error:

![image](https://user-images.githubusercontent.com/36648995/200139619-537de0cf-0579-4f2f-8f3c-f00133e9634a.png)

The full error:
`DioError [DioErrorType.response]: XMLHttpRequest error.
Source stack:
yw@https://bluebubbles.app/web/main.dart.js:5895:24
b8i/$async$a1x<@https://bluebubbles.app/web/main.dart.js:100860:5
k/s@https://bluebubbles.app/web/main.dart.js:4268:63
$2@https://bluebubbles.app/web/main.dart.js:60092:14
n@https://bluebubbles.app/web/main.dart.js:4254:10
b8i@https://bluebubbles.app/web/main.dart.js:100878:10
a1x@https://bluebubbles.app/web/main.dart.js:100855:24
biz/$async$Ju<@https://bluebubbles.app/web/main.dart.js:100850:5
k/s@https://bluebubbles.app/web/main.dart.js:4268:63
$2@https://bluebubbles.app/web/main.dart.js:60092:14
n@https://bluebubbles.app/web/main.dart.js:4254:10
biz@https://bluebubbles.app/web/main.dart.js:100854:10
Ju@https://bluebubbles.app/web/main.dart.js:100798:35
a3T@https://bluebubbles.app/web/main.dart.js:100795:32
wq@https://bluebubbles.app/web/main.dart.js:100796:27
$0/$async$$0<@https://bluebubbles.app/web/main.dart.js:70411:14
k/s@https://bluebubbles.app/web/main.dart.js:4268:63
$2@https://bluebubbles.app/web/main.dart.js:60092:14
n@https://bluebubbles.app/web/main.dart.js:4254:10
$0@https://bluebubbles.app/web/main.dart.js:70416:10
biV/$async$fw<@https://bluebubbles.app/web/main.dart.js:69944:14
k/s@https://bluebubbles.app/web/main.dart.js:4268:63
$2@https://bluebubbles.app/web/main.dart.js:60092:14
n@https://bluebubbles.app/web/main.dart.js:4254:10
biV@https://bluebubbles.app/web/main.dart.js:69966:10
fw@https://bluebubbles.app/web/main.dart.js:69934:19
b3J/$async$OT<@https://bluebubbles.app/web/main.dart.js:70059:33
k/s@https://bluebubbles.app/web/main.dart.js:4268:63
$2@https://bluebubbles.app/web/main.dart.js:60092:14
n@https://bluebubbles.app/web/main.dart.js:4254:10
b3J@https://bluebubbles.app/web/main.dart.js:70063:10
OT@https://bluebubbles.app/web/main.dart.js:70055:23
b3I@https://bluebubbles.app/web/main.dart.js:70056:22
ay6/$async$EO<@https://bluebubbles.app/web/main.dart.js:95209:20
k/s@https://bluebubbles.app/web/main.dart.js:4268:63
$2@https://bluebubbles.app/web/main.dart.js:60092:14
$0@https://bluebubbles.app/web/main.dart.js:60112:13
cJM@https://bluebubbles.app/web/main.dart.js:4457:5
cKd@https://bluebubbles.app/web/main.dart.js:4459:7
$1@https://bluebubbles.app/web/main.dart.js:60033:3
cNH@https://bluebubbles.app/web/main.dart.js:3120:17
m3/s@https://bluebubbles.app/web/main.dart.js:3128:51
MutationCallback*cGm@https://bluebubbles.app/web/main.dart.js:4237:1
@https://bluebubbles.app/web/main.dart.js:210292:23
lazyFinal/a[c]@https://bluebubbles.app/web/main.dart.js:32:36
clx@https://bluebubbles.app/web/main.dart.js:4464:13
bZs@https://bluebubbles.app/web/main.dart.js:4581:32
p6@https://bluebubbles.app/web/main.dart.js:61667:9
a9k@https://bluebubbles.app/web/main.dart.js:60502:8
lC@https://bluebubbles.app/web/main.dart.js:60500:13
bv@https://bluebubbles.app/web/main.dart.js:60075:13
m@https://bluebubbles.app/web/main.dart.js:4258:10
c1T/$async$c1T<@https://bluebubbles.app/web/main.dart.js:7901:17
k/s@https://bluebubbles.app/web/main.dart.js:4268:63
$2@https://bluebubbles.app/web/main.dart.js:60092:14
n@https://bluebubbles.app/web/main.dart.js:4254:10
c1T@https://bluebubbles.app/web/main.dart.js:7902:10
c0u/$async$c0u<@https://bluebubbles.app/web/main.dart.js:49253:14
k/s@https://bluebubbles.app/web/main.dart.js:4268:63
$2@https://bluebubbles.app/web/main.dart.js:60092:14
n@https://bluebubbles.app/web/main.dart.js:4254:10
c0u@https://bluebubbles.app/web/main.dart.js:49255:10
@https://bluebubbles.app/web/main.dart.js:211232:7
@https://bluebubbles.app/web/main.dart.js:211226:56
dartProgram@https://bluebubbles.app/web/main.dart.js:211229:84
@https://bluebubbles.app/web/main.dart.js:211232:15
`

**Comment by tneotia** [comment]
I recommend moving to cloudflare instead as it doesnt have this issue. Ngrok seems to either be blocked or have this CORS issue on chrome these days.

**Comment by nmcarp99** [comment]
Using cloud flare seemed to fix it, thank you!
