### ISSUE TITLE
"Unknown Group Event" when sending messages

### ISSUE THREAD

**Issue by Greigh** [BlueBubblesApp/bluebubbles-app#2245]
![20220902_161549](https://user-images.githubusercontent.com/57759540/188231117-22812267-a596-417a-a1ac-01338b08611c.jpg)

All of the messages that I send end up saying Unknown Group Event. All of the Server settings say connected. 

Including ones, I send on my Mac. I put a [message on Discord](https://discord.com/channels/640229510662455326/746560644995612752/1015355340042272820) if someone wants to message me for logs. 

Thanks!

**Comment by zlshames** [comment]
Fixed by server release
