### ISSUE TITLE
Better deleted chat handling

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#2257]
1. When a chat is deleted, don't remove it from the DB, just set a deleted_at field timestamp
2. When we fetch chats for the chat list, exclude if deleted_at IS NOT NULL
3. When we receive a new-message notification, if it's for a deleted chat, set the deleted_at flag to null.
4. Update chat in the chat list so it re-appears

**Comment by tneotia** [comment]
done
