### ISSUE TITLE
FlatHub packaged Linux app freezes after screen lock / minimize

### ISSUE THREAD

**Issue by richardbowman** [BlueBubblesApp/bluebubbles-app#2264]
Hi, I don't know what issues are related, but for me on Fedora 36, the version currently in Flathub (still 1.9.7) is basically broken with multiple issues:

1) The big blocking issue is that the app hangs after you lock your screen (this is on a Gnome 42 desktop) - I can replicate this 100% of the time. It also happens many times, but not always, if you just move the app to the background or minimize it -- you have to quit and reload after you stop using it for anything. The window doesn't accept any inputs, and if you for instance resize the window, it won't redraw anymore.

2) As #2213 already mentioned, the version in Flathub doesn't seem to work on Wayland anymore (older versions worked just fine). This one isn't a deal breaker but an odd regression.

3) Also wondering what's happening with Flathub publishing since 1.10 was released 8 days ago and isn't on Flathub. I was hoping to just find a TAR file for Linux support to try the latest version to see if any of this was resolved but noticing they are gone now from the release artifacts.

Happy to help debug any of these issues if I can get some pointers on how to best do so.

**Comment by jjoelj** [comment]
2. Is the Wayland issue only on the Flathub version or also on the binaries available [in this release](https://github.com/BlueBubblesApp/bluebubbles-app/releases/tag/v1.10.0%2B31)? These correspond to the 1.9.102.0 beta release available both on Discord and in the Flathub beta repo. I know that the flatpak config does not have wayland as I (apparently incorrectly) read that Flutter didn't support wayland. If the binaries in the aforementioned release work, I'll remove the flatpak limitation in the next release.

3. I've been busy lately, but a stable Linux build should make its way to Flathub sometime this week after a final beta.

1. As for this issue, I'm not sure what causes it, but it's possible that the updated framework present in 1.9.102.0 will fix it.

If you're able to test out the beta build, that'd be great. I'll be releasing the final beta soon

**Comment by jjoelj** [comment]
I think I may have found the culprit for the freezing after lock/sleep: https://github.com/antler119/system_tray/issues/53

I also fixed the wayland segfault by updating our dependency thanks to https://github.com/leanflutter/screen_retriever/pull/3

**Comment by jjoelj** [comment]
I've released 1.10 on flathub. The wayland issue is definitely fixed. Let me know if the other issue persists. Otherwise we can close this.

**Comment by jjoelj** [comment]
1.12 has just made it to beta (1.11.100.0). Closing this. Reopen if it's still an issue
