### ISSUE TITLE
New Messages still failing to show up in open chats

### ISSUE THREAD

**Issue by Mx772** [BlueBubblesApp/bluebubbles-app#2266]
Re: [Release v1.10.1](https://github.com/BlueBubblesApp/bluebubbles-app/releases/tag/v1.10.1%2B36)
> Fixes issue where new messages wouldn't show in an open chat until re-entering the chat.

Unfortunately this doesn't seem to be fully fixed. 
Currently on v1.10.1 on android and still seeing this behaviour. 

I am currently on:
Android 13
ServerV: 1.3.0
MacOS: 11.6.8
AndroidV: 1.10.1

I have also noticed that this behaviour is active even if following a new message through a notification. (If that chat was the last opened chat)

**Comment by buds115** [comment]
I am also experiencing this issue which has been making it hard to use.

**Comment by brianangulo** [comment]
I'm experiencing this

**Comment by zlshames** [comment]
> I'm experiencing this

This will be fixed in the next client update. We are rewriting most of the app, which is why it's taking a bit longer to release. But once it's done, things should be much more reliable

**Comment by tneotia** [comment]
Completed in full rewrite
