### ISSUE TITLE
[Web app feature request] Compatibility with PW managers (e.g. BitWarden, KeePass)

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2268]
![PW_Manager](https://media.discordapp.net/attachments/746560677333827584/1021992234989662219/PW.png?width=1480&height=827)

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#webapp-requests`.

**Comment by tneotia** [comment]
This is not something we can do because flutter doesn't render in traditional HTML elements that can be interacted with by extensions and stuff
