### ISSUE TITLE
Load entire message search context

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2269]
Rather than just 25 in either direction, find a way to allow users to scroll the view up and down indefinitely

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#android-development`.

**Comment by tneotia** [comment]
It is not being addressed yet

**Comment by zlshames** [comment]
Has this been addressed now? Pretty sure when you search you can get the surrounding context/texts

**Comment by tneotia** [comment]
Can't keep scrolling only loads last 25
