### ISSUE TITLE
Implement better GamePigeon (and other) widgets

### ISSUE THREAD

**Issue by jjoelj** [BlueBubblesApp/bluebubbles-app#2277]
BlueBubbles Server versions `>=1.2.0` send additional metadata about messages to the clients.
We'll use this issue to track the message structure of GamePigeon and other special messages, such as Apple Pay, so that we can display them better in the message view.

Here is the attributedBody of a GamePigeon Basketball message:

`{string: �￼, runs: [{range: [0, 1], attributes: {__kIMBaseWritingDirectionAttributeName: -1, __kIMBreadcrumbTextMarkerAttributeName: Basketball, __kIMBreadcrumbTextOptionFlags: 0}}, {range: [1, 1], attributes: {__kIMBaseWritingDirectionAttributeName: -1, __kIMMessagePartAttributeName: 0, __kIMFileTransferGUIDAttributeName: at_0_34B24A96-383F-4E9B-B1B1-840611C0E921}}]}`

**Comment by tneotia** [comment]
Completed in full rewrite
