### ISSUE TITLE
FlatHub version is stale

### ISSUE THREAD

**Issue by SMores** [BlueBubblesApp/bluebubbles-app#2281]
Hello! It looks like the past two versions never made it to FlatHub; the latest there is still 1.9.7.

**Comment by jjoelj** [comment]
Desktop v1.10 (Windows and Linux) are still in beta. Windows is on its final beta (v1.9.104.0) before a stable release, but I am troubleshooting rendering issues on Linux. The latest Linux beta (v1.9.102.0) is available in the Flathub beta repo, or in our Discord server.

I'll update this issue, along with others that have been opened relating to Linux builds, when I am able to fix the rendering issues on Linux and release a stable build.

**Comment by SMores** [comment]
Ah, gotcha! I got misled by the "(stable)" in the release name. Sounds good! Thanks

**Comment by jjoelj** [comment]
1.10 is out on flathub now :)
