### ISSUE TITLE
Cannot scroll on Pinephone Pro

### ISSUE THREAD

**Issue by jvarn** [BlueBubblesApp/bluebubbles-app#2288]
I'm using a Pinephone Pro running Mobian / Phosh.

Installation and message sync works perfectly; however, I cannot scroll through messages: moving my finger up and down the screen just gives the mouseover effect (light grey background) to each message.

- Long pressing works as expected.
- Using a USB mouse to scroll works as expected.

**Comment by tneotia** [comment]
can you try the latest v1.10.1 from either releases or flathub and see if the issue persists?

**Comment by jvarn** [comment]
After updating to 1.10.1.1, the issue persists.

**Comment by jjoelj** [comment]
> After updating to 1.10.1.1, the issue persists.

Do you have the 'Improve Mouse Wheel Scrolling' setting turned on or off?

**Comment by jvarn** [comment]
It is turned off.

**Comment by jjoelj** [comment]
Looks like it's a flutter issue, unfortunately.
 https://github.com/flutter/flutter/issues/90366

I'll continue watching for updates or workarounds.

**Comment by jvarn** [comment]
FYI, I just tested on Manjaro with KDE Plasma Mobile, with same result.

**Comment by jvarn** [comment]
Having read the linked issue, I see it has nothing to do with Wayland/X11 (the main reason I did the above test). It does seem to be Flutter, as you said; and unfortunately it is not a new issue.
