### ISSUE TITLE
move sync group chat icon to chat settings

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2290]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#webapp-requests`.

**Comment by tneotia** [comment]
Not sure if this makes much sense, as "chat list" is dedicated towards that screen and "conversation" is dedicated to the message view

**Comment by tneotia** [comment]
taken care of
