### ISSUE TITLE
Missing scroll bars: linux client

### ISSUE THREAD

**Issue by bohalloran** [BlueBubblesApp/bluebubbles-app#2296]
Running on Ubuntu 22.04 and scroll bars are missing on all Settings menus.

![screenshot](https://user-images.githubusercontent.com/8116388/200426629-68a184bc-9c6a-4492-918e-c9f023baa413.png)

**Comment by jjoelj** [comment]
Fixed in 1.10

**Comment by bohalloran** [comment]
@jjoelj Just installed client from snapstore and scroll bars are missing from all Settings menu options.  The snapstore claims to have published 1.10.100.0 on 02/28.23
