### ISSUE TITLE
Better message sync

### ISSUE THREAD

**Issue by SprintKeyz** [BlueBubblesApp/bluebubbles-app#2303]
Not sure whether this belongs here or as a server issue.

When syncing messages in a chat, the max number of messages that can be synced is 25, and the option from the server settings to sync all doesn't seem to do much. Additionally, message syncing sometimes gets stuck and won't progress, although this is somewhat rare.

**Comment by tneotia** [comment]
Done (server settings option). to sync messages in the chat, you should use the 100 messages option to go farther back
