### ISSUE TITLE
FlatHub app with Fedora 37: version `GLIBC_2.34' not found (required by bluebubbles)

### ISSUE THREAD

**Issue by SMores** [BlueBubblesApp/bluebubbles-app#2304]
I just upgraded my system to [Fedora 37](https://fedoramagazine.org/announcing-fedora-37/). Upon trying to start BlueBubbles, I get the following errors:

```
$ flatpak run app.bluebubbles.BlueBubbles
bluebubbles: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by bluebubbles)
bluebubbles: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /app/bluebubbles/lib/libdart_vlc_plugin.so)
bluebubbles: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /app/bluebubbles/lib/libsystem_tray_plugin.so)
```

It looks like Fedora 37 is using glibc 2.36 (though I have no idea if this is relevant):

```
$ ldd --version
ldd (GNU libc) 2.36
```

Worth noting perhaps that I have half a dozen other Flatpaks installed that are all working. Maybe relevant:

Only one other flatpak is using the Gnome runtime, and that flatpak (Slack) seems to have been updated to use Gnome 43 (which Fedora 37 also uses):

```
     Runtime: org.gnome.Platform/x86_64/43
```

While BlueBubbles is still using 42:

```
     Runtime: org.gnome.Platform/x86_64/42
```

I'm not totally aware of the interplay between the host file system and the flatpak filesystem, so I'm not sure what else is relevant or where else I should be looking, but I'm more than happy to provide more information if it would be at all useful!

**Comment by jjoelj** [comment]
I believe that everything you mentioned is relevant.

I've updated the flatpak to use Gnome 43 to see if that fixes the issue. 1.10.1.1 should be on flathub soon.

**Comment by nmcarp99** [comment]
Using Ubuntu 20.04.1 LTS here, GNOME version for this is 42.5 (fully upgraded as far as I know). As of the latest Bluebubbles update I am getting the message the OP was getting...

**Comment by jjoelj** [comment]
@SMores @nmcarp99 1.10.1.1 has been published to FlatHub. Let me know if the issues persist.

**Comment by nmcarp99** [comment]
Thanks, that fixed it for me!

**Comment by jjoelj** [comment]
Awesome, thanks for the reports, guys.
