### ISSUE TITLE
Fix settings backups related to notification actions

### ISSUE THREAD

**Issue by jjoelj** [BlueBubblesApp/bluebubbles-app#2306]

**Comment by tneotia** [comment]
@jjoelj wasn't this fixed?

**Comment by jjoelj** [comment]
> @jjoelj wasn't this fixed?

They save correctly now. This issue is about the backups to/from the server/json files.

**Comment by tneotia** [comment]
weird... the backup and restore uses the same logic as getting the data from save, so not sure why thats broken

**Comment by jjoelj** [comment]
> weird... the backup and restore uses the same logic as getting the data from save, so not sure why thats broken

I believe it's because `toMap()` returns these settings as lists, and `save()` converts them to strings before saving. `fromMap()` expects the values to be stored as strings. Putting the `jsonEncode()` in` toMap()` would probably fix this.

**Comment by tneotia** [comment]
I fixed this as it was also messing with android
