### ISSUE TITLE
Windows app: Pictures saved without extension

### ISSUE THREAD

**Issue by SD777x** [BlueBubblesApp/bluebubbles-app#2311]
Saving pictures from the Windows app results in a file without an extension.  It looks like the file is still a jpeg file as it opens fine with any photo program, but on inspecting properties it has no extension so may be confusing to some users.

**Comment by LegendaryFire** [comment]
I've also experienced this the odd time here & there.

**Comment by tneotia** [comment]
I dont think this should be happening on the beta app anymore
