### ISSUE TITLE
[Web app feature request] Quick pair with QR code

### ISSUE THREAD

**Issue by dacmcbibs** [BlueBubblesApp/bluebubbles-app#2312]
Just wanted to add a suggestion for a a QR code on the Web App that you can scan with the Blue Bubbles Android App to pair the web app, similar to WhatsApp or Messages for Web, so that we don't have to know / type the configuration into the web app any time we need to set it up.

Maybe this could  also be extended to the desktop client as well?

**Comment by tneotia** [comment]
This would require some centralized server handling these requests and kind of goes against our ethos. Tentatively marking as not planned for now.
