### ISSUE TITLE
[Desktop] forwarding breaks chat list access and renders app unusable when pressing back

### ISSUE THREAD

**Issue by b1ankusername** [BlueBubblesApp/bluebubbles-app#2313]
forwarding breaks chat list access and renders app unusable when pressing back
![image](https://user-images.githubusercontent.com/100311639/205553164-ba7c0f9d-f462-4f88-a363-6e2caa7121f5.png)
![image](https://user-images.githubusercontent.com/100311639/205553176-cec459d8-c0b7-44e8-a048-8f3f78465b60.png)

**Comment by tneotia** [comment]
This appears to be fixed in rewrite
