### ISSUE TITLE
[Desktop/Linux] exception when selecting new message in Ubuntu notifications

### ISSUE THREAD

**Issue by bohalloran** [BlueBubblesApp/bluebubbles-app#2314]
Running linux client on Ubuntu 22.04 LTS;

No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:    22.04
Codename:    jammy

and getting following exception when selecting new message in Ubuntu notifications;

flutter: [BlueBubblesApp][2022-12-05 08:15:39.363656][DEBUG] (Queue) -> [HandleMessage] Successfully mapped message (Chats: 1)
flutter: [BlueBubblesApp][2022-12-05 08:15:39.363935][INFO] Client received new message SMS;-;46339
flutter: [BlueBubblesApp][2022-12-05 08:15:39.454080][INFO] (Actions-HandleMessage) -> New message: [FedEx: Your package is out for delivery today 12/05. fedex.com/t/391274973559/en_US Reply HELP for help. STOP to cancel.] - [BC650D51-7AEB-5FDC-3DF3-8D275C54D894]
flutter: [BlueBubblesApp][2022-12-05 08:15:47.439018][INFO] Startup Logs
flutter: [BlueBubblesApp][2022-12-05 08:15:47.442704][INFO] Opening ObjectBox store from path: /home/briano/.var/app/app.bluebubbles.BlueBubbles/data/bluebubbles/objectbox
flutter: [BlueBubblesApp][2022-12-05 08:15:47.448594][ERROR] Bad state: failed to create store: 10001 Cannot open store: another store is still open using the same path: "/home/briano/.var/app/app.bluebubbles.BlueBubbles/data/bluebubbles/objectbox"
flutter: [BlueBubblesApp][2022-12-05 08:15:47.448692][ERROR] #0      ObjectBoxNativeError.throwMapped (package:objectbox/src/native/bindings/helpers.dart:66)
flutter: #1      throwLatestNativeError (package:objectbox/src/native/bindings/helpers.dart:50)
flutter: #2      checkObxPtr (package:objectbox/src/native/bindings/helpers.dart:32)
flutter: #3      Store._checkStorePointer (package:objectbox/src/native/store.dart:309)
flutter: #4      new Store (package:objectbox/src/native/store.dart:150)
flutter: #5      openStore (package:bluebubbles/objectbox.g.dart:732)
flutter: #6      initApp.initStore (package:bluebubbles/main.dart:287)
flutter: <asynchronous suspension>
flutter: #7      initApp (package:bluebubbles/main.dart:337)
flutter: <asynchronous suspension>
flutter: #8      main (package:bluebubbles/main.dart:149)
flutter: <asynchronous suspension>
flutter: 
flutter: [BlueBubblesApp][2022-12-05 08:15:47.448881][ERROR] LateInitializationError: Field 'store' has not been initialized.
flutter: [BlueBubblesApp][2022-12-05 08:15:47.448924][ERROR] #0      initApp.initStore (package:bluebubbles/main.dart)
flutter: <asynchronous suspension>
flutter: #1      initApp (package:bluebubbles/main.dart:337)
flutter: <asynchronous suspension>
flutter: #2      main (package:bluebubbles/main.dart:149)
flutter: <asynchronous suspension>
flutter: 
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: LateInitializationError: Field 'store' has not been initialized. #0      initApp.initStore (package:bluebubbles/main.dart)
<asynchronous suspension>
#1      initApp (package:bluebubbles/main.dart:337)
<asynchronous suspension>
#2      main (package:bluebubbles/main.dart:149)
<asynchronous suspension>

#0      initApp (package:bluebubbles/main.dart:512)
<asynchronous suspension>
#1      main (package:bluebubbles/main.dart:149)
<asynchronous suspension>

(bluebubbles:2): GLib-GObject-WARNING **: 08:15:52.345: ../gobject/gsignal.c:2772: instance '0x559a60e051b0' has no handler with id '2726'

**Comment by tneotia** [comment]
It looks like its trying to open a new instance of the app rather than use the old instance already open, which would cause this issue

**Comment by bohalloran** [comment]
I'm starting app on command line as;
flatpak run app.bluebubbles.BlueBubbles

Whenever I select notifications in terminal see the above exception and new bluebubbles window with attached screenshot and message.
![Screenshot from 2022-12-07 15-01-48](https://user-images.githubusercontent.com/8116388/206284590-69ad3f19-9397-4f76-b26b-3f57929fa435.PNG)

**Comment by tneotia** [comment]
fixed internally

**Comment by bohalloran** [comment]
Confirmed as fixed.  Thanks!!
