### ISSUE TITLE
Echo effect not playing

### ISSUE THREAD

**Issue by Orcazephyr** [BlueBubblesApp/bluebubbles-app#2315]
I am able to see messages sent and recieved with the Echo effect, but it is not possible to play the animation. I am able to play all of the other effect animations. I observed this on the  android client, but I will test it on windows and web browser when I have a chance.

**Comment by tneotia** [comment]
We don't support the echo animation at this time - it's incredibly difficult to pull off

**Comment by Orcazephyr** [comment]
On a related subject - is this the reason why I cannot tap the invisible ink message to view it, or is there another way besides copying it to read the contents?

**Comment by tneotia** [comment]
you have to swipe on the message to remove the effect, similar to on an apple device

**Comment by Orcazephyr** [comment]
Okay, I can confirm that invisible ink works. 

If the Echo effect isn't ever planned to be added, it would be nice to see some text above the send with Echo icon informing that the animation won't be visible for yourself. Similarly  if you press the replay button, it should show an alert dialog explaining the same thing. I'm not a UI designer, so I don't know if that would be the best place to put it, but some message would be nice.

**Comment by tneotia** [comment]
done

**Comment by ItxWeird** [comment]
Why won't the echo effect ever be added?
