### ISSUE TITLE
on Android: does not initiate conversation to selected number

### ISSUE THREAD

**Issue by marc65864** [BlueBubblesApp/bluebubbles-app#2318]
I'm on Android 12, running BlueBubble Server on MacOS 10.13.6. In the Android app I select a person's phone number but it starts the conservation trying to send the message to the person's mail adress.  Android app tells me that the message couldn't be delivered. I know that it tried to send using the mail adress, because I see it the native message app on the Mac.

**Comment by zlshames** [comment]
This is actually an issue with the way macOS interacts with the Contacts on the Mac devices. If you go into the Contacts app on your Mac and remove the email address from the person's contact entry, it should work the way you expect. 

Lmk if that fixes it
