### ISSUE TITLE
Use Conversations Notifications on Android 

### ISSUE THREAD

**Issue by Orcazephyr** [BlueBubblesApp/bluebubbles-app#2319]
This would allow for only showing bubbles for specific people and changing individual notification sounds. ![Screenshot_20221211-100445.png](https://user-images.githubusercontent.com/54782502/206914894-d149f5a5-519c-4375-8d86-56119a12883a.png)![Screenshot_20221211-100521.png](https://user-images.githubusercontent.com/54782502/206914901-571966ad-bac8-4a62-a0dc-6780faf47d4b.png)

**Comment by tneotia** [comment]
I've tried very hard to find the API for this - with no luck. I haven't seen any other messaging app replicate this behavior, so I'm not sure how to add it. For now, there's an extensive and annoying process you can use to add a specific conversation: 

1. enable "bubble notifications" in android settings
2. get a new notification from a chat you want to mark as favorite
3. expand that notification in the shade (use two fingers so it shows the mark read / reply options
4. on the bottom right, theres a button that looks like a square with an arrow through it, click that
5. it converts the conversation to a bubble, and now it will show up as favoritable in android settings.
6. you can make it priority and also change the ringtones as well iirc

**Comment by Orcazephyr** [comment]
Maybe Android 14 will add an API for this. I'm surprised one doesn't exist already as this seems very fundamental and bubbles aren't exactly new.

**Comment by tneotia** [comment]
I went digging and found it - it isnt documented very well at all. It will be there in next update
