### ISSUE TITLE
[Desktop / Windows] BUG: Black Screen / Broken Navigation after Forwarding Image

### ISSUE THREAD

**Issue by dezryth** [BlueBubblesApp/bluebubbles-app#2331]
**Tested on:** Windows 11 Microsoft Store BlueBubbles Client
**Version:** 1.10.1.0_Windows
**Steps to reproduce:** Select image from a chat and action to "forward" the image to another chat recipient. Attempt to back out of that chat (doesn't matter if you actually complete forwarding or not), and you end up on a black unusable screen that is only rectified by reloading the application.
**Why this is a problem:** Irritating and not a good user experience to have to relaunch the application.

Screenshot of the problem:
![image](https://user-images.githubusercontent.com/5300356/212553600-f1d2fc4f-f4af-4cf8-ad3d-ee8968173da8.png)

Thanks, team! I love the software, and this is a small issue that I figured I could help contribute by raising. I may even look into it myself.

**Comment by tneotia** [comment]
Hi, this will be fixed in the upcoming v1.11 beta for desktop. Thanks for reporting
