### ISSUE TITLE
Feature Request: Allow Bluebubbles-app to support custom Headers

### ISSUE THREAD

**Issue by bpersino** [BlueBubblesApp/bluebubbles-app#2342]
If users decide to put bluebubbles server behind Cloudflare using a custom domain and would like to secure the server using Cloudflare zero trust, it requires the user to authenticate with Cloudflare before the server is accessible, but this is not possible with standalone application that don't have a web interface.  One way around this problem is to have the app support custom headers to bypass Cloudflare zero trust authentication by using service tokens.

**Service Token**
https://developers.cloudflare.com/cloudflare-one/identity/service-tokens/

**Zero Trust**
https://developers.cloudflare.com/cloudflare-one/

Here is an example of what the custom header looks like. 

{
    "CF-Access-Client-Id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.access",
    "CF-Access-Client-Secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}

**Comment by tneotia** [comment]
are socket connections also affected by this? or only http requests

**Comment by bpersino** [comment]
Yes, both websockets and http request are affected.  Essentials everything is blocked by Cloudflare until authentication occurs or using headers with client id and secret to bypass authentication.

Byron

**Comment by tneotia** [comment]
done. next update, long press connect button in the setup pages

**Comment by nathandaven** [comment]
this feature is not working for me. I am able to verify that my tunnel is working using postman, but bluebubbles cannot connect, loops socket error. removing zero trust auth works fine however
