### ISSUE TITLE
[android] In Samsung theme, dividers in chat list blinking in and out

### ISSUE THREAD

**Issue by samir-a-ali** [BlueBubblesApp/bluebubbles-app#2365]
I use the Samsung theme so my thumb can reach all the content and recently I've noticed the conversation dividers blinking in and out. See video 

https://user-images.githubusercontent.com/107290291/215656342-928f27fc-aeda-4f3d-abc1-c7e07b0d760a.mp4

**Comment by tneotia** [comment]
I might just be blind but I don't see any problems on the screen recording

**Comment by samir-a-ali** [comment]
I made another video where I don't click the screen around so much. You can see it between the two group chats and then between the two md chats.

https://user-images.githubusercontent.com/107290291/215658253-95fe7b41-9c12-4a5e-a98a-e4cffe0bfb65.mp4

**Comment by tneotia** [comment]
added different rendering mechanism to fix
