### ISSUE TITLE
[Bug] Unread counts while in a chat do not align with unread dots in the chat list

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#2368]
Some users are reporting that the unread indicator while in chat shows a number (i.e. 2), but when backing out to the chat list, there are no unread chats.

**Comment by tneotia** [comment]
not sure exactly what this comes from, but I changed the mark all as read code to pull from DB in case some chats are like filtered out in the cached chats list

**Comment by zlshames** [comment]
How often does this reload? Just curious because I feel like I've noticed that the unread dot changing as I've left a chat, rather than it already being there when I left... If that makes sense

**Comment by tneotia** [comment]
closing.... I think its something to do with updating from the old app where chats may have artificially gotten stuck as unread - now the mark as read can take care of it properly
