### ISSUE TITLE
Export contacts to server is not functioning 

### ISSUE THREAD

**Issue by samir-a-ali** [BlueBubblesApp/bluebubbles-app#2369]
Currently connected directly to the localhost address. Desktop app has names present but no contact pictures. Attempting to export to contacts shows error code. See attached videos and app/server logs. 

https://user-images.githubusercontent.com/107290291/215858808-889ce844-897f-4542-8f69-4bf63731c7e2.mp4

[linksharing_20230131_140406.txt](https://github.com/BlueBubblesApp/bluebubbles-app/files/10549936/linksharing_20230131_140406.txt)
[BlueBubbles-log-2023131_14320.txt](https://github.com/BlueBubblesApp/bluebubbles-app/files/10549941/BlueBubbles-log-2023131_14320.txt)

**Comment by tneotia** [comment]
This is a server bug, unrelated to android app. we will be releasing a fix for desktop contact names in the next server update
