### ISSUE TITLE
Bug: Conversations with specific contacts have missing messages post-full rewrite

### ISSUE THREAD

**Issue by arnabanerji** [BlueBubblesApp/bluebubbles-app#2371]
After the full rewrite, I've noticed issues with a couple of contacts whose records I've made edits to in Google Contacts, i.e. adding nicknames/merging them. I'm not sure that this is the actual fundamental issue, because it's happening with one contact who I haven't done anything important to as well.

I won't consistently receive message notifications for these contacts and/or they'll appear at the absolute bottom of the conversation list even though they're the most recently updated conversation. After an open/close and a message redownload, the missing message content may appear in the conversation list preview. However, when I open the chat, the message itself won't show -- even for messages that I've reacted to so the app is aware of their existence in some way.

If I do another refresh of the whole app, those conversations may again change to show "Empty message" in the conversation list preview.

I've made edits to those contacts because they're important ones, so I obviously really want those conversations to be functional. Will attempt to document the exact pattern of message being received, effect of refreshing the conversation, etc. more exactly and update this issue. Happy to try and provide more technical info as well if prompted.

P.S. I love this application very much, thank you to all contributors for your incredible work!

**Comment by arnabanerji** [comment]
Thanks for your response! I tried this and it did immediately fix the issue with those certain contacts' messages not appearing or creating notifications.

However, it's now done something else entirely where contacts that were named just fine are only showing a number -- and it may not even be their number or a number that I have saved in my contacts!

Also, I again have a couple of conversations (with both correctly and incorrect associated contacts) that are showing "Empty message" at the bottom of the chat list and are unable to sync more messages.

Finally, not sure if this is related, but before I did anything at all, a number of SMS conversations appeared in my conversation list, notifying me that I had left the conversation. None of these had been active for well over a year before I started using BlueBubbles. Is this normal?

Is my best bet to reset/reconfigure entirely?

**Comment by zlshames** [comment]
If the resync didn't fix your issue, I would advise an android reset tbh. Apologies, but we are unsure why contacts would be associated with incorrect ones

**Comment by arnabanerji** [comment]
I was initially reluctant to do this because it seemed that I had been having trouble getting old conversations synced from my previous BlueBubbles machine over to my current one. However, it looks like things eventually worked, so I was able to give this a shot.

When the initial reload/sync was complete, everything was still messed up in the exact same manner as before -- same contacts named, same contacts only numbers/bizarre incorrect numbers. I attempted to resync handles/contacts again, and when I reopened the app, all contacts were numbers only and I was met with the message for the 1.11 update saying I needed to fix my contacts. Closing and reopening at that prompt gave me fully fixed conversations!

I'm not sure what the difference is between the resync handles/contacts procedure and the contacts fixing that you have for the 1.11 update, but it might be nice to include the option to trigger that process in some way.

Thanks for your support!

**Comment by tneotia** [comment]
It seems you mentioned "old bluebubbles machine" and this may be the root of the issue . When switching the server to a new Mac, you must also fully reset and resync the android app otherwise there will be issues with mismatched contacts and incorrect names
