### ISSUE TITLE
excessive CPU ussage on arch linux desktop using the tarball release of this app

### ISSUE THREAD

**Issue by ipatch** [BlueBubblesApp/bluebubbles-app#2372]
hello, thanks for making this app infrastructure. 🙏

i recently finished setting this app up on my arch linux install. i'm using macos mojave with qemu to run the bluebubbles app server. and am running the desktop client on arch linux.

the first thing i noticed is that the app seems to be using 100% CPU usage when i have the app open.

i'm not familiar with dart, so not sure how much help i can provide, but it seems just leaving the app open in the background causes one of my 4 cores (physical) to use 100% of the CPU. thus causing my cpu temps to increase and cause my cpu fans to spin excessively.

below is a screen grab from running htop on my arch linux install,

![image](https://user-images.githubusercontent.com/613805/216469707-b5fa63d4-fd28-4480-934a-6e38426c249e.png)

**Comment by jjoelj** [comment]
We've identified an issue with the text field that caused CPU usage to be abnormally high when a chat is open. This will be fixed in the upcoming 1.10.10x beta and 1.11.x builds.

Just to confirm, does the CPU usage go down if you open Settings and/or close the open chat?

**Comment by ipatch** [comment]
awesome, can confirm opening the settings tab/dialog from the main app window drop the cpu usage. 👍

**Comment by tneotia** [comment]
closing as already addressed internally

**Comment by ipatch** [comment]
> closing as already addressed internally

does that mean y'all are aware of the issue and are still trying to find a fix?

or does that mean a PR has been merged and this excessive cpu usage should not exist with the linux desktop client because of such PR being merged into a specific branch?

i had a helpful person on the discord server help me build bluebubbles from source using flutter on archlinux the other day, and i'm still seeing about 20% CPU usage when i leave a chat window idle...

that's something that doesn't seem right to me.

**Comment by tneotia** [comment]
yeah if youre running on older hardware as I recall from the discord, thats kind of expected. if the chat window isnt focused, there should be *no* CPU usage (at least on Windows thats the case, Linux may behave differently)

**Comment by ipatch** [comment]
and for reference, when i'm "done" using the app or no longer actively sending a msg i have to leave the app in the following state or else excessive CPU usaage still exists...

![image](https://user-images.githubusercontent.com/613805/216787119-4b5dbfc5-3926-4212-9c97-a5e0c1548f13.png)

**Comment by tneotia** [comment]
yeah, linux may behave differently in that the graphics are still rendering in the background even when they should not be - this isnt something we can address unfortunately. it is a lot better than previously, hopefully as the framework matures even more it gets better over time. simply hitting escape after done with a chat should close that window and drop your cpu usage

**Comment by ipatch** [comment]
> simply hitting escape after done with a chat should close that window and drop your cpu usage

okay i'll give that a try, and thanks for the help, hopefully that can work as a stop gap solution for the time being. 🤞

**Comment by ipatch** [comment]
so even with that state of the application ie. not having a chat selected. i'm still seeing cpu spikes of 5% to 10% every other second or two.

i guess that's to be expected?

![image](https://user-images.githubusercontent.com/613805/216787404-6abd1b39-2b2c-49f0-9247-4d53eb8463dd.png)

**Comment by tneotia** [comment]
honestly not sure, its hard for me to say because personally I use windows on a pretty new machine, and that always shows 0% when not in a chat. since this app isnt made in native C or something, theres always some overhead, I couldnt really say if that would manifest into 5-10% on older hardware, but it could be possible
