### ISSUE TITLE
Desktop (Beta 1.11) Can no longer copy text

### ISSUE THREAD

**Issue by mattn-asurion** [BlueBubblesApp/bluebubbles-app#2381]
On the new 1.11 Beta, the copy text behavior after right-clicking a specific message is no longer functioning:

![bluebubbles_app_Ld8uMIwWky](https://user-images.githubusercontent.com/123412023/218203119-bea55d53-cf1e-4a76-8d6c-495af0eee5c5.gif)

**Comment by tneotia** [comment]
done
