### ISSUE TITLE
Deskstop app switches back to chat list when attempting to add attachment.

### ISSUE THREAD

**Issue by samir-a-ali** [BlueBubblesApp/bluebubbles-app#2382]
Bug only occurs when window is small enough to not show the split screen view with the chat list and the active chat.

https://user-images.githubusercontent.com/107290291/218234408-adfffe4b-7e2a-4e66-afb6-dc79f188cd38.mp4

**Comment by samir-a-ali** [comment]
The active chat also cuts into the view of the top bar with the minimize, fullscreen, and close buttons

**Comment by tneotia** [comment]
fixed
