### ISSUE TITLE
Remake Backup and Restore Menu

### ISSUE THREAD

**Issue by Randymations** [BlueBubblesApp/bluebubbles-app#2394]
Short term:
When saving, text field allows for naming save
Text field defaults to hostname/computer name
Date will append to filename for pretty display and sorting

Long term:
Popup menu will be replaced with proper menu occupying right pane
Options for renaming and deleting saves
Creation date/time is stored in its own read-only field or popup
Saves can be inspected to display what options are stored AND/OR a diff/delta to show what will be changed when applying 
Saves can be reorganized by dragging

**Comment by tneotia** [comment]
done, although reorganizing saves is not something we support. renaming will require a server update as well
