### ISSUE TITLE
[Desktop] If chat list and active chat are in split screen, and then app is minimized to task tray, then Windows notification does not occur for a new message in the active chat. 

### ISSUE THREAD

**Issue by samir-a-ali** [BlueBubblesApp/bluebubbles-app#2396]
Even though app is minimized to tray and out of sight, windows notification does not occur. If window is shrunk so that only chat list is shown, then windows notification occurs. If window is shrunk so that only active chat is shown, then active chat is minimized to tray, windows notification does not occur for new message in active chat.

**Comment by jjoelj** [comment]
Fixed in 1.12
