### ISSUE TITLE
[Android] Custom message received sound occasionally plays when a message is received in the chat list or if the app is in the background

### ISSUE THREAD

**Issue by JFazio13** [BlueBubblesApp/bluebubbles-app#2397]
As the title states, I have a custom received sound set and it occasionally plays even when a conversation is not open. It seems to only play for the last conversation that was open, and it doesn't happen all the time. For example, if I have conversations 1, 2, and 3 in my chat list and just exited conversation 2, a new message received from conversation 2 with the conversation closed and the app in the background (phone can be locked as well) may trigger the sound to play for each message received until another conversation thread is opened.

**Comment by tneotia** [comment]
fixed internally
