### ISSUE TITLE
Android (Bug) - message received sound plays when not supposed to

### ISSUE THREAD

**Issue by carterashwood** [BlueBubblesApp/bluebubbles-app#2402]
The message received sound (not notification sound) still plays when you receive a message from a chat that isn't actively open (and even when the app is closed but still running). It should only play when the relevant chat is open and on screen if being as accurate to iOS is the goal.
![Screenshot_20230223_173103](https://user-images.githubusercontent.com/49218657/221439193-61f17aa0-d88a-4a5e-887b-70504cbd8ef3.png)

**Comment by tneotia** [comment]
fixed internally for next release
