### ISSUE TITLE
Often need to restart app for reactions to display

### ISSUE THREAD

**Issue by JoshKellerstein** [BlueBubblesApp/bluebubbles-app#2403]
Often clicking on the notification of a new reaction, or simply opening the app in some cases doesn't show reactions on messages which have been reacted to. It takes a restart of the app for them to correctly display.

**Comment by zlshames** [comment]
> Often clicking on the notification of a new reaction, or simply opening the app in some cases doesn't show reactions on messages which have been reacted to. It takes a restart of the app for them to correctly display.

can you update to our latest release and let us know if this is still an issue for you?

**Comment by JoshKellerstein** [comment]
Looks like it works. Thanks!
