### ISSUE TITLE
[Android] Incoming messages from numbers not already in chat list do not show in list until the app is fully closed and reopened

### ISSUE THREAD

**Issue by JFazio13** [BlueBubblesApp/bluebubbles-app#2406]
This can be consistently reproduced, whenever a message is received from a number not already in the BlueBubbles chat list, a notification is received as normal but the new message thread is not present in the app. To get the new thread to show, you have to fully close the app from multitasking and reopen it.

**Comment by mace07** [comment]
+1 confirm this issue is present on Android 14 with version 1.12.7 version code 2061

**Comment by tneotia** [comment]
Should be fixed in 1.13.1 update, let us know if it still persists
