### ISSUE TITLE
Profile Pictures are Stretched (Desktop Beta Client exe Windows 11)

### ISSUE THREAD

**Issue by ZenbladeJS** [BlueBubblesApp/bluebubbles-app#2408]
All profile pictures that do not have a 1:1 ratio in their original photos get stretched.
![image](https://user-images.githubusercontent.com/48926193/223613734-cc2f7c44-72d2-4c88-a837-181b6720e9be.png)
![image](https://user-images.githubusercontent.com/48926193/223613771-17793d18-0ec0-4aac-b62a-6808dd916945.png)

**Comment by tneotia** [comment]
This should no longer be an issue with the latest betas
