### ISSUE TITLE
[Android] New received images and other attachments intermittently do not show inside a conversation

### ISSUE THREAD

**Issue by JFazio13** [BlueBubblesApp/bluebubbles-app#2410]
Latest server and Android builds, issue occurs frequently but not every single time.

**When the issue occurs:**
A new image or attachment is received by BlueBubbles and a notification is received. Entering the conversation of the received attachment will not show the new attachment. Sliding left and holding to view message timestamps while in the conversation shows the correct timestamp of the attachment that should be showing below the last received message, but no attachment or message content is shown beside it. To get the attachment to show properly, the app must be fully closed in multitasking and reopened.

**Comment by tneotia** [comment]
Fixed internally, typically only happens with heic images
