### ISSUE TITLE
Replying to extremely long messages creates massive padding above and below the message

### ISSUE THREAD

**Issue by DeveloperBlue** [BlueBubblesApp/bluebubbles-app#2420]
I replied to an extremely long message (A 277 line long list) and I noticed it added a significant amount of padding above and below the reply message. The actual source message does not have this problem.

This occurs both on desktop (1.10.100.0_Windows) and Android (1.11.4 2049)

Above reply:
![image](https://user-images.githubusercontent.com/11480933/225478973-9ac84009-b816-4c4f-a463-f7a03216761c.png)

Below reply:
![bluebubbles_app_96lDWG7wnQ](https://user-images.githubusercontent.com/11480933/225479042-614dc567-40b9-48c9-8eb4-fa9a5c84df63.png)

**Comment by zlshames** [comment]
Thanks for the report! Kinda funny :)
