### ISSUE TITLE
Feature Request: After you download a received file on desktop, an "open file" and "open containing folder" button appear

### ISSUE THREAD

**Issue by merchalex** [BlueBubblesApp/bluebubbles-app#2437]
This feature exists in the form of "open file" button on the WhatsApp desktop client (seen below), but I thought going a step further to add an 'open containing folder' button would be even better and more efficient.

![image](https://user-images.githubusercontent.com/96741407/229027128-b8c0aec1-116a-41de-89d2-3d2b6f3028e8.png)

Thanks for all the hard work.

**Comment by tneotia** [comment]
done, although we can only add one button to a snackbar unfortunately
