### ISSUE TITLE
Android: Keyboard dismisses when switching apps

### ISSUE THREAD

**Issue by keegan-lillo** [BlueBubblesApp/bluebubbles-app#2448]
Hi all, thanks for all the amazing work! 

I've got a slight UI bug when switching between an open chat and other apps. Whenever I switch back to the conversation from a different app, they keyboard dismisses. This happens regardless of the "Auto-open Keyboard" setting.

https://user-images.githubusercontent.com/3537963/232377049-9a73098b-0d44-41d6-a575-ca19aeb53443.mp4

**Comment by tneotia** [comment]
fixed

**Comment by tneotia** [comment]
I'm actually going to mark this as not planned.... Flutter's input / keyboard support is garbage and an implementation for this will introduce issues like #2472 unless its heavily guarded by current app state, which is hard to get in the current codebase
