### ISSUE TITLE
Desktop - Contacts Not Syncing After Latest Update

### ISSUE THREAD

**Issue by meechgalhuquot** [BlueBubblesApp/bluebubbles-app#2461]
After the latest update, my contacts are no longer syncing, both on Windows and on the Flatpak install for Linux.  The Web app is syncing some but not all of my conversations. It doesn't matter if I clear data and resync with the server, the issue remains on both computers.

**Comment by jjoelj** [comment]
Try settings > troubleshooting > resync handles & contacts. Then fully close and reopen the app.

Not sure why reset + resync wouldn't fix it.

**Comment by meechgalhuquot** [comment]
No luck. Still no contacts and all individual chats are in the unknown senders list.On Apr 22, 2023, at 1:46 PM, Joel Jothiprakasam ***@***.***> wrote:﻿
Try settings > troubleshooting > resync handles & contacts. Then fully close and reopen the app.
Not sure why reset + resync wouldn't fix it.

**Comment by jjoelj** [comment]
Feel free to [join our Discord server](https://discord.gg/yC4wr38) if the problem persists.
