### ISSUE TITLE
[Android] 1.12.2: If more than one conversation is present in notification panel, can no longer click into a conversation or expand each conversations

### ISSUE THREAD

**Issue by samir-a-ali** [BlueBubblesApp/bluebubbles-app#2464]
https://user-images.githubusercontent.com/107290291/234148710-f24595e9-4284-48b4-8423-7316b2a33ca7.mp4

**Comment by jjoelj** [comment]
This has to be an OS issue

**Comment by samir-a-ali** [comment]
will close, until i can confirm is specific to bluebubbles
