### ISSUE TITLE
opacity slider while using Aero and transparency mode on windows doesn't affect chat view

### ISSUE THREAD

**Issue by nate-moo** [BlueBubblesApp/bluebubbles-app#2465]
exactly as title says
windows 10 LTSC 19044
latest build from windows store

--

![image](https://user-images.githubusercontent.com/40650681/234154242-89913684-da2a-43e9-b9c4-ccf70a44291a.png)
![image](https://user-images.githubusercontent.com/40650681/234154251-058c4b8f-70dc-49d2-a556-3b225788c267.png)

**Comment by jjoelj** [comment]
I think this is fixed
