### ISSUE TITLE
White line at the top of the window 

### ISSUE THREAD

**Issue by nate-moo** [BlueBubblesApp/bluebubbles-app#2466]
Windows 10 LTSC 19044
Latest Windows Store build
affects all transparency modes and all UI modes (material, iOS, Samsung)

----

![image](https://user-images.githubusercontent.com/40650681/234154601-3c600e99-a57d-4310-9bc6-e7e59632b90c.png)
![image](https://user-images.githubusercontent.com/40650681/234154622-363df6fa-9adb-4157-81c2-e7389bd2da38.png)

**Comment by tneotia** [comment]
@nate-moo confirmed this is no longer happening
