### ISSUE TITLE
Material Light Theme Message React Drop Shadow

### ISSUE THREAD

**Issue by aCobaltHero** [BlueBubblesApp/bluebubbles-app#2471]
On the Material Light Theme, the menu bar holding reactions shows an incorrect drop shadow, placing it too low.

![Screenshot_20230428-084531.png](https://user-images.githubusercontent.com/92462423/235271678-40b3928c-c4bf-4faa-a58e-14e354027bac.png)

**Comment by tneotia** [comment]
done
