### ISSUE TITLE
windows 7 support?

### ISSUE THREAD

**Issue by ipatch** [BlueBubblesApp/bluebubbles-app#2483]
i run windows 7 on a core2duo computer in my garage. (it's what i got). downloaded the latest windows installer from the releases page, i believe it was 1.12.x version. the program seemed to install without any issues.

however the program fails to launch due to a missing dll error,

```
the program can't start because api-ms-win-core-libraryloader-l1-2-0.dll is missing from your computer
```

found a youtube video explaining the error message, downloaded several vc runtimes from microsfot, have all updates installed for my windows 7 box.

after manually downloading the dll and placing it in the `system32` folder as from what i can tell bluebubbles on this computer installed in x86 mode and not amd64 mode, thus manually adding the required dll. i even installed the vc runtime package for x86 from microsoft to see if it would make a difference (no it did not). i'm not the most versed in the windows operating system, but after manually copying the dll mentioned above to the `system32` and attempting to launch bluebubbles i get the below error message on launch now,

---

![image](https://github.com/BlueBubblesApp/bluebubbles-app/assets/613805/d82add2d-3515-40c3-b9d2-cfe146f59292)

**Comment by jjoelj** [comment]
According to [this](https://answers.microsoft.com/en-us/windows/forum/all/api-ms-win-core-libraryloader-l1-2-0dll-is-missing/68151f0b-cbb1-4b5c-934e-792a62be20ac), the issue may be conflicting x86 and x64 dlls
