### ISSUE TITLE
[Feature Request] Show message time on details

### ISSUE THREAD

**Issue by Nickthegoatboy** [BlueBubblesApp/bluebubbles-app#2490]
In the below example, one message was sent almost 30 minutes later but it would be difficult to know this without the delivered timestamp. 

Request is to add an option to display the time of a message when viewing the details (second screenshot). 

![Screenshot_2023-06-01-19-33-54-941_com.bluebubbles.messaging.jpg](https://github.com/BlueBubblesApp/bluebubbles-app/assets/5771123/38968742-bf89-4c63-8205-10980b386d52)

![Screenshot_2023-06-01-19-33-49-739_com.bluebubbles.messaging.jpg](https://github.com/BlueBubblesApp/bluebubbles-app/assets/5771123/cc7b2a38-9a6a-42e9-8470-86c7c1c2e585)

**Comment by tneotia** [comment]
If you slide the view to the left you can view the timestamp, similar to Instagram.

**Comment by Nickthegoatboy** [comment]
> If you slide the view to the left you can view the timestamp, similar to Instagram.

Ah, yes, that is helpful for now! I think it could still be useful to show it in the message details screen, or have something similar to the desktop app, where clicking/tapping on a message brings up the timestamp for that specific message. 

I also think it could be nice to have finer control over the timestamp visibility in general - such as always showing timestamps for every message.

**Comment by tneotia** [comment]
tapping will show the timestamp now
