### ISSUE TITLE
[Android] Issue with rendering conversation causes entire app to freeze and crash.

### ISSUE THREAD

**Issue by samir-a-ali** [BlueBubblesApp/bluebubbles-app#2494]
This is the first instnace ive been able to capture it happening. But an error rendering a photo, an error rendering past messages, or just an unknown render error like in this instance cause the keyboard to freeze and the app to crash.
Cant get error logs because app crashes and i have to restart the app and the logs disappear.

https://github.com/BlueBubblesApp/bluebubbles-app/assets/107290291/22b8c7b7-90bf-4928-b394-d2f18f5845f9

**Comment by jawilson** [comment]
Yes! I've had this exact same issue, annoyingly often actually, and haven't figured out how to best report it yet. Of note, as long as you don't go into that specific thread, the app will work fine. I've managed to get around it sometimes by replying in notifications which still works (more wood to the fire that it's a render issue), but it's super annoying.

If I catch it happening to me again, I assume there may be a way to grab logs via ADB that could be usefuL?

**Comment by samir-a-ali** [comment]
> Yes! I've had this exact same issue, annoyingly often actually, and haven't figured out how to best report it yet. Of note, as long as you don't go into that specific thread, the app will work fine. I've managed to get around it sometimes by replying in notifications which still works (more wood to the fire that it's a render issue), but it's super annoying.
> 
> If I catch it happening to me again, I assume there may be a way to grab logs via ADB that could be usefuL?

how do you grab logs via ADB? I figured out that if I send an .heic photo the app crashes while rendering more often so I think I can reproduce it.

**Comment by zlshames** [comment]
I was actually able to reproduce it. but it only happened for a specific chat, and not all of them. @samir-a-ali @jawilson did you guys notice the same thing?

**Comment by samir-a-ali** [comment]
its happened with 3 chats, those chats happen to have a very high message count. maybe its crashes when trying to load/render all of them?

**Comment by zlshames** [comment]
> its happened with 3 chats, those chats happen to have a very high message count. maybe its crashes when trying to load/render all of them?

we dont render all the messages so idk why it would happen. by any chance, did you enable the scroll to last message option?

**Comment by samir-a-ali** [comment]
I do have this enabled yeah

**Comment by zlshames** [comment]
> I do have this enabled yeah

can you try disabling it and see if the issue persists :) I think that might be causing it cuz it just started freezing for me when i enabled it the other day

**Comment by samir-a-ali** [comment]
Will do

Samir A. Ali
New York Medical College
M.D. Candidate '24

**Comment by samir-a-ali** [comment]
will do

**Comment by jawilson** [comment]
> Have you noticed that disabling it fixes the crash? I have on my end.

Okay, I'm pretty sure I can say that disabling fixes the issue when it pops up. Interestingly, if I re-enable it before anything else happens in the conversation the issue no longer presents itself.

**Comment by tneotia** [comment]
redid the logic for this, and it *should* no longer happen. will need testing once a new update comes out.
