### ISSUE TITLE
[BUG] Improved scrolling breaks scrolling on Ubuntu 22.04

### ISSUE THREAD

**Issue by Morpheus636** [BlueBubblesApp/bluebubbles-app#2497]
Expected Behavior: Scrolling functions.

Actual Behavior: Scrolling does nothing on any screen or menu within Bluebubbles when Improved Scrolling is enabled.

Proposed Solution: Remove improved scrolling option. 

cc: @jjoelj

**Comment by jjoelj** [comment]
Apparently I fixed this ages ago. It's just not in a build yet...
https://github.com/BlueBubblesApp/bluebubbles-app/commit/c2ec11ab01a10f7fb1a422ab246f8b0296f87c06

**Comment by Morpheus636** [comment]
Haha I feel that.
