### ISSUE TITLE
New emojis don't display

### ISSUE THREAD

**Issue by jonprocter** [BlueBubblesApp/bluebubbles-app#2512]
Hi! I've noticed new emojis just show as boxes with a cross through them. If I enable the iOS emoji pack, they just show as blank. The emojis work fine in every other app and they show on my keyboard fine. 

Using latest version in the Play Store (1.12.2) on Android 13 on a new motorola razr 40 ultra. 

Thanks!

**Comment by jonprocter** [comment]
I installed the beta from GitHub, emojis work with the iOS pack enabled but still display as a box with a cross through it if using the system Android emojis.

**Comment by tneotia** [comment]
Unfortunately this is a flutter limitation, they haven't updated their internal fonts pack to support new emojis. This will be fixed once they do this.
