### ISSUE TITLE
Flatpak relaunching when tray icon present throws an error.

### ISSUE THREAD

**Issue by minseungchoi** [BlueBubblesApp/bluebubbles-app#2521]
I'm running OpenSUSE Aeon and using BlueBubbles through a Flatpak installation. 

When I try to reopen BlueBubbles while there is an instance running in the tray icon by launching the app through GNOME, I get an error message that says:
```
Whoops, looks like we messed up. Unfortunately you will need to reinstall the app, sorry for the inconvenience :(
Error: LateInitializationError: Field 'store' has not been initialized.
Stacktrace: #0   initApp (package:bluebubbles/main.dart)
<asynchronous suspension>
#1    main (package:bluebubbles/main.dart:74)
<asynchronous suspension>
```
I'm guessing that the desired behavior is that when the app is running in the background, relaunching the app should just open the background app, instead of raising the error message.

Thank you for all your hard work!

**Comment by minseungchoi** [comment]
I'm wondering how it works on other platforms: does BlueBubbles task bar icon show up at all times, or just when the app is minimized/closed? Persistent task bar option might be desirable...

**Comment by minseungchoi** [comment]
Wow never mind... I think I'm blind. I think I missed the ... task tray icon, because I was expecting some blue color there. I guess a still valid issue is that when the app is running in the background, relaunching the app should just open the background app, instead of raising the error message.

**Comment by tneotia** [comment]
related to double instance issue on Linux, which is fixed in upcoming release
