### ISSUE TITLE
Feature Request: Message Search in individual chat

### ISSUE THREAD

**Issue by Swayyum** [BlueBubblesApp/bluebubbles-app#2528]
A search option for individual chats or group chats. Something like discords search feature where you can search messages sent by a specific member or messages sent on a date. Though a simple: type in words and it finds every message with those words would also be good.

**Comment by Nickthegoatboy** [comment]
Sounds similar to https://github.com/BlueBubblesApp/bluebubbles-app/issues/2477 - does that capture what you're looking for?

**Comment by tneotia** [comment]
closing as dupe of https://github.com/BlueBubblesApp/bluebubbles-app/issues/2477
