### ISSUE TITLE
Support Password Managers For Server Setup

### ISSUE THREAD

**Issue by jawilson** [BlueBubblesApp/bluebubbles-app#2532]
Basically, it would be great if the password input box had whatever config is necessary to allow for password managers to autofill. Even better would be when manually filling in the server/password if the server URL input was marked as a "username" field.

On Android when setting up the application for the first time you are unable to autofill the server password box if you have a password manager configured. I believe this has always been an issue, but I just re-installed the app today and set up the server via Google Sign In and when it came time to enter the server password my keyboard didn't have any features like autocorrect (which seems... correct), or, more importantly, the ability to use a password manager to autofill. Previously, I believe this was true when manually entering the server URL and password.

I just double checked and the same situation is true of the [Web app](https://bluebubbles.app/web).

### Server
**Device:** Qemu on Linux (iMac Retina 5K, 27-inch 2017)
**macOS:** Ventura 13.2.1
**BlueBubbles Server:** 1.7.3

### Android
**Device:** Pixel 7 Pro
**Android Version:** 13
**Build number:** TQ3A.230805.001
**BlueBubbles Client:** 1.12.3 (from GitHub)
**Keyboard:** Microsoft SwiftKey Beta Keyboard (version 9.10.19.19)
**Password Manager App:** Bitwarden (version 2023.7.0)

### Web
**Device:** Dell XPS 15 9350
**OS:** Windows 11 (version 22H2)
**Browser:** Google Chrome Beta (version 117.0.5938.11 (Official Build) beta (64-bit))
**Password Manager Extension:** [Bitwarden - Free Password Manager](https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb) (version 2023.7.0)

**Comment by tneotia** [comment]
done
