### ISSUE TITLE
Show Avatars in DM Chats makes no change

### ISSUE THREAD

**Issue by cynojien** [BlueBubblesApp/bluebubbles-app#2542]
I recently disabled the Show Avatars in DM Chats option and it appears to have not made any change. I played around with the settings and noticed that the setting does effect the iOS and Samsung theme. So this bug only happens with the Material theme. 

I have attempted resetting and reinstalling the app. No change.

Seems unnecessary to have the avatar there all the time. 

Thanks guys.

**Comment by tneotia** [comment]
done
