### ISSUE TITLE
Textbox for sending messages loses focus as soon as cursor mouses out

### ISSUE THREAD

**Issue by dezryth** [BlueBubblesApp/bluebubbles-app#2543]
The text box now loses focus and cannot be typed into anymore as soon as the user mouses out of the textbox area. I believe this is probably related to the code pushed to address #2524

**Comment by jjoelj** [comment]
This was caused by me adding support for keyboard scrolling. I've fixed this issue in this commit https://github.com/BlueBubblesApp/bluebubbles-app/commit/148e81dfa69753cde71e25c712144e2bff19887a and it will be in the next update (1.12.5)
