### ISSUE TITLE
Desktop app: Right click on conversation menu does not pull up chat options

### ISSUE THREAD

**Issue by samir-a-ali** [BlueBubblesApp/bluebubbles-app#2555]
right click on conversation menu does not pull up options such as delete archive pin etc

**Comment by jjoelj** [comment]
wat. can you attach a screen rec

**Comment by samir-a-ali** [comment]
https://github.com/BlueBubblesApp/bluebubbles-app/assets/107290291/ca6ddbfb-cc06-451a-a788-1e4d23055620

sorry the recording isnt more helpful lol, im just spamming right click, and then i dry dragging it

**Comment by jjoelj** [comment]
Ah ok it's probably a bug with the material/samsung conversation tile. I fixed it on the ios skin but I guess I forgot the others.

**Comment by tneotia** [comment]
fixed
