### ISSUE TITLE
Only a handful of Contact Avatars (<5) appear on Windows app

### ISSUE THREAD

**Issue by ddiggles** [BlueBubblesApp/bluebubbles-app#2558]
Hello!

Just installed BlueBubbles on MacOS Catalina VM, newest version on Github (1.8).  Installed BlueBubbles on Windows 11.  Everything seems to be working, but all my contact avatars are blank - except for a handful, which is bizarre.  Like <5 of hundreds.

BB Server says it has contacts access, but all contacts listed have "N/A" under the Avatars column.  My contacts are via Gmail, which is synced with Apple Contacts on the VM as well as my iPhone.  All contact avatars show up properly in iMessage on both phone and MacOS.

Tried resyncing contacts in app, also completely reset Server but neither had any effect.

![image](https://github.com/BlueBubblesApp/bluebubbles-app/assets/19737405/25f171d9-1f26-4568-aa27-1150318be036)

**Comment by tneotia** [comment]
Unfortunately, this seems to be a limitation of our contacts plugin on the server, usually with Google Contacts it just doesn't have much luck in fetching avatars. We aren't sure why right now.

**Comment by tchirou** [comment]
@ddiggles 
Sorry to dig this up but I have the same problem on ventura with a mac mini and windows 11
I have found that the only avatar showing are coming from contacts with no space in the cell number 
Could you please check on your end if you have the same thing ?
Thanks a lot

**Comment by ddiggles** [comment]
@tchirou 

I ended up just putting my avatars in manually via the bluebubbles app.  That was the only way I could get them to show up (consistently).  It sometimes seemed like if it was an iOS contacts app avatar, they would show up.  But if they were from another location (i.e. gmail, like in my OP), they wouldn't work.  I tried a lot of things but it was always wonky.
