### ISSUE TITLE
Contact names do not show for non-iMessage contacts in SMS chats, but DO show if they are in MMS group chats

### ISSUE THREAD

**Issue by ddiggles** [BlueBubblesApp/bluebubbles-app#2571]
Non-iPhone contacts' names do not show up in the conversation pane in SMS conversations.  So the SMS recipient will only show up as their phone number.

If that same recipient is in a group chat (MMS-based), then their contact name does show up properly.

![image](https://github.com/BlueBubblesApp/bluebubbles-app/assets/19737405/c8d4825e-003c-472f-8975-c488702098c9)
![image](https://github.com/BlueBubblesApp/bluebubbles-app/assets/19737405/c204e47a-cb10-4535-b12f-954a6a32de50)

In second picture, MacOS is on left, BB desktop app is on right.

**Comment by ddiggles** [comment]
An edit on this issue, this is for NEW contacts that I have added since beginning to use bluebubbles.  "Old" SMS contacts show up fine in SMS and MMS threads.

I have made sure to run contact sync / refresh on both client and server, and restarted both, etc. to verify issue.

**Comment by ddiggles** [comment]
Turns out that clicking on the chat avatar (top panel of the message pane), to bring up "Details," and then clicking "Fetch Chat Details," refreshes the contact name and then it displays properly.

**Comment by mbuonaccorsi** [comment]
I am having this same issue.  New chats (iMessage or SMS, doesn't matter) don't sync contact info.

Using the Details > Fetch Chat Details button does not fix anything.

Any update on this being fixed?
