### ISSUE TITLE
Images pixelizing on zoom rather than blurring

### ISSUE THREAD

**Issue by SpaceSaver** [BlueBubblesApp/bluebubbles-app#2572]
Many apps to preserve the perceived quality of an image and readability of text will blur on zoom rather than displaying raw pixels.  Something in BB appears to be interfering with that in full screen previews in the Web App and Android.  Probably more.

BB:
<image src="https://github.com/BlueBubblesApp/bluebubbles-app/assets/60277022/82ed2f3e-7bdf-426a-8a38-1e665b4c1672" width="400px">

Samsung Gallery after downloading from BB:
<image src="https://github.com/BlueBubblesApp/bluebubbles-app/assets/60277022/793d6d6f-ae23-4cdf-9439-cc4334a30a16" width="400px">

**Comment by carterashwood** [comment]
This is due to the use of the Nearest Neighbor scaling algorithm rather than a more advanced algorithm such as Bilinear or Bicubic.
