### ISSUE TITLE
French language renaming app to "App Killer Manager"

### ISSUE THREAD

**Issue by SpaceSaver** [BlueBubblesApp/bluebubbles-app#2573]
The app renames itself to "App Killer Manager" when the device language is set to French.  This is due to the package `disable_battery_optimization 1.1.0+1` overriding the `@string/app_name` value for the French language which since BlueBubbles doesn't have anything set for, flutter takes as the `@string/app_name` value for French.

The problem package: https://pub.dev/packages/disable_battery_optimization
Their GitHub: https://github.com/pvsvamsi/Disable-Battery-Optimizations

**Comment by tneotia** [comment]
Fix coming shortly

**Comment by SpaceSaver** [comment]
> Fix coming shortly

👍

**Comment by michaelcspeed** [comment]
This still happens for me on 1.1.1

**Comment by SpaceSaver** [comment]
> This still happens for me on 1.1.1

Please update your install, this is a really old version
