### ISSUE TITLE
Recognize 1-time passcodes, address, Phone numbers  etc.

### ISSUE THREAD

**Issue by mjruotolo** [BlueBubblesApp/bluebubbles-app#2576]
Is it possible to Recognize 1-time passcodes and add them to the clipboard?  
Also is possible to recognize emails address or phones numbers in a messages and make them hyperlink?
Can there be an option added to be able to copy part of message instead of all of it?

**Comment by jjoelj** [comment]
You can press and hold the copy button to bring up a dialog that you can copy a selection from. We might want to add an explicit option in the more options menu

**Comment by jjoelj** [comment]
What platform of the client are you using?

**Comment by mjruotolo** [comment]
> What platform of the client are you using?

I’m using the android version.

**Comment by jjoelj** [comment]
> > What platform of the client are you using?
> 
> I’m using the android version.

You can enable the phone number and email linking in settings > conversation settings > smart suggestions
