### ISSUE TITLE
Custom header to fix ngrok issues

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#2580]
Either set the `ngrok-skip-browser-warning` header to true or add a proper User-Agent like `BlueBubbles/v1.12.4` or something

Both would be good but only the ngrok header if the URL is ngrok related

**Comment by joshuajohncohen** [comment]
For the ngrok custom header it has to set the header on the preflight request as well because ngrok is intercepting it

**Comment by joshuajohncohen** [comment]
Easiest thing is to set a User-Agent because that is already included with the preflight
