### ISSUE TITLE
Unable to send tapbacks in sms chats.

### ISSUE THREAD

**Issue by Keegan24680** [BlueBubblesApp/bluebubbles-app#2582]
I am unable to send tapbacks in sms chats.

**Comment by ItxWeird** [comment]
Tapbacks are only avaliable for imessage chats.

**Comment by Keegan24680** [comment]
You are able to do it with the messages app on Mac and iPhone.

**Comment by tneotia** [comment]
While yes, you can technically "send a tapback", it just sends as a regular text message to recipients which is why we haven't included this functionality. There isn't really a purpose of tapback functionality for SMS chats because it only shows as a tapback on the message for you
