### ISSUE TITLE
On Android, allow image viewer's top bar to hide/show with bottom bar 

### ISSUE THREAD

**Issue by halfway2anywhere** [BlueBubblesApp/bluebubbles-app#2607]
Could the app be updated so attachments go full screen when you tap on them in the attachment view? now it still shows the top bar with 'done' and hides the bottom row of buttons, but doesn't expand to take up the screen.

**Comment by halfway2anywhere** [comment]
https://github.com/BlueBubblesApp/bluebubbles-app/assets/84814040/b6416bc5-cc5d-482c-87a4-aa7a6f61249d

The top bar hides but the image still doesn't actually go full screen

**Comment by zlshames** [comment]
Fair enough, we'll re-look at it.

**Comment by halfway2anywhere** [comment]
It also doesn't hide the top ir bottom bar for videos at all. I'm not sure if that's intentional.
