### ISSUE TITLE
{Request} Option to register phone number with iMessage in app

### ISSUE THREAD

**Issue by cynojien** [BlueBubblesApp/bluebubbles-app#2613]
I'm sure you guys have heard about Beeper Mini and it's ability to do iMessage phone number registration without an iPhone.

Seeing as the "engine" powering this functionality is open source and all on device would it be possible to implement the feature into BlueBubbles? 
[https://github.com/JJTech0130/pypush](https://github.com/JJTech0130/pypush)
[https://jjtech.dev/reverse-engineering/imessage-explained](https://jjtech.dev/reverse-engineering/imessage-explained)

I personally prefer the customization, extra features, and complete open-source nature of BlueBubbles so it would be really nice to not have to use the Beeper Mini app for number registration which is what I'm doing for now as the iPhone I had keeping my number registered became a spicy pillow.

Thank you guys for this project. I very much apprentice it!

Also, sorry if this a double post. I searched for anything related and didn't find anything.

**Comment by eiqnepm** [comment]
I'm looking forward to seeing an open source alternative to Beeper Mini.

Beeper Mini claims all of the encryption is done client sided. While I am inclined to believe them, until an interdependent audit has  been conducted, it would be unwise to completely trust that statement.

It is also not possible to use Beeper Mini without Google Play Services.

It would make a lot of sense to me if BlueBubbles redirected their focus from a client-server model, to a completely client sided model.

Beeper Mini also does some fancy stuff on their servers to relay push notifications to prevent the need to keep the client persistently running. I should imagine this would be out of the scope for BlueBubbles if they decided to go the client sided route. Instead having the client persistently running seems like a reasonable. This would actually be better for privacy and also have the added benefit of not requiring Google Play Services.

**Comment by cynojien** [comment]
Did not mean to close.

**Comment by SpaceSaver** [comment]
This will likely come once the version is finished that makes it operate serverless, like Beeper Mini.

**Comment by cynojien** [comment]
> This will likely come once the version is finished that makes it operate serverless, like Beeper Mini.

Is that something that the team is working on? I haven't heard anything about that.

**Comment by tneotia** [comment]
this method is now broken (seemingly for a long time), so closing this for now
