### ISSUE TITLE
Ability to change open with maps to use coordinates instead of address

### ISSUE THREAD

**Issue by SpaceSaver** [BlueBubblesApp/bluebubbles-app#2617]
Sometimes you are at say a concert venue where it is one large plot of land with a singular address, I would like an option to change the Find My open with maps feature to open with maps based on the coordinates instead of the reported address.  Here's an example with what the link would look like: https://www.google.com/maps?q=38.898263,-77.0366537

**Comment by tneotia** [comment]
Fixed internally
