### ISSUE TITLE
When generating a URL preview title, strip www from domain

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#2627]
Often when sending links with www, the preview will show `www` as the preview title because it's being parsed as the domain or something. 

We should properly parse the domain to show it in the URL

**Comment by tneotia** [comment]
Got an example link that does this?

**Comment by zlshames** [comment]
I don't right now, but if i run into it i can. I think it just happens when a link is like `https://www.somelink.com` or something. And for whatever reason, the code strips out the main hostname (probably thinking the `www` is the hostname)
