### ISSUE TITLE
Client does not enable new features after upgrading server's macOS version

### ISSUE THREAD

**Issue by Nystrata** [BlueBubblesApp/bluebubbles-app#2636]
After updating from Monterey (vanilla) to Ventura (OCLP), 
The Android client does not show the new iMessage Private API features (reply, edit, unsend etc...) until I uninstall and reinstall the Android client app.

Client: 1.12.7 / 2061
Server:  1.9.2

**Comment by tneotia** [comment]
whenever you change servers or reset the server (which I assume you had to reset for OCLP, you must reset the android app, things go kinda haywire otherwise)

**Comment by Nystrata** [comment]
I did an in-place upgrade

**Comment by tneotia** [comment]
Does the in-place upgrade to OCLP not wipe your entire data (setup macOS from scratch again)?

**Comment by Nystrata** [comment]
I'm assuming that my user home folder being intact means it didn't do a wipe.
