### ISSUE TITLE
Custom Themes Not Syncing to Cloud

### ISSUE THREAD

**Issue by itsanoel** [BlueBubblesApp/bluebubbles-app#2641]
Custom themes on my android and windows clients not backed up to the cloud, but they do properly export local backups. No errors are reported in the apps or the server. Settings backups work properly. Restarting the clients or the server does not fix the issue.

https://github.com/BlueBubblesApp/bluebubbles-app/assets/48412794/153e4867-8b72-43bf-b6c5-674f651d8090

**Comment by zlshames** [comment]
I was unable to replicate this. Are you using a custom theme? If you haven't created a custom/new theme, there won't be anything to backup.

**Comment by itsanoel** [comment]
Yep, using a custom theme. On my bluebubbles desktop, I have 2 custom themes: Android Messages Desktop (currently selected) and Android Messages Mobile. At some point I was able to backup Android Messages Mobile (not sure how), but trying to backup now with either selected still does not back up the Desktop theme. Settings backups are still working fine.
![image](https://github.com/BlueBubblesApp/bluebubbles-app/assets/48412794/f71837b2-3997-4361-9043-a00654908ba6)

**Comment by tneotia** [comment]
Can you run logging from troubleshoot menu as you try to back up the desktop theme

**Comment by itsanoel** [comment]
Text:
[BlueBubblesApp][2024-01-22 17:13:16.267744][INFO] (REQUEST[GET]) -> PATH: https://acquire-phrase-consultants-jpg.trycloudflare.com/api/v1/backup/settings
[BlueBubblesApp][2024-01-22 17:13:16.405014][INFO] (RESPONSE[200]) -> PATH: https://acquire-phrase-consultants-jpg.trycloudflare.com/api/v1/backup/settings
[BlueBubblesApp][2024-01-22 17:13:16.406038][INFO] (REQUEST[GET]) -> PATH: https://acquire-phrase-consultants-jpg.trycloudflare.com/api/v1/backup/theme
[BlueBubblesApp][2024-01-22 17:13:16.525367][INFO] (RESPONSE[200]) -> PATH: https://acquire-phrase-consultants-jpg.trycloudflare.com/api/v1/backup/theme
[BlueBubblesApp][2024-01-22 17:13:18.227922][INFO] (REQUEST[POST]) -> PATH: https://acquire-phrase-consultants-jpg.trycloudflare.com/api/v1/backup/theme
[BlueBubblesApp][2024-01-22 17:13:18.343107][INFO] (RESPONSE[200]) -> PATH: https://acquire-phrase-consultants-jpg.trycloudflare.com/api/v1/backup/theme
[BlueBubblesApp][2024-01-22 17:13:18.343774][INFO] (REQUEST[POST]) -> PATH: https://acquire-phrase-consultants-jpg.trycloudflare.com/api/v1/backup/theme
[BlueBubblesApp][2024-01-22 17:13:18.462107][ERROR] (ERROR[400]) -> PATH: https://acquire-phrase-consultants-jpg.trycloudflare.com/api/v1/backup/theme
[BlueBubblesApp][2024-01-22 17:13:18.463208][ERROR] (ERROR[400]) -> null
[BlueBubblesApp][2024-01-22 17:13:18.463208][ERROR] (ERROR[400]) -> application/json
[BlueBubblesApp][2024-01-22 17:13:18.463208][ERROR] (ERROR[400]) -> {status: 400, message: You've made a bad request! Please check your request params & body, error: {type: Validation Error, message: The name may not be greater than 50 characters.}}
[BlueBubblesApp][2024-01-22 17:13:19.151367][INFO] (REQUEST[GET]) -> PATH: https://acquire-phrase-consultants-jpg.trycloudflare.com/api/v1/backup/settings
[BlueBubblesApp][2024-01-22 17:13:19.294444][INFO] (RESPONSE[200]) -> PATH: https://acquire-phrase-consultants-jpg.trycloudflare.com/api/v1/backup/settings
[BlueBubblesApp][2024-01-22 17:13:19.295247][INFO] (REQUEST[GET]) -> PATH: https://acquire-phrase-consultants-jpg.trycloudflare.com/api/v1/backup/theme
[BlueBubblesApp][2024-01-22 17:13:19.407801][INFO] (RESPONSE[200]) -> PATH: https://acquire-phrase-consultants-jpg.trycloudflare.com/api/v1/backup/theme
[BlueBubbles_Logs_2024-1-22_17-13-22.txt](https://github.com/BlueBubblesApp/bluebubbles-app/files/14016001/BlueBubbles_Logs_2024-1-22_17-13-22.txt)

**Comment by tneotia** [comment]
Ahhh.... well there's the issue I guess, @zlshames do you want to change this server side, should we truncate the theme name before uploading, or should we throw an error on android telling the user to reduce the theme name length before uploading?

**Comment by zlshames** [comment]
> Ahhh.... well there's the issue I guess, @zlshames do you want to change this server side, should we truncate the theme name before uploading, or should we throw an error on android telling the user to reduce the theme name length before uploading?

Yep, the server is doing it's job by validating the name. Just truncate it on the client side
