### ISSUE TITLE
Remember "reply" state when changing chats

### ISSUE THREAD

**Issue by dratze98** [BlueBubblesApp/bluebubbles-app#2642]
Currently, if I type a message and then change to a different chat and then come back, the message is still there (this is great and super helpful!), but if that message was a reply to a message it forgets that it is a reply. This has resulted in me sending regular messages that were supposed to be replies. Could we make it so that it remembers if it is replying to a message or not when we leave a chat?

**Comment by cameronaaron** [comment]
this would be a big help
