### ISSUE TITLE
Android app feature request - Auto detect iPhone contacts from non-iPhone contacts

### ISSUE THREAD

**Issue by mn1968** [BlueBubblesApp/bluebubbles-app#2643]
I have BB setup with Private API/SIP disabled. As a result, when I search and select a contact,  the android app will detect whether the contact is an iPhone (switches to Blue iMessage tab), or not (switches to Green SMS Tab). Since the app can determine iPhones from non-iPhones, is it possible to have ONLY all iPhone contacts display when the Blue iPhone tab is selected when starting a New Conversation?

**Comment by zlshames** [comment]
Unfortunately, no, not really. We would have to check all of your contact numbers to see if it's registered. Not just the one you type/choose. Closing as I don't think this would be feasible without a ton of extra processing
