### ISSUE TITLE
[Bug][Android] Multiple Contacts apps breaks the "Add Contact" and "Info" buttons

### ISSUE THREAD

**Issue by DeveloperBlue** [BlueBubblesApp/bluebubbles-app#2644]
I have two contact apps installed: Samsung's default Contacts app and Google's Contacts app.

When both apps are installed the "Add Contact" button and "Info" button in does not work. This happens regardless of which app is set as the default Contacts app.

#### Reproduction:
https://github.com/BlueBubblesApp/bluebubbles-app/assets/11480933/756f0d81-6761-4941-9e75-89102ad53ae3

I'm happy do any troubleshooting or run any experimental builds to help debug this.

----

Samsung Galaxy Note20 Ultra
OneUI 5.1
Android 13
BlueBubbles 1.12.7 2061

### Additional Information:

- Setting the default Contacts app* (to either app) doesn't seem to fix this
- The Samsung Contacts app can't be uninstalled 😠
- Uninstalling the Google Contacts app does fix the buttons. (But this is not optimal).
- In other apps, when no default app is set, I get prompted for which Contacts app I would like to use. The BlueBubbles app didn't do this.

----

*I don't know if this really matters, but I just wanted to add that in OneUI 5.1 there's no way to explicitly set the default Contacts app in settings:

I have to open different apps (The Samsung dialer, Google's Messages app, etc.) and trigger "Add Contact" and "View Contact Information" actions from there, and then I'm prompted for which app I'd like to use for each action. 

Instead of a system-wide "This is my default Contacts app" setting, it's more of a "For the 'Add Contact' action, use this Contacts App" and "For the 'View Contact Information' action, use this Contacts app". 

Setting either Contacts app as the default for all those actions still does not fix the issue.

**Comment by SpaceSaver** [comment]
@DeveloperBlue As a temporary bandage you could try uninstalling Samsung Contacts via adb, or disabling it
