### ISSUE TITLE
[Bug Fix] Sort messages by earliest value: dateCreated or dateDelivered

### ISSUE THREAD

**Issue by seanlowe** [BlueBubblesApp/bluebubbles-app#2660]
**Issue:** Messages can get wildly out of order when switching between devices (devices in question: Android mobile and either Ubuntu or Windows PC). 

**Description:** I've already joined the discord and talked to Tanay about this issue. This seems to be an issue with High Sierra which I've hosted my server on, but I have no ability to switch to a higher macOS just to solve this problem and honestly, I'm not even sure it would fix it. This is a high enough priority (for me) that I've honestly considered not using BlueBubbles at all just to not have to deal with trying to parse out *my own conversations* because there's no semblance of order to them at all. I don't honestly know how I can open the app and a message sent 10 minutes ago suddenly says it was created 10 *minutes from now*. If it was just that all these messages were getting a `dateCreated` of the moment I open the app, but it seems like it only assigns the first message that time and then uses the correct spacing between subsequent messages to create the `dateCreated` on those messages, leaving me with messages that are created in the future. This means when I send a new message, it's then placed in the middle of all these random messages, further obfuscating the actual flow of the conversation.

**Suggested solution:** I've looked through the code a little and I would put up a PR but I have no time right now to do so. My suggested solution is to, anywhere we do a .sort(...) on messages, we sort by whichever value is earlier, `dateCreated` *or* `dateDelivered`. From my observations, `dateDelivered` has never been wrong, only `dateCreated` so using whichever is earlier should be a solid enough fix if the actual underlying problem (whether that be how messages are "created" in the app or an actual DB issue on High Sierra) is untenable.

This is extremely frustrating, please fix this.

**Comment by SpaceSaver** [comment]
OCLP?

**Comment by seanlowe** [comment]
Ran across this issue again today. Was messaging a friend on the desktop app, hopped over to Android client to send a video, then came back and saw this issue on the video I just sent. Checking the message details shows this:

![image](https://github.com/user-attachments/assets/7fbdb8c9-b33c-4db4-8a6c-b1add20f198d)
