### ISSUE TITLE
New Conversation Merge all users data into one 

### ISSUE THREAD

**Issue by AndyXheli** [BlueBubblesApp/bluebubbles-app#2662]
Currently, if you select new conversation and ypu scroll throw the contacts list you'll see the same user multiple times but one may have the phone number one may have the email and etc It would be nice to merge all that info into one and if someone clicks on the user then prompt to select phone number or email 

Tested this on android app. I'm sure the other platforms are the same.

**Comment by zlshames** [comment]
When you search the person by name, it'll show the existing chat higher at the top of the list, no? Same as if you typed their phone number
