### ISSUE TITLE
Android Client: Server is unreachable / no-ip.org with Let's Encrypt

### ISSUE THREAD

**Issue by bigmalletman** [BlueBubblesApp/bluebubbles-app#2673]
Please reference discord thread: https://discord.com/channels/640229510662455326/1206322471448481792

As I understand it, most users are using Cloudflare proxy. I was trying to set up Dynamic DNS but am unable to get the Android client to connect to my no-ip.org address.

If I use http, I have no issues and the Detect Localhost Address functionality also works perfectly. However, using unencrypted traffic would be very unwise.

If I try to use https along with my valid Let's Encrypt certificate, I run into issues.

The Detect Localhost Address functionality won't work with this setup. If you set up Dynamic DNS with https, the port only outputs https traffic. This isn't really a huge issue, since there isn't an increase in latency when using Dynamic DNS, Detect Localhost can simply be disabled.
The web client has no issues connecting ... however, the Android client (1.13.0 from Google Play Store) will not connect.
The error I am getting in the debug log is -- OS Error: CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:393))
However, if I go to my custom URL in a web browser or CURL, everything reports that this is a valid certificate. The Android client acts like it isn't even attempting to check the certificate.
I connect through Firebase and have also tried with the QR code. The startup page just reports that the server is unreachable.

I will switch to Cloudflare in the meantime, but I would find Dynamic DNS ideal for my purposes.

[BlueBubbles-log-2024211_151331.txt](https://github.com/BlueBubblesApp/bluebubbles-app/files/14234091/BlueBubbles-log-2024211_151331.txt)

**Comment by bigmalletman** [comment]
I just discovered, if I change the url to the port forward to 443 -> 1234, the android client will connect. However, this is not ideal, since 443 is typically not open or pointing toward some other service.

**Comment by ampersandru** [comment]
Same issue here, trying to use https with 1234 causes BB android client unable to connect but can access within web browser

**Comment by bigmalletman** [comment]
including the intermediate certificate in the server.pem resolved this issue.
however, i am unsure why this Only affected the Android client and why it only affected non-443 ports.
