### ISSUE TITLE
New messages are received but not shown in reading pane

### ISSUE THREAD

**Issue by weflower** [BlueBubblesApp/bluebubbles-app#2680]
**Client Info**
1.12.7.0_Windows (from the MS Store)

**Server Info**
Server Version: 1.9.5
macOS Version: 12.7.3

**Issue**
For SMS text messages, when I receive messages they appear in the left panel but nothing displays in the reading pane.

See picture:
![blue-bubbles-incoming-bug](https://github.com/BlueBubblesApp/bluebubbles-app/assets/22036497/88927dd9-ff71-4a9e-91b1-0cd2c9ef4bfe)

**Comment by Girgl3** [comment]
I have the same problem. Not sure how to fix it

**Comment by jjoelj** [comment]
Deleting the AppData folder and setting the app up again should fix this. It's a bug caused by resetting the app from within the app.
