### ISSUE TITLE
App Causing S22 Ultra Lag

### ISSUE THREAD

**Issue by AndyXheli** [BlueBubblesApp/bluebubbles-app#2694]
Hi everyone, I'm noticing lag on my S22 Ultra after installing this app. Not sure what's up I removed this app lag gone also seeing big battery drain 

Running Android 14 OneUI 6.0 

app 1.13.0

Server 9.5

**Comment by zlshames** [comment]
Your entire phone is lagging? Are you sure it's BlueBubbles? The app should affect other apps, and at least since he latest update, we've dramatically reduced battery drain. You shouldn't see anything excessive. Do you have the battery stat screenshot to show it's draining?

**Comment by AndyXheli** [comment]
Hey @zlshames  I just did a factory reset on the phone let me see what happens. I'll keep you posted. :)

**Comment by zlshames** [comment]
> Hey @zlshames  I just did a factory reset on the phone let me see what happens. I'll keep you posted. :) 
> 

Woah, well, I dont think you needed to do that but 🤷🏽‍♂️
