### ISSUE TITLE
Firebase stuck on old cloudfare URL

### ISSUE THREAD

**Issue by samir-a-ali** [BlueBubblesApp/bluebubbles-app#2698]
attempting to use the google sign in to fetch the new cloudfare url from the firebase console just gives us an old CF url.

**Comment by zlshames** [comment]
This just means the server didn't update it in the Firestore.  I have an alpha build that should fix it, I just want some testers before releasing. Would you wanna test?

**Comment by samir-a-ali** [comment]
Sure I can test it

**Comment by cameronaaron** [comment]
I am having similar issues even on the latest dev branch but in my case the URL wont switch from local host to the server URL even when off network

**Comment by zlshames** [comment]
> I am having similar issues even on the latest dev branch but in my case the URL wont switch from local host to the server URL even when off network

Sounds like you have the Detect Localhost Address option enabled on the client? Disable that maybe?

**Comment by cameronaaron** [comment]
I mean yea but I would expect it to transition when off local host.. I especially would not expect it to still be able to receive but not send. there is a bug here

**Comment by zlshames** [comment]
> I mean yea but I would expect it to transition when off local host.. I especially would not expect it to still be able to receive but not send. there is a bug here

Receiving messages will come through firebase, so it doesn't require a direct/open connection to the server. Different mechanisms. 

If localhost detection is enabled, that will take priority over your server address. So if your server address changes, localhost will still take precedence over the new server URL. 

Even if you sign in with Google, the new server URL will be stored, but localhost will still be used until you leave your home WiFi

**Comment by cameronaaron** [comment]
I feel like we are not understanding each other. 

Steps to reproduce the issue:

1. One enable local host detection
2. Notice on local host (cool)
3.  Leave local network 
4. Can receive messages but not send them
5. looks at network I am connected to notices it still shows local host address.
6. Close and reopen app 5 times eventually I get the right URL

**Comment by zlshames** [comment]
> I feel like we are not understanding each other.
> 
> Steps to reproduce the issue:
> 
> 1. One enable local host detection
> 2. Notice on local host (cool)
> 3. Leave local network
> 4. Can receive messages but not send them
> 5. looks at network I am connected to notices it still shows local host address.
> 6. Close and reopen app 5 times eventually I get the right URL

Different issue. I think what you are looking for is this: https://github.com/BlueBubblesApp/bluebubbles-app/issues/2696
