### ISSUE TITLE
International Phone Numbers do not display correctly (truncates to US DID format)

### ISSUE THREAD

**Issue by blue-archon** [BlueBubblesApp/bluebubbles-app#2707]
Hello, the BB address book is not correctly parsing the contacts as specified in Contacts for international numbers. For instance: the number +919912345678 will be displayed as 991-234-5678. It is not clear if this is just a display issue or if it actually uses the wrong number. Both iMessage and SMS Forwarding have this issue.

In any case, this is a quality of life improvement that would help make BB an even more polished app than it already is.

2 cents -- I feel that we are at a point where the stability of the software is solid. Most of the issues with server connectivity, seem to be tied to user error or user insistence on using quirky setups.

It would be great to see some of these type of issues (and other annoyances like duplicate contacts) get resolved as part of the release cycle.

**Comment by zlshames** [comment]
Dupe: https://github.com/BlueBubblesApp/bluebubbles-app/issues/2566
