### ISSUE TITLE
Emoji 15.1 emojis do not show up as big emojis

### ISSUE THREAD

**Issue by sabogalc** [BlueBubblesApp/bluebubbles-app#2708]
The following emojis do not show up as big emojis: 🙂‍↔️, 🙂‍↕️, 🐦‍🔥, 🍋‍🟩, 🍄‍🟫, and ⛓️‍💥.

Below is BB vs. iOS
![image](https://github.com/BlueBubblesApp/bluebubbles-app/assets/53708281/f61dcead-9b72-42a7-a504-fcca392fd673)
![image](https://github.com/BlueBubblesApp/bluebubbles-app/assets/53708281/c7598744-c2d7-451b-99df-64af137be9b3)

**Comment by zlshames** [comment]
My initial guess is because they are 4-byte Unicode characters, which are seen as multiple characters when you test the length, so it doesn't get picked up as <= 3 characters

**Comment by tneotia** [comment]
Fixed with updated iOS font and emoji rejex
