### ISSUE TITLE
system tray icon in flatpak version of bluebubbles desktop is not working properly

### ISSUE THREAD

**Issue by queenbiscuit311** [BlueBubblesApp/bluebubbles-app#2717]
The system tray icon in the flatpak app doesn't work due to missing flatpak options. Running the app with command "flatpak run --talk-name=org.kde.StatusNotifierWatcher app.bluebubbles.BlueBubbles" or enabling "D-Bus session bus" in flatseal fixes this.

In addition, the system tray icon is blank because it attempts to set the icon to /app/bluebubbles/data/flutter_assets/assets/icon/icon.png, which doesn't exist outside of the flatpak container.

**Comment by meap02** [comment]
Can I configure my BlueBubbles to use the system tray icon outside its container? Maybe even set my own?
