### ISSUE TITLE
Windows client - focus on textbox when edit is chosen

### ISSUE THREAD

**Issue by mrsamypnw** [BlueBubblesApp/bluebubbles-app#2734]
Hi -

Using Windows client version 1.12.7.0 with server 1.9.6. When I right-click and choose edit on a message I sent, the edit text box doesn't have focus. I have to click into the edit text box in order to modify the iMessage text.

Is that expected behavior? If so, can an enhancement be made to add that?

**Comment by jjoelj** [comment]
This is fixed in the 1.13 beta release
