### ISSUE TITLE
Windows: Can't view BB program even though it's open in background

### ISSUE THREAD

**Issue by SD777x** [BlueBubblesApp/bluebubbles-app#2759]
This happens both with  1.13.0 beta or the 1.12.7 release.  I open BB but the program windows doesn't open.  I check task manager and it's running in the background (FYI it fluctuates from 6-11% CPU but that's another issue I suppose).  I don't see it in the taskbar or tray and can't seem to open it.  I don't have any hidden monitors, I have 2 monitors which are both on and the laptop itself which has the monitor disabled via Windows settings.  I've tried to reboot, completely uninstall and reinstall, etc and still does the same thing.  It's odd because on my other computers BB works fine. 

Hardware: LG Gram 16 2-in-1, 12th gen i7-1260p, 16gb RAM
Software: Windows 11 Pro 22631.3737

**Comment by jjoelj** [comment]
Is your issue related to [this one](https://github.com/BlueBubblesApp/bluebubbles-app/issues/2629)?

**Comment by SD777x** [comment]
> Is your issue related to [this one](https://github.com/BlueBubblesApp/bluebubbles-app/issues/2629)?

I deleted the appdata as instructed and it worked, TYVM.
