### ISSUE TITLE
Phone keeps killing BlueBubbles

### ISSUE THREAD

**Issue by Perifractic** [BlueBubblesApp/bluebubbles-app#2765]
I have a Kyocera Docomo Digno 4 (KY-42C). I fully appreciate it's not a commonly used device (though it's very popular in Japan), but then again it runs Android 10 and other background apps like Tessie (Tesla app that displays permanent notification) are not being killed like BlueBubbles.

Please note the phone doesn't support Google Play Services, but that doesn't seem to matter.

When I open BlueBubbles, it connects to the server, and if it remains in the foreground on screen, all notifications seem to work great. All my chats are there. 

Strangely though the desktop client reports no Androids are connected. But it works.

As soon as I return to home screen, the app gets killed and notifications stop, every time.

I've tried ADB commands like dumpsys deviceidle whitelist +com.bluebubbles.messaging to no avail. I also have tried the direct socket connection notification, and when that stays in the taskbar notifications do work, but it often gets killed (again apps like Tessie are not being killed and their permanent notifications remain 24/7).

I'd really love to get this working reliably as this phone is wonderful and has saved me from smartphone addiction, but I need iMessage. Any ideas from saving the process from apparently being killed?

Thanks in advance.

**Comment by zlshames** [comment]
Closing this as we've worked together on the side to solve this. We are 90% there
