### ISSUE TITLE
No Android Auto Messages

### ISSUE THREAD

**Issue by jdebner** [BlueBubblesApp/bluebubbles-app#2767]
Hello!

I'm unable to see any incoming messages as notifications from Android Auto. From the changelog I see there should be support but it doesn't seem to work at all. Is there anything I can test or help repro in order to help debug this? I'd love to get this app working with Android Auto.

**Comment by cameronaaron** [comment]
you have to download it from github not the app store

**Comment by jdebner** [comment]
Will try this, any reason that's the case as I assume most people install from the Play store?

**Comment by cameronaaron** [comment]
Play store doesn't have a Mac to be able to setup a server and test it on
Android auto

**Comment by jdebner** [comment]
Thanks for the clarification, if a test server can be set up then test credentials can be passed along to the testing team which is frequently used for these types of limitations. 

I think it would be well worth it to increase access to safer driving for all Play Store download users! Let me know if I can help at all to set up the streaming process.

**Comment by drewjc75** [comment]
I mean I've got an old Mac Mini I could send along if they need something to test with?

**Comment by zlshames** [comment]
Closing. For now, only the GitHub builds will be able to use AA
