### ISSUE TITLE
Samsung phone with HEIF/HEIC photos has duplicate (HEIC.JPG) pictures in gallery

### ISSUE THREAD

**Issue by rsipka** [BlueBubblesApp/bluebubbles-app#2769]
Hello,
on my Samsung S23, when taking photos, I use the HEIF format (HEIC extension).

I've noticed, that when I browse media from inside BlueBubbles app, for each HEIC file, new HEIC.JPG file is created in the same folder (so alongside the original file). Example:

20240712_165642.heic becomes 20240712_165642.heic **and** 20240712_165642.heic.jpg.

I suspect that this is the media browser inside BlueBubbles is converting them on the fly when viewing the gallery inside the app (when choosing pic to attach to the chat).

This creates duplicate file(s) that are then uploaded to my Nextcloud/Syncthing/etc.

Using Bluebubbles app from Google Play Store, v1.13.2. Phone is on Android 14, OneUI 6.1.

Is this a bug or feature? Shouldn't files be converted only during upload, if necessary?

If anyone could shed a light at that behavior, I would be glad. 

Thanks, Radek

**Comment by zlshames** [comment]
The server is what converts them to a jpg. You are seeing the duplicates in BlueBubble's media browser in the conversation details page? Or are you seeing dupes in your photos app?

**Comment by keegan-lillo** [comment]
I had "Auto-download attachments" turned on, but I think it is the client doing it as the duplicated photos are ones I've never sent

**Comment by zlshames** [comment]
> I had "Auto-download attachments" turned on, but I think it is the client doing it as the duplicated photos are ones I've never sent

I wonder if the auto-download attachments will download both the HEIC version and the JPG converted version when it's enabled. if so, we probably should choose one or the other...

**Comment by rsipka** [comment]
For me, I don't see duplicates in Samsung Gallery or the Media browser from BlueBubbles app, but I do see them in the file explorer (for example Total Commander for Android), and I mainly noticed since all the .jpg files get uploaded to my Nextcloud.

The JPG converted pictures appear on the android filesystem immediately (in the same folder as original picture) once I open the Media Browser and start scrolling to select photo - every photo viewed in the grid gets converted, not just those you select to upload. I attach the example (of just 3 photos, but many more got created in my last "swipe" across the media browser).

I speak about local Android pictures that you want to send from BlueBubbles app via Media Browser. If I hit Share from Samsung Gallery -> select BlueBubbles -> share to contact/group, no duplicate is created that way (at least in any folder I would notice).

![Screenshot_20240812_233730_Total Commander](https://github.com/user-attachments/assets/3daf73b5-dc57-4fd4-98f2-93bbe2c0e39d)

**Comment by rsipka** [comment]
Hello,
the path is standard `/storage/emulated/0/DCIM/Camera` and the pictures are the photos taken previously by the camera (into .heic) and when viewed from media browser (inside BlueBubbles, when you open chat with contact and try to select media to send to the contact) the .jpg are generated and saved in the same path as above.

This happens with Auto-save attachments On or Off (as those are NOT attachments sent by someone to the chat),

So, flow is as follows:
- I take picture with camera, it's saved as `/storage/emulated/0/DCIM/Camera/20240811_180021.heic`
- later on, I open chat in BlueBubbles, and click on the Media browser to select photos ![Screenshot_20240813_172040_BlueBubbles](https://github.com/user-attachments/assets/817f6a31-e4b8-465d-b76b-cbf20c7be107)
- Once it opens, EVERY picture it shows thumbnail of (in my case those are always `.heic`) will have the `.jpg` generated in the same folder as original picture
- This "duplicate" `.jpg` is staying in the folder indefinitely (and is immediately detected by Nextcloud and uploaded - this is how I noticed, I don't normally look into the `/storage/emulated/0/DCIM/Camera` folder).
- I need to manually remove the .jpg files


Yesterday, I tried to download source code and opened it in Android Studio, unfortunately I didn't even find the part that is the Media browser - total newbie in that regards, I just noticed Flutter is used, but as I don't know it, I don't even know if it's some Flutter component :/

**Comment by zlshames** [comment]
Fixed: https://github.com/BlueBubblesApp/bluebubbles-app/commit/cd5489884fcd2e849b90d7e876fb8ed582eccc23
Will be in next release
