### ISSUE TITLE
Suggestion: use WebView for FaceTime 

### ISSUE THREAD

**Issue by User8395** [BlueBubblesApp/bluebubbles-app#2775]
Instead of redirecting the user to chrome whenever a FaceTime call comes, Android System WebView should be used instead, as it is based on Chrome and allows for a full screen FaceTime experience on Android.

**Comment by zlshames** [comment]
I think the reason we did it this way was so that you could stay in the call but still respond to texts and stuff

**Comment by User8395** [comment]
> I think the reason we did it this way was so that you could stay in the call but still respond to texts and stuff

The WebView could be a separate activity with a big return to call button at the top like other services.

**Comment by tneotia** [comment]
The real reason it was done this way is because the framework we use (Flutter) frankly has terrible support for web views and other platform native components. Handling permissions and even just webview performance is pretty poor. Using the built in browser just makes sure that the experience stays as good as possible even though the downside is it's not truly full screen.

**Comment by User8395** [comment]
> The real reason it was done this way is because the framework we use (Flutter) frankly has terrible support for web views and other platform native components. Handling permissions and even just webview performance is pretty poor. Using the built in browser just makes sure that the experience stays as good as possible even though the downside is it's not truly full screen.

I see. I wanted this because I use Firefox, which for reasons unbeknownst to me, is not supported by FaceTime.

**Comment by tneotia** [comment]
We have thought about this and it *should* forcefully open in chrome as long as you have it installed.

**Comment by User8395** [comment]
> We have thought about this and it _should_ forcefully open in Chrome as long as you have it installed.

I had Chrome disabled which is why it wasn't opening 😅.
