### ISSUE TITLE
Emoji fill into focused text box

### ISSUE THREAD

**Issue by mehapps** [BlueBubblesApp/bluebubbles-app#2777]
Currently emoji always go into the main message box which works for sends/replies but not for edits, my thought is that emojis should just go into whatever box is focused so that it would work for sending, replying, but also for editing

**Comment by zlshames** [comment]
Can you provide an example screenshot or something or process to reproduce the issue? Are emojis not being allowed to be entered during editing?

**Comment by mehapps** [comment]
https://github.com/user-attachments/assets/f42c124c-0e2f-4785-84c5-b44796f6da7f
For me they're being forced into the main message box

**Comment by jjoelj** [comment]
This only applies to desktop beta. I'll fix this before stable
