### ISSUE TITLE
option to remove tapback names 

### ISSUE THREAD

**Issue by mehapps** [BlueBubblesApp/bluebubbles-app#2779]
This might be kinda niche and the way BB does it rn follows what iOS does for notifications but I'd like to have an option if possible to remove the contact name on a tapback action within the notification, so instead of <contact> loved/liked <message> it would just be Loved <message>

**Comment by zlshames** [comment]
done. development branch. will release with next release

**Comment by zlshames** [comment]
@mehapps I'm looking at an iPhone and it shows sender names before reactions in the chat list and in notifications

**Comment by mehapps** [comment]
> @mehapps I'm looking at an iPhone and it shows sender names before reactions in the chat list and in notifications

Yeah I'm looking at mine now and I think you're right, I don't actually remember where I saw it otherwise (it may have been my watch)
