### ISSUE TITLE
Issue with split view causes back button to break and app to become unresponsive

### ISSUE THREAD

**Issue by ChrisSmith2** [BlueBubblesApp/bluebubbles-app#2792]
**I'm using:**
BlueBubbles installed from the windows store, version 1.12.102.0

**Issue:**
In split view, if you press the back button on the right side (to hide the current settings page) and then try to press the back button on the left side, nothing will happen and various parts of the app then become non-functional. For instance, the back button breaks, the buttons in the change name dialog break, and attempting to right click the tray icon does nothing. The only way to get the app working again is force quit it and relaunch. 

![gif](https://github.com/user-attachments/assets/bbffa464-895b-4661-9e4f-30bcc6e0a696)

**Steps to reproduce**
- While in split view mode, navigate to the settings page
- Press the right-side back button
- Press the left-side back button
- App is now broken

**Comment by ChrisSmith2** [comment]
Built the desktop app myself off of the latest version of the development branch (currently 34070330b48a135dee1c95a3e0e4467f8e410283). It appears the issue no longer occurs on this version.

**Comment by jjoelj** [comment]
Good to know, will close when there is a release
