### ISSUE TITLE
Contact titles scambled in notafications but not in BlueBubbles Client

### ISSUE THREAD

**Issue by micaslarsen** [BlueBubblesApp/bluebubbles-app#2799]
Since a couple of monthts ago all contant names are completly scrambled. Could this Firebase related in the way it handles id for message threaads?
Is there a manual way to sync this up or do i have to clear all data from the app to reconfigure the server connection?

The problem is identical to what's discussed on this [Reddit thread](https://www.reddit.com/r/BlueBubbles/comments/zr1iwj/contact_names_are_all_scrambled/)

**Comment by jjoelj** [comment]
If you change servers, you have to reset and re-sync the client as mentioned [here](https://docs.bluebubbles.app/server/basic-guides/migrating-servers). Otherwise, you will encounter several issues, including the one you're experiencing.

**Comment by micaslarsen** [comment]
Cool, thanks so much for the quick reply. I'll look into the docs later today.🙏
