### ISSUE TITLE
Sending Mentions is allowed by the UI but does not function on Sonoma+

### ISSUE THREAD

**Issue by Adrianmoder** [BlueBubblesApp/bluebubbles-app#2811]
For some reason, when @ someone in a gc it's doesn't get bolded like how it used to be. It appears just like typing out the name

**Comment by jjoelj** [comment]
Currently not supported on Sonoma+

**Comment by zlshames** [comment]
Actually, it is supported. We figured out that it wasn't that it's not supported on Sonoma+, but the ddScan flag breaks on Sonoma+. So we've disabled it for those versions
