### ISSUE TITLE
Messages missing even after sync

### ISSUE THREAD

**Issue by Anti-Apple4life** [BlueBubblesApp/bluebubbles-app#2816]
On newer clients (but not on 1.12.4 web) messages just disappear, even after i sync the last 25 ones.
![Web 1.12.4](https://github.com/user-attachments/assets/451115aa-45a0-4037-bc78-7878d4e80f0d)
![Desktop 1.13.2 beta](https://github.com/user-attachments/assets/41471e04-8427-4a55-8018-6969a405a29c)

**Comment by jjoelj** [comment]
This is a bug caused by the app not resetting properly. Deleting the app data and setting it up again will fix it.

**Comment by Anti-Apple4life** [comment]
Can confirm that fixed the issue, thanks!
