### ISSUE TITLE
Android client creating .jpg version of any heic images directly next to them

### ISSUE THREAD

**Issue by clansty** [BlueBubblesApp/bluebubbles-app#2826]
After I open the photos picker, bluebubbles android app created a `.heic.jpg` file with compressed size of image directly in filesystem next to the .heic file. this leads to same photo appear twice in phone's gallery app. File history app shows that these photos are created by Bluebubbles android app.

I think these files should be created in the app's private cache dir.

Bluebubbles app version `1.13.2 (20002066)` from Play store
Android version 14 with ColorOS 14.1

![dumplicated photos in file manager](https://github.com/user-attachments/assets/46886028-6f7a-477a-a871-f56b1b18ead9)
![Storage Isolation from Rikka shows files created by bluebubbles](https://github.com/user-attachments/assets/66863470-756a-4750-b696-d5653a80e6b4)

**Comment by mehapps** [comment]
I think this was fixed in v1.14.0 beta 1?

**Comment by zlshames** [comment]
> I think this was fixed in v1.14.0 beta 1?

Yes
