### ISSUE TITLE
x86_64.tar versions are not in assets since 1.13 BETA

### ISSUE THREAD

**Issue by tknz** [BlueBubblesApp/bluebubbles-app#2828]
x86_64.tar versions are not in assets since 1.13 BETA - Wondering if more recent Linux versions of the binaries will continue to be released? My use case can't use snaps or flatpak as it's getting installed by script in a custom Ubuntu Kasm Container workspace.

**Comment by jjoelj** [comment]
They will continue to be released when they are built. The binaries on GitHub are the same version as the latest desktop versions in all stores.
