### ISSUE TITLE
Group chat message error

### ISSUE THREAD

**Issue by kymerea** [BlueBubblesApp/bluebubbles-app#2844]
I'm not entirely sure what happened but I'll try my best to explain.

On one of the group chats, I sent a message and somehow that message was sent into a direct message to one of the group chat members. I'd closed the app at this point and when I recieved a message back my bluebubbles crashed maybe like 5 times before I could actually open the app and reply to the message. The message from my friend was from dms either because of the error I said before or somehow another error that the messages coming back went to DM. Although it does appear they sent the message to me in dms from iMessage on my mac. Either way a fairly confusing error and I don't know how replicable it is.

**Comment by zlshames** [comment]
> I'm not entirely sure what happened but I'll try my best to explain.
> 
> On one of the group chats, I sent a message and somehow that message was sent into a direct message to one of the group chat members. I'd closed the app at this point and when I recieved a message back my bluebubbles crashed maybe like 5 times before I could actually open the app and reply to the message. The message from my friend was from dms either because of the error I said before or somehow another error that the messages coming back went to DM. Although it does appear they sent the message to me in dms from iMessage on my mac. Either way a fairly confusing error and I don't know how replicable it is.

If you are getting a "system" crash popup. Can you please take an Interactive Bug Report and DM a google drive link to me or over discord.
