### ISSUE TITLE
BlueBubbles initial connection does not have a textarea to enter custom headers

### ISSUE THREAD

**Issue by vincentvella** [BlueBubblesApp/bluebubbles-app#2847]
In order to connect with advanced connection settings, I would need the ability to enter a custom header & client ID + my header and client secret. Because it's not allowing me to enter those it won't allow me to proceed to connect to my domain since it thinks the domain doesn't exist/is not reachable.

**Comment by zlshames** [comment]
Added into the next v1.15.0 release
