### ISSUE TITLE
Can't run Desktop App on Asahi Linux

### ISSUE THREAD

**Issue by AngusCrump** [BlueBubblesApp/bluebubbles-app#2856]
Attempting to run Bluebubbles from Asahi Linux results in error:
`bluebubbles: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory`

Installed using Flathub and Snap store to same result.

Note: Have used Bluebubbles on Asahi linux before but it's been awhile so an update probably broke it.

**Comment by jjoelj** [comment]
Hmm it should be trying to load libmpv.so.2. What version of the app are you running?

**Comment by AngusCrump** [comment]
`$ snap info bluebubbles
name:      bluebubbles
summary:   BlueBubbles client for Linux
publisher: BlueBubbles (jojejo)
store-url: https://snapcraft.io/bluebubbles
license:   unset
description: |
  BlueBubbles is an open-source and cross-platform ecosystem of apps aimed to bring iMessage to
  Android, Windows, Linux, and more! With BlueBubbles, you'll be able to send messages, media, and
  much more to your friends and family.
  
  
  **Important Note**
  
  
  The following features _are not_ supported on the Snap version:
  * In-app video playback
  * Signing in with Google
  
  These features _are_ supported on the Flatpak version, available here:
  
  https://flathub.org/apps/app.bluebubbles.BlueBubbles.
commands:
  - bluebubbles
snap-id:      6oNtWIWOaMA4O7xbzddHuvhprSnVXYmV
tracking:     latest/stable
refresh-date: today at 18:19 AEDT
channels:
  latest/stable:    1.14.0.0 2024-11-07 (80) 104MB -
  latest/candidate: ↑                              
  latest/beta:      ↑                              
  latest/edge:      1.14.0.0 2024-11-14 (81) 104MB -
installed:          1.14.0.0            (80) 104MB -`

**Comment by AngusCrump** [comment]
Same while using Flathub version:
$ flatpak info app.bluebubbles.BlueBubbles

BlueBubbles - BlueBubbles client for Linux

          ID: app.bluebubbles.BlueBubbles
         Ref: app/app.bluebubbles.BlueBubbles/aarch64/stable
        Arch: aarch64
      Branch: stable
     Version: 1.14.0.0
     License: Apache-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 2.7 GB
     Runtime: org.gnome.Platform/aarch64/46
         Sdk: org.gnome.Sdk/aarch64/46

      Commit: 7bd83db4a7f4969bb655dd5bb0c407975af03e5083b2bd24ff997d09e0842aef
      Parent: 58be26b2e112481d0769fd3d98549357058141fd4e62a9e2b8669f5c86eefc46
     Subject: Update description and captions (5ee2723f)
        Date: 2024-11-07 11:14:51 +0000

**Comment by jjoelj** [comment]
I just checked the binaries with `ldd` and for some reason the `x86_64` version depends on `libmpv.so.2`, while the `arm64` version depends on `libmpv.so.1`. I incorrectly assumed they'd need the same dependency. I'll update the snap and flathub configurations as soon as I can.

Edit: Will most likely just have the fixed version as 1.15. I'm about to release that anyway

**Comment by AngusCrump** [comment]
Thanks!

**Comment by jjoelj** [comment]
Turns out the issue was just that I had built the arm version on an older OS. I've updated my environment, so 1.15 should work as expected. The builds are in the process of being published. I will close this issue when they are released.

**Comment by jjoelj** [comment]
1.15 has been published to both stores

**Comment by AngusCrump** [comment]
Works!
