### ISSUE TITLE
Openbubbles, received messages - verification failed

### ISSUE THREAD

**Issue by Tumnus88** [BlueBubblesApp/bluebubbles-app#2859]
When a phone number was originally sending SMS but they enabled imessage, I receive the messages and get an error under the message that says verification failed. I can send them a message back and they receive it as if it's from iMessage. It's just when I receive their message it is green SMS and has the verification failed message. So sending and receiving works on the thread but it appears on my end like it's stuck in SMS, but on the other person's iPhone it looks normal.

**Comment by jjoelj** [comment]
Wrong repo
