### ISSUE TITLE
[Functional demand]Like iOS's IMSSAGE, you can hide the Subject column

### ISSUE THREAD

**Issue by fwz233-RE** [BlueBubblesApp/bluebubbles-app#2872]
![image](https://github.com/user-attachments/assets/35e22f97-b4ca-493a-badb-dc84c63a6e53)
Not
![image](https://github.com/user-attachments/assets/b742dc15-3567-4c59-83bc-f52ea0e575e7)

I don’t know if I can realize this demand. If the update was realized that day, I was willing to donate

**Comment by SpaceSaver** [comment]
Settings -> Private API -> Uncheck the subject option

**Comment by bronson** [comment]
Time to close this issue, that's exactly the solution.
