### ISSUE TITLE
Effect support

### ISSUE THREAD

**Issue by Bricktheworld** [BlueBubblesApp/bluebubbles-app#293]

**Comment by CSab6482** [comment]
I know this is probably more about showing effects than being able to send them, but @ eltoroloco04#5717 in the Discord mentioned [this](https://github.com/LumingYin/iMessageParity) MacForge/mySIMBL plug in that allows for sending Message effects from macOS.
https://github.com/open-imcore/imcore.react/issues/12
https://github.com/sgtaziz/WebMessage/issues/104

**Comment by CSab6482** [comment]
#976
