### ISSUE TITLE
Optimize Chat.addMessage to be more context-aware to prevent "over-processing"

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#307]

**Comment by tneotia** [comment]
Apparently we implicitly use transactions already in our update or delete queries so idk what exactly this ticket is wanting

Source: https://stackoverflow.com/a/54542762

**Comment by zlshames** [comment]
Fair enough. I think this was just an old ticket. probably not needed now. However, we probably do need to optimize the `Chat.addMessage` code to be more specific to the context of when the message is trying to be added. For instance, if it's being added when in headless mode, we don’t need to do any of the chatbloc updating stuff afaik. It's a fair bit of overhead we don’t need. There are a few other areas to need to improve that flow. I'll rename this ticket to re-purpose it.

**Comment by zlshames** [comment]
@tneotia can we close this with the rewrite
