### ISSUE TITLE
Scheduled messages

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#404]

**Comment by zlshames** [comment]
This was partially started, but not finished. Code is commented out for the most part

**Comment by zlshames** [comment]
This is now done on the server side. We just need a UI to create them from the client side

**Comment by zlshames** [comment]
@tneotia did u want this to be done for the rewrite or the release after it

**Comment by tneotia** [comment]
rewrite but after first alpha

**Comment by zlshames** [comment]
I'm going to say we should push this after the rewrite release

**Comment by tneotia** [comment]
done
