### ISSUE TITLE
Ability to download full chats from details page

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#487]

**Comment by Bricktheworld** [comment]
This one is boring zzzzzzzzzzzzz, I'm assigning to you

**Comment by zlshames** [comment]
@tneotia i saw you set the timeframes for the PDF. Should we also apply it to plaintext too?

**Comment by tneotia** [comment]
We can if you want, should be pretty easy to add that.

**Comment by zlshames** [comment]
> We can if you want, should be pretty easy to add that.

Yeah, i think i'd want it to be consistent

**Comment by tneotia** [comment]
@zlshames PR made
