### ISSUE TITLE
Add support to send notification for FaceTime call with private API

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#527]

**Comment by CSab6482** [comment]
Will this have nay kind of compatibility with Apple's upcoming FaceTime links feature? Or is that separate from this?

**Comment by zlshames** [comment]
> Will this have any kind of compatibility with Apple's upcoming FaceTime links feature? Or is that separate from this?

Potentially, however, I'm not sure how Apple will roll it out... Will it be available on older macOS devices or only the new ones with the latest macOS update

**Comment by tneotia** [comment]
Technically the app now notifies if a facetime call was started in a GC

**Comment by zlshames** [comment]
I think this is different. Want to keep it open for now

**Comment by tneotia** [comment]
added
