### ISSUE TITLE
Mismatch on tapbacks when a photo is sent together with a text message.

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/bluebubbles-app#542]
This isn't a huge deal, and I had this problem in AirMessage too (however, when sending a photo with text in BlueBubbles, the photo sends first and then the text which I think is done much better than AirMessage sending the text first).

So here on iOS we can see the tapbacks go with the text, not the image, but on BlueBubbles, the tapbacks show up on the image. Also, would it be possible to group the tapbacks into numbered clutters? Thanks for everything and good luck on finals,
- CSab

![iOS 1](https://user-images.githubusercontent.com/53708281/101992018-60a67680-3c7e-11eb-8e6c-495904a90061.png)
![iOS 2](https://user-images.githubusercontent.com/53708281/101992022-613f0d00-3c7e-11eb-89f1-d18502c58406.png)
![Android 1](https://user-images.githubusercontent.com/53708281/101992020-613f0d00-3c7e-11eb-873d-0388f59a0b59.jpg)
![Android 2](https://user-images.githubusercontent.com/53708281/101992019-60a67680-3c7e-11eb-8f33-6076c8a27b7d.jpg)

**Comment by CSab6482** [comment]
![iOS 1](https://user-images.githubusercontent.com/53708281/101992018-60a67680-3c7e-11eb-8e6c-495904a90061.png)
![iOS 2](https://user-images.githubusercontent.com/53708281/101992022-613f0d00-3c7e-11eb-89f1-d18502c58406.png)
![Android 1](https://user-images.githubusercontent.com/53708281/101992020-613f0d00-3c7e-11eb-873d-0388f59a0b59.jpg)
![Android 2](https://user-images.githubusercontent.com/53708281/101992019-60a67680-3c7e-11eb-8f33-6076c8a27b7d.jpg)
Here's another example

**Comment by Bricktheworld** [comment]
Hmmm ok, this is more of a design choice decision, but yes it definitely is very easy to do. Should we do it like how iOS does it? It's not really a mismatch, more of like a decision on which to put the reaction, because the image is part of the message, so does the image get the reaction or does the text?

**Comment by CSab6482** [comment]
I think the photo and text should have the ability to be treated as a separate message. For example on the latest nightly, long pressing for a reaction on either the text or the photo gives me the same option

**Comment by CSab6482** [comment]
I just had a similar problem with two photos that were sent together, I wanted to put different tapbacks on each photo but the two photos were treated as one message

**Comment by Bricktheworld** [comment]
> I think the photo and text should have the ability to be treated as a separate message. For example on the latest nightly, long pressing for a reaction on either the text or the photo gives me the same option

Well that's just not how iMessage works, they are essentially the same message, the message just has an attachment

**Comment by CSab6482** [comment]
Ah shoot. Okay I understand, I'll close this then

**Comment by CSab6482** [comment]
Reopening because I was just sent 4 pictures and wanted to add different tapbacks to each photo, but all 4 were treated as one message.

**Comment by CSab6482** [comment]
Even though it is one message with multiple parts, I still feel that each piece of the message should have the individual ability to have a tapback on it

**Comment by CSab6482** [comment]
Also mentioned [here](https://github.com/iandwelker/smserver/issues/81)

**Comment by CSab6482** [comment]
https://github.com/sgtaziz/WebMessage/issues/51#issuecomment-782634724
sgtaziz fixed this in WebMessage, however since that server runs on iOS and this one runs on macOS I'm not sure how comparable the code is

**Comment by CSab6482** [comment]
[Here](https://github.com/iandwelker/smserver/issues/81#issuecomment-798832580) is a similar issue in SMServer, as well as [the same issue](https://github.com/sgtaziz/WebMessage/issues/51#issuecomment-797713234) in WebMessage

**Comment by CSab6482** [comment]
https://github.com/open-imcore/imcore.react/issues/8#issuecomment-816035066
![BlueBubbles Obama](https://user-images.githubusercontent.com/53708281/114327667-fad0db00-9b07-11eb-968c-a5a2774669e2.jpg)
![Obama iOS](https://user-images.githubusercontent.com/53708281/114076603-d4474180-9874-11eb-81b3-e9300226529c.png)

**Comment by CSab6482** [comment]
https://github.com/open-imcore/imcore.react/issues/8#issuecomment-817379826 Also issue #714
![BlueBubbles 3](https://user-images.githubusercontent.com/53708281/114327688-19cf6d00-9b08-11eb-984c-99f265126583.jpg)
![PNG image (1)](https://user-images.githubusercontent.com/53708281/114327689-1b993080-9b08-11eb-9019-1e1e7731a83c.png)

**Comment by CSab6482** [comment]
Here's another situation with one message that has multiple parts (this time both text and attachments)

Here is the conversation on iOS
![iOS](https://user-images.githubusercontent.com/53708281/118409211-3b67cb00-b657-11eb-817d-f4c142f7aa0d.png)
and in BlueBubbles
![BlueBubbles](https://user-images.githubusercontent.com/53708281/118410993-5ab72600-b660-11eb-96d9-13616199639c.jpeg)
Below is some message information that I copied from MyMessage
> {
  "id": "28935DBA-A57E-485E-9442-10FBAD3A3C95",
  "fromMe": true,
  "isTypingMessage": false,
  "description": "Here is a message that has images intermittently scattered throughout it",
  "flags": 1085445,
  "fileTransferIDs": [
    "49CA2847-DF32-4D66-9857-7163EE1FCE49",
    "9C606BB6-2443-4101-A55A-8E2610D08988",
    "00A6CB41-165B-43B8-881F-59D725515B36"
  ],
  "chatID": "*recipient*",
  "time": 1620776404411,
  "timeRead": 0,
  "isSOS": false,
  "timeDelivered": 1620776405263.5593,
  "isAudioMessage": false,
  "isCancelTypingMessage": false,
  "items": [
    {
      "type": "text",
      "payload": {
        "id": "p:0/28935DBA-A57E-485E-9442-10FBAD3A3C95",
        "chatID": "*recipient*",
        "parts": [
          {
            "type": "text",
            "string": "Here is a message"
          }
        ],
        "fromMe": true,
        "time": 1620776404411,
        "text": "Here is a message"
      }
    },
    {
      "type": "attachment",
      "payload": {
        "metadata": {
          "size": {
            "width": 200,
            "height": 200
          },
          "id": "49CA2847-DF32-4D66-9857-7163EE1FCE49",
          "filename": "IMG_1752.png",
          "uti": "public.png",
          "mime": "image/png"
        },
        "id": "p:1/28935DBA-A57E-485E-9442-10FBAD3A3C95",
        "chatID": "*recipient*",
        "transferID": "49CA2847-DF32-4D66-9857-7163EE1FCE49",
        "fromMe": true,
        "time": 1620776404411
      }
    },
    {
      "type": "text",
      "payload": {
        "id": "p:2/28935DBA-A57E-485E-9442-10FBAD3A3C95",
        "chatID": "*recipient*",
        "parts": [
          {
            "type": "text",
            "string": "that has images"
          }
        ],
        "fromMe": true,
        "time": 1620776404411,
        "text": "that has images"
      }
    },
    {
      "type": "attachment",
      "payload": {
        "metadata": {
          "size": {
            "width": 200,
            "height": 200
          },
          "id": "9C606BB6-2443-4101-A55A-8E2610D08988",
          "filename": "IMG_3897.png",
          "uti": "public.png",
          "mime": "image/png"
        },
        "id": "p:3/28935DBA-A57E-485E-9442-10FBAD3A3C95",
        "chatID": "*recipient*",
        "transferID": "9C606BB6-2443-4101-A55A-8E2610D08988",
        "fromMe": true,
        "time": 1620776404411
      }
    },
    {
      "type": "text",
      "payload": {
        "id": "p:4/28935DBA-A57E-485E-9442-10FBAD3A3C95",
        "chatID": "*recipient*",
        "parts": [
          {
            "type": "text",
            "string": "intermittently scattered"
          }
        ],
        "fromMe": true,
        "time": 1620776404411,
        "text": "intermittently scattered"
      }
    },
    {
      "type": "attachment",
      "payload": {
        "metadata": {
          "size": {
            "width": 200,
            "height": 200
          },
          "id": "00A6CB41-165B-43B8-881F-59D725515B36",
          "filename": "IMG_4390.png",
          "uti": "public.png",
          "mime": "image/png"
        },
        "id": "p:5/28935DBA-A57E-485E-9442-10FBAD3A3C95",
        "chatID": "*recipient*",
        "transferID": "00A6CB41-165B-43B8-881F-59D725515B36",
        "fromMe": true,
        "time": 1620776404411
      }
    },
    {
      "type": "text",
      "payload": {
        "id": "p:6/28935DBA-A57E-485E-9442-10FBAD3A3C95",
        "chatID": "*recipient*",
        "parts": [
          {
            "type": "text",
            "string": "throughout it"
          }
        ],
        "fromMe": true,
        "time": 1620776404411,
        "text": "throughout it"
      }
    }
  ],
  "service": "iMessage",
  "timePlayed": 0,
  "sender": "*me*",
  "isDelivered": true
}

I made a similar comment for AirMessage [here](https://github.com/airmessage/airmessage-android/issues/3#issuecomment-841861771).

**Comment by CSab6482** [comment]
Another example. I wanted to place different tapbacks on each of these images, but BlueBubbles groups all of the images into one message that can only receive one tapback.
![Screenshot_20210707-174253](https://user-images.githubusercontent.com/53708281/124832995-7e556900-df4b-11eb-891e-f7f25c0821d4.jpg)

**Comment by CSab6482** [comment]
Is it okay to close this issue?

**Comment by zlshames** [comment]
Not yet. Needs to be implemented client-side

**Comment by tneotia** [comment]
Completed in full rewrite
