### ISSUE TITLE
Request: chat heads and bubbles (like Google Messages in Android 11)

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#638]
it would be nice to have

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@cdi` in `#baffoonery`.

**Comment by zlshames** [comment]
Apparently Brandon had started this code, and commented it out. It doesn't fully work, but it kinda does. If we put some work into it, it will work

**Comment by zlshames** [comment]
Turns out the VM gets killed for some reason when you open the chat head. Not sure why
