### ISSUE TITLE
SMS relay from Android App to iMessage Client on macOS

### ISSUE THREAD

**Issue by clubtech** [BlueBubblesApp/bluebubbles-app#700]
Currently it seems that only iMessages sync over to the Android client. Any SMS received on the iOS device is not synced over even though I have the iPhone set to forward all texts to the Mac that has the bluebubbles server installed.

**Comment by SoPat712** [comment]
This is currently only supported on the Desktop app, it'll be a while before the devs can get around to adding this to the android apps as well.

**Comment by zlshames** [comment]
> Currently it seems that only iMessages sync over to the Android client. Any SMS received on the iOS device is not synced over even though I have the iPhone set to forward all texts to the Mac that has the bluebubbles server installed.

I want to add a native way to text via SMS, rather than via iMessage like the Desktop app does. This will take more time, especially with other efforts such as material theme, samsung theme, and other things going on. Will keep these tickets open until we complete that task.

**Comment by zlshames** [comment]
Dupe: https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/21

**Comment by clubtech** [comment]
This is not a duplicate of #21 . That topic asks to integrate Android's SMS into the app (i.e for users to be able to send native SMS using BlueBubbles)
I am asking for SMS relay FROM the iPhone (i.e. to be able to send/receive SMS that is received on the iPhone and is relayed to other Apple devices such as the Mac which has the Bluebubbles server installed on it).
These two are not the same requests.

**Comment by zlshames** [comment]
> This is not a duplicate of #21 . That topic asks to integrate Android's SMS into the app (i.e for users to be able to send native SMS using BlueBubbles)
> I am asking for SMS relay FROM the iPhone (i.e. to be able to send/receive SMS that is received on the iPhone and is relayed to other Apple devices such as the Mac which has the Bluebubbles server installed on it).
> These two are not the same requests.

All, my fault. Re-opening. This would be a solution similar to SMServer's solution. Most likely a Jailbreak rweak

**Comment by clubtech** [comment]
I think your desktop client already does this. It simply grabs the SMS messages from the mac and relay them over to the client. This should not require a jailbroken iPhone as all texts are received on the mac and can be sent via the mac.

**Comment by zlshames** [comment]
> I think your desktop client already does this. It simply grabs the SMS messages from the mac and relay them over to the client. This should not require a jailbroken iPhone as all texts are received on the mac and can be sent via the mac.

Our desktop client does it via iMessage on your macOS server. The issue with that is it relies on the server for SMS. In a perfect solution, we want it natively integrated with the SMS API. I don’t think I will add SMS non-natively to the Android client (like we do in desktop), since native SMS API is an option

**Comment by zlshames** [comment]
Closing as it's a dupe

**Comment by tneotia** [comment]
Finally completed
