### ISSUE TITLE
Sending many attachments often send out of order

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#714]
I sent 13 photos and they were sent in the order 1, 12, 6, 7, 13, 8, 10, 11, 3, 2, 4, 5, 9. Regarding AirMessage, Tagavari said in his 1-6-21 post that his protocol 5.2 change 

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by CSab6482** [comment]
Whoops, I used quotes in my description which is a no-no, here it is in full

I sent 13 photos and they were sent in the order 1, 12, 6, 7, 13, 8, 10, 11, 3, 2, 4, 5, 9. Regarding AirMessage, Tagavari said in his 1-6-21 post that his protocol 5.2 change "adds a 'sort' parameter for attachments, which should eliminate any edge cases where a message with multiple attachments has its attachments displayed out of order". Maybe this would be possible to implement once it's open source?

Also I made a typo in the title, I meant to say "Sending many attachments often sends them out of order" but that's just a tiny thing

**Comment by CSab6482** [comment]
I have more info on this. I sent Zach 4 images as one message from iOS (technically from WebMessage, but WebMessage is hosted on iOS). When looking at the conversation on an Apple device, the attachments correctly show in the order 1, 2, 3, 4. However, looking at the conversation details page has the images in a different order. Below is my Mac's details page.
![Screen Shot 2021-03-29 at 3 56 22 PM](https://user-images.githubusercontent.com/53708281/112893842-2f28ae00-90a9-11eb-86e0-eba106c61601.png)
This incorrect 1, 4, 2, 3 order is the exact same order that BB Android and Desktop displays the images in. And another minor bug is that the ordering in the Android details page is also incorrect
![order android](https://user-images.githubusercontent.com/53708281/112893956-4bc4e600-90a9-11eb-88e9-f029593f691f.jpg)

**Comment by CSab6482** [comment]
Here's another example. The images show up in the correct 1, 2, 3, 4 order in my messages transcript on my Mac, but they were in the incorrect order in the details page (2, 1, 4, 3). The Android app shows the 2, 1, 4, 3 order.
![Screen Shot 2021-03-29 at 9 26 28 PM](https://user-images.githubusercontent.com/53708281/112920288-a3c61180-90d6-11eb-95b3-68a281633c10.png)
I have filed a bug report with Apple [here](https://www.apple.com/feedback/messages-ios-ipados.html). The macOS version is available [here](https://www.apple.com/feedback/messages.html). Please file an issue if you can

**Comment by tneotia** [comment]
@CSab6482 is this still an issue?

**Comment by CSab6482** [comment]
> @CSab6482 is this still an issue?

I'm currently in exams, so I'll test this on Friday October 1. Also I'll upload my photos for #617

**Comment by tneotia** [comment]
Resolved by multi part message support
