### ISSUE TITLE
When someone leaves a group chat, their contact photo gets messed up

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#719]
I assume this is because the chata database is trying to create an entry for someone who isn't in the registry and then things get wonky, in my case, one person who left the chat took the contact photo of someone else who was still in the chat when looking at their previous messages

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by zlshames** [comment]
Hmmm, "participant" info is stored in the `handle` database table. That table contains their address and nothing _that_ valuable other than that. Those are then added to a pivot table to connect to chats. If someone leaves a chat, the only thing that is removed is that link in the pivot table between the handle and the chat. All the handle data (the user address) stays the same. I'm not sure why it would go "defunct". But I can look into it.

**Comment by zlshames** [comment]
@tneotia after that test last night with the adding/removal of participants, is this fixed?

**Comment by tneotia** [comment]
didnt get this issue
