### ISSUE TITLE
Received multiple photos, attempting to open one opens an incorrect photo, exiting back to the chat crashes my phone (0.1.16 rc-1)

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/bluebubbles-app#783]
![Screenshot_20210216-205018_Discord](https://user-images.githubusercontent.com/53708281/108145006-bc371b00-7098-11eb-9f9f-b72be7730cdd.jpg)
[Here](https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/542) are the [links](https://github.com/iandwelker/smserver/issues/81) that were mentioned in the message.

**Comment by CSab6482** [comment]
I've got more info on this. It looks like the magic number is 24. The details page can't display more than 24 images, and if it does, if you go in the chat and scroll above what the bottom-most image in the details page is and tap it, you get taken to the last image.

**Comment by CSab6482** [comment]
https://github.com/sgtaziz/WebMessage/issues/51#issuecomment-782634724

**Comment by tneotia** [comment]
@CSab6482 still an issue?

**Comment by CSab6482** [comment]
https://github.com/BlueBubblesApp/bluebubbles-app/issues/714#issuecomment-930505743
We should use the gc to test these
