### ISSUE TITLE
Google Duo calling from details page

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#803]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#general`.

**Comment by zlshames** [comment]
This can either be done via a plugin, or custom code to invoke an intent in the Java code, via the MethodCallHandler class

**Comment by tneotia** [comment]
Tried this, it dont work. I havent seen any other app be able to invoke Duo besides Google Messages and the native Samsung phone app. Seems like the intent isnt well documented or isnt meant for 3rd parties.

**Comment by tneotia** [comment]
done
