### ISSUE TITLE
If someone sends a text immediately after an Unknown Group Event, no contact name shows up above the text

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#808]
I received this bug while using the material theme, and when switching to the iOS and Samsung themes, it was still there

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-bugs`.

**Comment by tneotia** [comment]
Completed in full rewrite
