### ISSUE TITLE
Notification when removed from a conversation

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#822]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#requests`.

**Comment by zlshames** [comment]
This should not be toggle-able. Should be a always-on feature

**Comment by tneotia** [comment]
iMessage does not send an explicit message saying you were removed. It acts the same way as if you leave the conversation yourself, so there isn't really a way to tell unfortunately (and iMessage itself says "you left the conversation").
