### ISSUE TITLE
Reactions placed on attachments don't show up in SMServer, WebMessage, or MyMessage

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/bluebubbles-app#823]
@iandwelker @sgtaziz @EricRabil
![Weird Bug](https://user-images.githubusercontent.com/53708281/115468924-c8a73380-a201-11eb-8ac9-541cc733f393.jpg)
![Worked](https://user-images.githubusercontent.com/53708281/115468928-c9d86080-a201-11eb-875c-0b17df319754.png)
![Tapback is weird](https://user-images.githubusercontent.com/53708281/115469247-479c6c00-a202-11eb-9f43-9b2b36efb66d.png)
They show up okay in the BlueBubbles Desktop app though.

**Comment by CSab6482** [comment]
Update - This seems to only affect attachments. As of now, I've only noticed it on images. I will update the title/comments if I can confirm that it happens on other attachments.

**Comment by CSab6482** [comment]
Here is a similar situation, however, it is also bugged in the BlueBubbles Desktop app (similar to [this example](https://github.com/BlueBubblesApp/BlueBubbles-Desktop-App/issues/196#issuecomment-831580960)). This situation is a little different, because I sent the tapback directly through the macOS messages app, not through BlueBubbles.
![Shaq](https://user-images.githubusercontent.com/53708281/117235894-972f8a00-adf5-11eb-9947-220ae5b7c24f.png)
![PNG image](https://user-images.githubusercontent.com/53708281/117236364-8895a280-adf6-11eb-90b5-d2e8566837bb.png)

**Comment by CSab6482** [comment]
Given the previous comment that had the wrong tapback displayed even though BlueBubbles was not involved, I think this is a macOS bug rather than a BlueBubbles one (see [here](https://github.com/BlueBubblesApp/BlueBubbles-Server/issues/188))

**Comment by tneotia** [comment]
Probably completed in full rewrite, considering we use the partIndexes properly
