### ISSUE TITLE
Ability to save configurations to the server

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#842]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@cdi` in `#requests`.

**Comment by zlshames** [comment]
Related Issue: https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/874

**Comment by zlshames** [comment]
This will require coordination with updates to the Server to support this action

**Comment by tneotia** [comment]
Local import / export is done, we now need a server endpoint to complete this ticket
