### ISSUE TITLE
New chat creator will sometimes auto-prefix phone numbers with wont international code

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#848]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#feedback`.

**Comment by zlshames** [comment]
Marked as hard because this will be fairly hard to replicate for me because I do not have an International number (relative to the US)

**Comment by tneotia** [comment]
Don't think this is an issue anymore
