### ISSUE TITLE
Better sticker support (GIF support & better layout)

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/bluebubbles-app#851]
Below is the same conversation in BlueBubbles and on macOS. Only two of the five stickers show up on Android, and four of those stickers (all except for the "Party!" one in the top left) are GIFs rather than static images. Neither of the GIFs move on Android, though I have had other stickers that are GIFs that do play properly on Android (see [here](https://github.com/airmessage/airmessage-android/issues/4)). [This](https://apps.apple.com/us/app/spongebob-stickers/id1244244590?app=messages) is the sticker pack.
![Screenshot_20210518-120804](https://user-images.githubusercontent.com/53708281/118688636-3bd9a080-b7d4-11eb-811a-b9d883dc1934.jpg)
![Screen Shot 2021-05-18 at 12 13 11 PM](https://user-images.githubusercontent.com/53708281/118688263-e56c6200-b7d3-11eb-84f7-e33fccfb273e.png)

**Comment by zlshames** [comment]
Ultimately, we need to organize the stickers a bit better. Right now, they are "stacked" on top of each other. It looks like Apple lays them out in a row for the most part.

@CSab6482 if the message is really short, how does Apple layout the stickers

**Comment by zlshames** [comment]
Marking this as `hard` because you have to understand how the "Stack" of message items works. It should be marked as `medium` if you already know this.

**Comment by CSab6482** [comment]
> @CSab6482 if the message is really short, how does Apple layout the stickers

Here is an example from iOS

https://user-images.githubusercontent.com/53708281/122244112-9bd66c00-ce92-11eb-9471-6d41280c6ec5.mp4

![IMG_0739](https://user-images.githubusercontent.com/53708281/122244119-9da02f80-ce92-11eb-97a4-ee0130c8055a.PNG)
and the same conversation in BlueBubbles
![Screenshot_20210615-100629](https://user-images.githubusercontent.com/53708281/122244164-a7299780-ce92-11eb-868f-fbc7ab04b497.jpeg)
![Screenshot_20210615-100635](https://user-images.githubusercontent.com/53708281/122244170-a8f35b00-ce92-11eb-8cb9-e679862b6841.jpeg)
and just so I can have these photos all in one place, here's [AirMessage](https://github.com/airmessage/airmessage-android/issues/4)
![Screenshot_20210616-111641_AirMessage](https://user-images.githubusercontent.com/53708281/122246365-7ba7ac80-ce94-11eb-88b4-e606f8b0eac4.jpg)
I feel like AirMessage did a better job in this case since it shows not only the narwhal, but also a bit of SpongeBob and the dog, even though they are stacked and not spaced out. Also, the "and" and "huh?" texts were correctly covered by the emoji stickers in AirMessage.
