### ISSUE TITLE
Reactions can take a long time to display

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#853]
[Android RC5] When a reaction is sent via the Private API, it is sent to the Mac (and recipient) instantly as expected, but can take up to 5 minutes to show as sent in the android app. This issue is present in rc5, and also older versions. My Mac is running High Sierra, not sure if that's relevant.

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@electronika` in `#android-bugs`.

**Comment by zlshames** [comment]
I've only seen this happen when the helper was ultimately disabled and the reaction was sent via AppleScript. The only argument I have against that is the AppleScript isn't as good on High Sierra, compared to Catalina. That said, I think this needs a bit more info, and maybe some more anecdotal instances

**Comment by tneotia** [comment]
@romhacks this still an issue?

**Comment by romhacks** [comment]
No, it's resolved in newer client versions :)
