### ISSUE TITLE
GIFs play at a faster speed than normal

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#890]

**Comment by CSab6482** [comment]
Here are two gifs provided by @ Bsloanlndy# 0955 in the Discord
![1624028484058](https://user-images.githubusercontent.com/53708281/122601001-a46ba580-d03e-11eb-8848-b058359f5c68.gif)
![1624036498004](https://user-images.githubusercontent.com/53708281/122601009-a6cdff80-d03e-11eb-8cf0-4a9b353d79a8.gif)
Along with a screen recording of how it looks in BlueBubbles.

https://user-images.githubusercontent.com/53708281/122601135-d846cb00-d03e-11eb-9adc-34bd1f5fee56.mp4

**Comment by CSab6482** [comment]
Also from @ Bsloanlndy# 0955 https://github.com/flutter/flutter/issues/29130

**Comment by CSab6482** [comment]
I found another one
![1628483949945](https://user-images.githubusercontent.com/53708281/128661201-f2abe9b4-8115-4040-b16d-3ec494fe1e09.gif)

https://user-images.githubusercontent.com/53708281/128661206-3f9c7190-1427-41d3-91c4-600b0f68b1aa.mp4

**Comment by tneotia** [comment]
Fixed
