### ISSUE TITLE
[GetX Migration] Migrate all theming

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#941]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#community-contributions`.

**Comment by zlshames** [comment]
Marking this as hard because of all the little nuances with Theming using GetX. Things just don't seem to update the way we want it to.

**Comment by tneotia** [comment]
tbh prolly dont need to do this - if it aint broke, dont fix it
