### ISSUE TITLE
Stickers flash when message is sent

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#985]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@isaac` in `#android-bugs`.

**Comment by CSab6482** [comment]
From @ Isaac#9000 in the Discord

https://user-images.githubusercontent.com/53708281/123724375-3b640900-d85a-11eb-89f6-7f2bc945baa2.mp4

**Comment by CSab6482** [comment]
From @ isaac#9000 in the Discord

https://user-images.githubusercontent.com/53708281/123724375-3b640900-d85a-11eb-89f6-7f2bc945baa2.mp4

**Comment by CSab6482** [comment]
#851
